### ISSUE TITLE
Feature request: integration with Ombi

### ISSUE THREAD

**Issue by ElevonsJKeloids** [hrfee/jfa-go#1]
It would be helpful if jfa could integrate with Ombi's user database, and when a user is signed up for Jellyfin they are added to Ombi with their email and username/password.

**Comment by hrfee** [comment]
I'll have a look into this.

**Comment by hrfee** [comment]
I've added this in ba67fa753629014b4f8c825b75c66e18f7531ffb. You need an API key from Ombi which you can put in the "Ombi integration" section of the settings, as well as the server URL. Once done, you need to create a template user in Ombi from which the roles and permissions will be grabbed and used through the "Ombi user defaults" menu in the jfa-go settings. New users will then be created automatically on Ombi.

**Comment by hrfee** [comment]
I'll publish a package and bump the version for this later.
