### ISSUE TITLE
ISSUE INSTALL

### ISSUE THREAD

**Issue by ernandesdias** [hrfee/jfa-go#10]
Hi there,

When I run:
#go run setup.go

returns
#command-line-arguments
./setup.go:13:12: undefined: appContext
./setup.go:16:15: undefined: newJellyfin

Could you help me?

**Comment by hrfee** [comment]
Sorry if the file names are a bit confusing. If you've just cloned the repository, then you'll need to compile the code. You can find a guide in the wiki. If you don't want to compile, then download a build in the releases section.

**Comment by benildo** [comment]
Download the last version:

https://github.com/hrfee/jfa-go/releases/tag/v0.2.0

**Comment by hrfee** [comment]
Yeah, download the one for your system and then extract the archive and run the `jfa-go` or `jfa-go.exe` executable in a terminal.

**Comment by ernandendias** [comment]
I'm trying to install at Ubuntu Server 20.04. 
I've downloaded [jfa-go_0.2.0_Linux_x86_64.tar.gz](https://github.com/hrfee/jfa-go/releases/download/v0.2.0/jfa-go_0.2.0_Linux_x86_64.tar.gz)

When I run the **jfa-go** in a terminal I got the message:

![image](https://user-images.githubusercontent.com/73147233/96611372-f8b55e80-12d2-11eb-9a4f-c11c1df2ed6f.png)

**Comment by hrfee** [comment]
Weird. Could you make sure `/root/.config` exists first, and then install this [new](https://builds.hrfee.pw/repo/hrfee/jfa-go/build/9abb17742700dfc3aebbadfdb513390b72888550/jfa-go_v0.0.0-testing_Linux_x86_64.tar.gz) version and try it again? If the same problem occurs, it will print the full error message so I can figure out whats going on.

**Comment by ernandendias** [comment]
Hi there @hrfee Thanks for your help

There's no **/root/.config**
I've dowloaded the [new](https://builds.hrfee.pw/repo/hrfee/jfa-go/build/9abb17742700dfc3aebbadfdb513390b72888550/jfa-go_v0.0.0-testing_Linux_x86_64.tar.gz) version, but the same problem :(

![image](https://user-images.githubusercontent.com/73147233/96733002-5a3b0300-138f-11eb-81ed-f534364d17bd.png)

**Comment by hrfee** [comment]
Ah, ok, just create `/root/.config` and it'll work then. I'll make it do this automatically for future users.

**Comment by ernandesdias** [comment]
Oh yeah! It worked out after create the folder!
Thanks!

![image](https://user-images.githubusercontent.com/73147233/96921937-9486cc00-1485-11eb-8b41-a7ac31a4bd26.png)
