### ISSUE TITLE
sending wrong mail invite link

### ISSUE THREAD

**Issue by Marios1231** [hrfee/jfa-go#100]
Hey i set up jfa and everything is good but when I put an email to send an invite the link is wrong like the link would be like 
https://www.example.com/accounts/evFWXQQAEsJ5ovrkkWp58k but its supposed to be 
https://www.example.com/accounts/invite/evFWXQQAEsJ5ovrkkWp58k
thank you

**Comment by hrfee** [comment]
Settings > Invite Emails > URL base should have `/invite` on the end of it. This is a weird remnant of when there was no proper URL Base option and I haven't merged the two together yet.

**Comment by Marios1231** [comment]
thank you for the fast reply appreciate it
