### ISSUE TITLE
Jellyfin login broken after user creation

### ISSUE THREAD

**Issue by lyz-code** [hrfee/jfa-go#101]
The latest versions of Jellyfin have an issue where [the login page get's stuck with an endless spin](https://github.com/jellyfin/jellyfin-web/issues/2507). I'm able to patch it with the [last snippet of the last comment](https://github.com/jellyfin/jellyfin-web/issues/2507#issuecomment-809977045), but each time a new user is created with jfa-go, the error reappears.

I don't know if it's something you can patch on your side, or we need to wait till Jellyfin fixes it by themselves. Maybe something changed in the user management in the last versions that jfa-go needs to adapt. I'm not sure. What do you think?

**To Reproduce**

* Start a clean Jellyfin with version 10.6.4, with the linuxserver docker.
* Create a user
* Stop the server, and start it with version 10.7.1 or above. Now the login should be broken
* Apply the fix:

    ```bash
    systemctl stop jellyfin.service
    mv /var/lib/jellyfin/data/jellyfin.db{,.bak}
    systemctl start jellyfin.service
    # [ Go to JF URL, get asked to log in even though there are no Users in the JF DB now]
    systemctl stop jellyfin.service
    mv /var/lib/jellyfin/data/jellyfin.db{.bak,}
    systemctl start jellyfin.service
    ```
* Try logging in (it should work fine)
* Create a user with the invite from jfa-go
* Try to log in (it will spin up forever again)

**Platform/Version**

jfa-go version 0.3.4 using the official docker.

**Comment by hrfee** [comment]
Does it break when you create an account directly through Jellyfin? Also, looking through the logs posted on those issues, I also get  SQL `FROM \"DisplayPreferences\"` looking errors, i've just been restarting/updating Jellyfin each time to fix it, never considered it could be hapenning each time i test out jfa-go.

**Comment by hrfee** [comment]
Just tried and I can't reproduce. Could you try re-making any profiles you have in jfa-go? Maybe its related to missing fields added in more recent JF versions.

**Comment by lyz-code** [comment]
I'm so sorry for answering with such a big delay. Recreating the profiles did the trick :)
