### ISSUE TITLE
[FEATURE REQUEST] Set password for password reset

### ISSUE THREAD

**Issue by john-sp** [hrfee/jfa-go#103]
Instead of setting the password to the pin for the web reset, allow the user to set the password on jfa-go. It would make it easier for the user to not have to change the password after logging in. 

It also could allow be expanded for the entire reset process to be in JFA, and not have to rely on Jellyfin to create a pin.

**Comment by hrfee** [comment]
Sorry i didn't respond to this earlier, was bogged down by exams and finishing the matrix integration.

This was actually something I wanted to do with the first version of jellyfin-accounts, but felt it was kinda jank. I've since added magic links for password resets which are also equally janky so i'll add this as an optional feature. Should be done in a few days, maybe a week.

**Comment by hrfee** [comment]
only just started on this, but i'm almost done adding the option to set the new password through magic links. When/if I add a self-contained reset route I would also want to add a page for Jellyfin users which they can change/add contact methods through as well as reset their password, so it'll take a while.

**Comment by hrfee** [comment]
Pushed, should be available on unstable builds in the next 10 minutes. Enable "Use reset link" and "Set password through link" in Settings > Password Resets, and the link sent to the user when they request a reset through Jellyfin should have a prompt the the new password.

**Comment by john-sp** [comment]
I updated to the latest unstable with docker and am on commit 21b373a, which does not exist 😞. The button for set password through link does not exist for me. I will wait for docker to properly update it (maybe it is and the commit is wrong) and see if it works.

**Comment by hrfee** [comment]
Yeah, there was a dumb mistake in that commit I think so I force-pushed and overwrote it.
