### ISSUE TITLE
jfa-go tray crashes on launch

### ISSUE THREAD

**Issue by LeviSnoot** [hrfee/jfa-go#105]
**Describe the bug**

When I open the .exe I can see the icon in the tray for a couple of seconds before it disappears. Task Manager shows it's closing soon after launch.

**To Reproduce**

1. Extract jfa-go_0.3.6_TrayIcon_Windows_x86_64.zip
2. Open jfa-go.exe

**Logs**

Can't get far enough to get a log.

**Configuration**

No config file available.

**Platform/Version**

Windows 10 Pro version 20H2

**Comment by hrfee** [comment]
Could you open it in a terminal? You can shift-right click anywhere in the folder containing the executable and press "Open Powershell Window here", and then type `jfa-go.exe` and press enter. That way you should be able to see the logs.

**Comment by LeviSnoot** [comment]
Here's what I get following those instructions:
```
PS C:\jfa-go> jfa-go.exe
jfa-go.exe : The term 'jfa-go.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ jfa-go.exe
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (jfa-go.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by hrfee** [comment]
Start typing it again and pressing tab maybe? It should auto complete and then you can press enter again.

**Comment by LeviSnoot** [comment]
Ohhh true lol, so I did it and it just launches the program and prints nothing:
```
PS C:\jfa-go> .\jfa-go.exe
PS C:\jfa-go>
```

**Comment by hrfee** [comment]
That's really weird, never had a case where nothing output at all before, nor can I reproduce the behaviour (on Linux through WINE atleast). Could you try deleting `C:\Users\<your username>\AppData\Roaming\jfa-go` if it exists and running again?

**Comment by hrfee** [comment]
Ah, just switched over to Windows and got it. It closes and a windows network thing pops up, Accepted it and ran it again but it's still not working.
<img width="525" alt="Capture" src="https://user-images.githubusercontent.com/11923517/119532583-ecb7e080-bd7c-11eb-8afc-cf2e480f6a85.PNG">

**Comment by LeviSnoot** [comment]
Thank you! This fixed it!
