### ISSUE TITLE
[Issue] Reset Password Notification not working with Telegram

### ISSUE THREAD

**Issue by xiNeRoar** [hrfee/jfa-go#108]
#### Read the [FAQ](https://github.com/hrfee/jfa-go/wiki/FAQ) first!

**Describe the bug**

No telegram notification when pressed on jellyfin's reset password

**To Reproduce**

1. Create a invite code in jfa-go (30mins/ 1user only)
2. Create an account with that invite code with telegram linked up
3. Press forgot password on jellyfin with that registered account
4. Nothing sent to the linked up telegram account

I have checked there is a password.json under jellyfin/config directory, it is just jfa does not send out notification via telegram to users

**Comment by hrfee** [comment]
Oops, forgot to test password resets. Not all of the characters telegram wants escaped were escaped. Should be fixed in the nightly.

**Comment by xiNeRoar** [comment]
@hrfee Sorry to bother but where can i know if the bug is fixed and a new version is released?

**Comment by hrfee** [comment]
It was fixed in commit fb6256d, which is available in the nightly builds now.

**Comment by xiNeRoar** [comment]
@hrfee sorry i might be a bit dumb, may i know what is a "nightly build"? where can i install it?

**Comment by hrfee** [comment]
If you're using a pre-compiled executable from the releases section, use one of [these](https://builds.hrfee.pw/view/hrfee/jfa-go). If you're using Docker, use the `hrfee/jfa-go:unstable` tag. If you're using the AUR version, switch to [jfa-go-git](https://aur.archlinux.org/packages/jfa-go-git/)/

**Comment by xiNeRoar** [comment]
@hrfee Thank you, i am using docker "stable" tag of jfa-go atm. I will switch it to unstable then.

**Comment by xiNeRoar** [comment]
@hrfee i changed the docker version to "unstable" tag and the telegram notification works, but the reset url in the message was not showing my domain, may i know where can i change the reset link?
```
Hi demo,

Someone has recently requested a password reset on Jellyfin.

If this was you, click the link below.

The code will expire on 29/05/21, at 17:41 UTC, which is in 30m.

If this wasn't you, please ignore this.

PIN: http://accounts.jellyf.in:8056/reset?pin=39-83-76-A6

Need help? contact me.
```

**Comment by hrfee** [comment]
I know it's a little weird, but Settings > Invite Emails > URL Base. Set it to your url and add `/invite` to the end. If it's hidden, enable invite emails, write the url, then disable it and save.

**Comment by xiNeRoar** [comment]
@hrfee Thank you for your instruction, but i think this function is somehow broken right now.
```Hi demo,

Someone has recently requested a password reset on Jellyfin.

If this was you, click the link below.

The code will expire on 29/05/21, at 17:41 UTC, which is in 30m.

If this wasn't you, please ignore this.

PIN: http://accounts.jellyf.in:8056/reset?pin=39-83-76-A6

Need help? contact me.
```
As above message described, i expect the password will reset only if i clicked on the link. But i found out even if i did not click on the link. My password will still reset to the PIN, which means anyone have my account name can abuse this function and mess up my password at anytime?

**Comment by hrfee** [comment]
I'm guessing your email provider automatically opens the link to generate a preview, that might be what triggers the reset. This is definitely something I need to fix, but it shouldn't be a risk. Can you try sending it to a different email account to see if it gets auto reset again?

**Comment by xiNeRoar** [comment]
@hrfee i am not sending the message through email. I am sending it through telegram. Another wired thing is that whenever i click in the link, it will show below screen;
![image](https://user-images.githubusercontent.com/66216186/120079575-0e032e80-c0e7-11eb-8cf6-66e61e4becc7.png)
But in fact the password is successfully reset.

**Comment by xiNeRoar** [comment]
@hrfee Is this what you describe? about preview?
![image](https://user-images.githubusercontent.com/66216186/120079628-57537e00-c0e7-11eb-98d1-168fedae0156.png)

**Comment by hrfee** [comment]
Ah, telegram is opening the link, which resets the password and invalidates the PIN, therefore showing you that message when you visit it for the second time. This should be easy to fix, maybe checking the User Agent of the visitor to check it isn't a bot.

**Comment by xiNeRoar** [comment]
"maybe checking the User Agent of the visitor to check it isn't a bot." Is this something that i can do with?

**Comment by hrfee** [comment]
No, I'll implement a fix after dinner, will be up within an hour.

**Comment by xiNeRoar** [comment]
thank you so much, really appreciate your great work :P

**Comment by hrfee** [comment]
Fixed in 953a66e, Update in around ~15 minutes and see if there's still a problem.

**Comment by xiNeRoar** [comment]
@hrfee I stopped my docker image and re-pull the "unstable" tag, however the problem still exist.
![image](https://user-images.githubusercontent.com/66216186/120087043-3acf3a00-c117-11eb-8340-01bcd9e36a10.png)

**Comment by hrfee** [comment]
Could you run `docker logs jfa-go | grep "jfa-go version"` and send the output?

**Comment by xiNeRoar** [comment]
yes sure. but may i know where should i type in this command? i am using docker application in Synology NAS

**Comment by hrfee** [comment]
Ah, didn't realise. Could you go to Settings > About and send the value next to "Commit" instead?

**Comment by xiNeRoar** [comment]
Here it is;
![image](https://user-images.githubusercontent.com/66216186/120087361-bb8f3580-c119-11eb-8b78-f499b2cfad7e.png)

**Comment by hrfee** [comment]
Ok thats the right version. Do you know how to access the logs of the jfa-go docker container on the NAS? If so, could you repeat the password reset, then look for any lines beginning with `[ERROR]` and send them? Make sure to remove any sensitive information.

**Comment by xiNeRoar** [comment]
Not really but i would love to give it a try :P.
Do i need to enable this option in order to have the logs?
![image](https://user-images.githubusercontent.com/66216186/120087476-f6459d80-c11a-11eb-9e31-02ce7349637a.png)

**Comment by hrfee** [comment]
Yeah, forgot to mention but that’d be helpful.

**Comment by xiNeRoar** [comment]
After i enable the option and test it again, suddenly things works lol...
![image](https://user-images.githubusercontent.com/66216186/120087559-8b489680-c11b-11eb-9453-a446b4799589.png)
i gonna test it again several times to make sure it is not an incident

**Comment by xiNeRoar** [comment]
> After i enable the option and test it again, suddenly things works lol...
> ![image](https://user-images.githubusercontent.com/66216186/120087559-8b489680-c11b-11eb-9453-a446b4799589.png)
> i gonna test it again several times to make sure it is not an incident

It does work right now, after i enable the debug option. But it will send the reset password message twice to my telegram.
I will turn off the debug option and test it again.

**Comment by xiNeRoar** [comment]
Okay...After i enable the debug loggin function and disable it again. Everything work perfectly right now.
No more "Password reset failed". I have no idea why and...i cant found the log to paste it here.
Anyway, thank you very much for you help on this issue. :P

**Comment by hrfee** [comment]
Closing now, feel free to re-open or create a new issue if there's any more problems,
