### ISSUE TITLE
apt-get can't find jfa-go package on Raspbian

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [hrfee/jfa-go#109]
Hi,

I was previously using jfa-go directly on the pi, registered as a service. As I saw that now it is available on a repo, I wanted to try it. But it doesn't look like it can find the package to download it.

I've executed successfully all the the commands below:

sudo apt-get update && sudo apt-get install curl apt-transport-https gnupg
curl https://apt.hrfee.dev/hrfee.pubkey.gpg | sudo apt-key add -
echo "deb https://apt.hrfee.dev trusty main" | sudo tee /etc/apt/sources.list.d/hrfee.list
sudo apt-get update
sudo apt-get install jfa-go

But at the end, I have an error "Package jfa-go can't be found"

Is the repo working correctly ? Is the issue on my end or not ?
Any help or answer is welcome, have a good day.

**Comment by hrfee** [comment]
The stable apt repo only has a build for x86_64 right now, which was added manually when I set it up for testing. The unstable one has ARM, you can switch to it by running
```sh
sudo sed -i 's/trusty/trusty-unstable/g' /etc/apt/sources.list.d/hrfee.list
```
After that, apt-get update and you should be able to install it.

**Comment by hrfee** [comment]
Ended up uploading v0.3.6 for arm, so if you haven't switched to unstable already you should be able to `sudo apt update && sudo apt install jfa-go` now.
