### ISSUE TITLE
Ombi don't remove user 

### ISSUE THREAD

**Issue by Killianbe** [hrfee/jfa-go#11]
Hi
Ombi don't remove user when i delete him with your app. Email not appear to i need to write manually 
thx :)

**Comment by hrfee** [comment]
Fixed user deletion in a89dc40ff2e769359e05206a99ba25a359141be2, which should hopefully be on the unstable docker soon (build is taking a while for some reason). As for the email address, it appears to work for me. Could you try again with the new version?

**Comment by Killianbe** [comment]
i've update all my html, now when i create user via form.html i havn't username, only mail + password. And when i press ok, email is username for ombi and jellyfin. i've update docker too.

**Comment by hrfee** [comment]
Check settings > Email > Use email addresses as username. If you want username and email, make sure its disabled.

**Comment by hrfee** [comment]
If it's already disabled, make sure this is in your `form.html`:
```
{{ if .settings.username }}
    <div class="form-group">
        <label for="inputUsername">Username</label>
        <input type="username" class="form-control" id="inputUsername" name="username" placeholder="Username" required>
    </div>
{{ end }}
```
It should appear just above these lines:
```
<div class="form-group">
    <label for="inputPassword">Password</label>
```

**Comment by Killianbe** [comment]
it's that html problem. But now when i enter email, it didn't rewrite on ombi and on jfago

**Comment by hrfee** [comment]
You mean when you enter the email address in the accounts tab, it doesn't change? It won't change the ombi email address, I'll add that later.

**Comment by Killianbe** [comment]
![1](https://user-images.githubusercontent.com/16178815/97678204-bee31580-1a93-11eb-97a7-6bab6a3de73d.PNG)
![2](https://user-images.githubusercontent.com/16178815/97678207-bf7bac00-1a93-11eb-9f05-ab748b5e2591.PNG)
![3](https://user-images.githubusercontent.com/16178815/97678208-c0144280-1a93-11eb-81ec-c768ff991455.PNG)
![4](https://user-images.githubusercontent.com/16178815/97678210-c0144280-1a93-11eb-95ba-13d1de414bc7.PNG)
 if that can help u

**Comment by Killianbe** [comment]
User not create on jfa account, is created on ombi and jellyfin, but ombi take username with email and not enter mail. and it's ok on jellyfin

**Comment by hrfee** [comment]
Does the email address of the new user appear in the accounts tab?

**Comment by Killianbe** [comment]
I think I'll remove everything, and make a clean docker again. and I will retrieve the correct mail template that I would have just modified

**Comment by Killianbe** [comment]
ok i have redone everything, the ombi integration works entirely. But I still have no mail in the jfago application like in picture 4.

**Comment by Killianbe** [comment]
and a question? if I don't modify the admin page, do I have to copy it to my custom directory or it will load automatically in the basic version

**Comment by hrfee** [comment]
Ok so the email address is stored on ombi but not on jfa-go, right? If yes, could you check if the email addresses are present in `/config/emails.json`?

**Comment by hrfee** [comment]
> and a question? if I don't modify the admin page, do I have to copy it to my custom directory or it will load automatically in the basic version

You don't need to copy it if you don't want to make any changes, it will load the internal version automatically.

**Comment by Killianbe** [comment]
> 
> 
> Ok so the email address is stored on ombi but not on jfa-go, right? If yes, could you check if the email addresses are present in `/config/emails.json`?

Only 2 email here, ,not other.. i'll try to delete file

**Comment by hrfee** [comment]
Ok, just so i understand fully: When you create an account in jfa-go, the email is applied to Ombi, but doesn't appear in jfa-go itself?

**Comment by Killianbe** [comment]
exactly ^^ sorry i've bad english

**Comment by hrfee** [comment]
When you manually add an email address in the accounts tab, is it stored correctly in `emails.json`?

**Comment by Killianbe** [comment]
I close. i've delete all for restart to good base. i'll go try your lang.json thx foir support
