### ISSUE TITLE
Invalid link for password resets

### ISSUE THREAD

**Issue by LeviSnoot** [hrfee/jfa-go#111]
**Describe the bug**

When jfa-go sends a password reset email, it links to the incorrect url. My url base for jfa-go is `https://invites.example.com/invite`. When it sends a password reset link, the link URL ends up being `http://s.example.com/invite/reset?pin=XX-XX-XX-XX`

**To Reproduce**

What to do to reproduce the problem.

Either generate a password reset email, or preview the password reset email in jfa-go under "Settings -> Messages/Notifications".

**Platform/Version**

Windows 10 Pro
jfa-go Version 0.3.6

**Comment by hrfee** [comment]
`https://invites.example.com/invite` is set in Settings > Invite emails > URL Base right? There's a URL Base in Settings > General for the web UI, and another one used by both Invite emails and Password reset links in Settings > Invite Emails.

**Comment by LeviSnoot** [comment]
Probably should have mentioned originally that I'm using Caddy to reverse proxy the program so when I change the value in General settings jfa-go doesn't know what to do and goes blank.

**Comment by hrfee** [comment]
You can leave that alone then. Also, to be clear, do you access jfa-go through `https://invites.example.com`, or `https://invites.example.com/invite`?

**Comment by LeviSnoot** [comment]
I access it through `https://invites.example.com`, I set the base URL as `https://invites.example.com/invite` but I can't exactly remember why. When I set the base URL as `https://invites.example.com` the resulting URL is `https:/s.levi.land/reset?pin=12-34-56`

**Comment by hrfee** [comment]
The extra `/invite` is necessary for the Invite Emails URL Base (i think?), not for the General one. `https:/s.levi.land/reset?pin=12-34-56` looks right to me, the `/invite` should be stripped (I know, its a mess).

**Comment by LeviSnoot** [comment]
Yeah that makes sense. It's fine though, the problem I'm having is just the initial syntax for the URL. (`https:/s.` instead of `https://invites.`).

**Comment by hrfee** [comment]
Ah, since it tries to remove `/invite`  it ends up taking it off the beginning of the URL instead of the end. I've switched the `Replace` to `TrimPrefix` so this doesn't happen in 561c461, you'll be able to download a nightly build [here](https://builds.hrfee.pw/view/hrfee/jfa-go) in about 15 minutes.

**Comment by LeviSnoot** [comment]
Thanks so much!

**Comment by mLgz0rn** [comment]
Hey I know this is closed, but I have a similar issue, it was working fine before this fix.
I'm having an issue where the /invite part is not being removed.

So instead of being https://invite.example.com/reset?pin=12-34-56-78
It's  https://invite.example.com/invite/reset?pin=12-34-56-78

**Comment by hrfee** [comment]
@mLgz0rn sorry I thought i fixed my fix already, i  put TrimPrefix instead of TrimSuffix. Fixed in d4096d0, give it like 10 minutes and you'll be able to download from builds.hrfee.pw or docker unstable.

**Comment by mLgz0rn** [comment]
> @mLgz0rn sorry I thought i fixed my fix already, i put TrimPrefix instead of TrimSuffix. Fixed in [d4096d0](https://github.com/hrfee/jfa-go/commit/d4096d00621ac0c250248c0f81f5e3e26cfa549c), give it like 10 minutes and you'll be able to download from builds.hrfee.pw or docker unstable.

Thanks you so much for the fast response!

**Comment by mLgz0rn** [comment]
@hrfee For some reason my docker container does not seem to want to update to the latest commit on unstable.
Even if I delete the container or force it to pull the latest unstable I still end up on Commit 21b373a

**Comment by mLgz0rn** [comment]
It's working now! thank you

**Comment by hrfee** [comment]
@mLgz0rn I realised from another issue that my docker builds were broken, forgot to tell you as well but good its working now.
