### ISSUE TITLE
Try again within your home network

### ISSUE THREAD

**Issue by ClankJake** [hrfee/jfa-go#114]
#### Read the [FAQ] (https://github.com/hrfee/jfa-go/wiki/FAQ) first!

 ![](https://user-images.githubusercontent.com/8566394/80172222-6d287280-85ba-11ea-94ac-a97c7966bbfb.png)

#### ** Describe the bug **
It's not a bug in itself in jfa-go itself a problem in Jellyfin to reset the password I'm getting this message I've done the procedure in the FAQ but without success.

I'm running on an instance in Docker-composer + nginx (outside the docker) + CloudFlare

**Comment by hrfee** [comment]
The example doesn't work for me either, actually. The `$host` variable in nginx is the IP of the client, which obviously doesn't make sense. I must have changed it at some point, let me figure out the proper config.

**Comment by hrfee** [comment]
This seems to work for me:
```nginx
    location /Users/ForgotPassword {
        proxy_pass http://<jellyfin address>/Users/ForgotPassword;
        proxy_set_header X-Forwarded-For <any local ip address>;
    }

    location /Users/ForgotPassword/Pin {
        proxy_pass http://<jellyfin address>/Users/ForgotPassword/Pin;
        proxy_set_header X-Forwarded-For <any local ip address>;
    }
```

**Comment by ClankJake** [comment]
good it worked here

**Comment by hrfee** [comment]
Great, i'll update the wiki.
