### ISSUE TITLE
I am having this same setup issue but on Debian. Not sure where to look for the file/directory that resolved his issue.

### ISSUE THREAD

**Issue by WhiteTrashWeeb** [hrfee/jfa-go#115]
Hello. I am having the same issue as this person, but on Debian instead of windows. He was able to resolve the issue by deleting a directory and configuring it manually. Thing is, I don't know how to do that on Debian and his problem was on Windows. Anyone know how to point me in the right direction?

https://github.com/hrfee/jfa-go/issues/16

**Comment by hrfee** [comment]
Should be `~/.config/jfa-go`.

**Comment by WhiteTrashWeeb** [comment]
Yes that's correct. Whether I use the internal, external or domain, it cannot connect to Jellyfin.

**Comment by hrfee** [comment]
Could you send the log output of jfa-go when you start it?
