### ISSUE TITLE
cant refresh

### ISSUE THREAD

**Issue by mickeyt89** [hrfee/jfa-go#116]
once completed setup via web ui i click refresh then it doesnt let me access the web ui again to login

**Comment by hrfee** [comment]
What OS are you running jfa-go on, and are you using Docker?

**Comment by TheMrRoboto** [comment]
I am having this same issue, on Debian no docker

**Comment by hrfee** [comment]
Could you update to the version I just published (v0.3.7) and try again? If it crashes, could you send the output?

**Comment by xarmadigi** [comment]
I have the sane issue on ubuntu 18.04 tls server. I am triying connect to emby
