### ISSUE TITLE
Can't seem to run jfa-go under a certain user

### ISSUE THREAD

**Issue by DJSigmann** [hrfee/jfa-go#118]
I can start jfa-go just fine when I run it under root or another user account, but when I use the same system user that I use for Jellyfin I get the following error message:
https://gist.github.com/DJSigmann/5eb128693903c4f551924ab09cc1606d

I'm running this on Debian Buster btw.

Any help in resolving this would be appreciated.

**Comment by hrfee** [comment]
The configuration is separate per-user, and it looks like the configuration on the broken user is incomplete or broken. You can copy `/home/<working username>/.config/jfa-go` to `/home/<broken username>/.config/jfa-go` to copy the config and user storage over.

**Comment by DJSigmann** [comment]
> 
> The configuration is separate per-user, and it looks like the configuration on the broken user is incomplete or broken. You can copy `/home/<working username>/.config/jfa-go` to `/home/<broken username>/.config/jfa-go` to copy the config and user storage over.

My bad, I should have mentioned I ran jfa-go like this:
`jfa-go -c /etc/jfa-go/config.ini -d /var/lib/jellyfin/jfa-go`

I did make sure that the user had sufficient permissions for both the folder and the config file and the error persisted.
I also tried copying a working config file to the home directory of the broken user (I changed the perms) and ran jfa-go without any options, but the error is still present.

However, I have tried running jfa-go with a few other system users and they also give the same errors, perhaps jfa-go just doesn't play nicely with system users?

**Comment by hrfee** [comment]
Ah, ok. I just noticed on line 7 of your log it says
```
2021/06/12 18:22:21 Failed to authenticate with Jellyfin @ : Timed out
```
There should be a server address just after `@`, e.g.
```
2021/06/13 15:14:52 Failed to authenticate with Jellyfin @ jellyfin-url: Timed out
```
Any error in reading the config file should be reported, so i'm not really sure at this point. Could you start over with no config or data and go through the setup process again, running as the broken user?

If that doesn't work, could you maybe try running an unstable release?

**Comment by DJSigmann** [comment]
> 
> 
> Ah, ok. I just noticed on line 7 of your log it says
> 
> ```
> 2021/06/12 18:22:21 Failed to authenticate with Jellyfin @ : Timed out
> ```
> 
> There should be a server address just after `@`, e.g.
> 
> ```
> 2021/06/13 15:14:52 Failed to authenticate with Jellyfin @ jellyfin-url: Timed out
> ```
> 
> Any error in reading the config file should be reported, so i'm not really sure at this point. Could you start over with no config or data and go through the setup process again, running as the broken user?
> 
> If that doesn't work, could you maybe try running an unstable release?

Huh, setting the broken user's UID to a value above 1000 AND removing my config.ini file worked, sorry for the late reply, and thanks for all the help.
