### ISSUE TITLE
Feature Request: Announce User Custom Email File

### ISSUE THREAD

**Issue by Facinorous-420** [hrfee/jfa-go#126]
![AnnounceUser](https://bss.nz/i/07-06-2021-Ceqn8aF9wH.png)

As far as I can find, I can not set a cusstom email template for these messages I send users. Would this be possible to be added?

**Comment by hrfee** [comment]
I'll add an option to save an announcement as a template, and stick a dropdown next to the announce button to select them. I'm a bit busy this week but it should be done by the weekend.

**Comment by hrfee** [comment]
Added in 3e55cd1. There's now an extra button to save as a template in the announce modal, and when you hover over the "Announce" button on the accounts page a list of templates will appear for you to select.

**Comment by Facinorous-420** [comment]
> Added in [3e55cd1](https://github.com/hrfee/jfa-go/commit/3e55cd1e31fd27c6b4cd8f9c97430de6a4623cfc). There's now an extra button to save as a template in the announce modal, and when you hover over the "Announce" button on the accounts page a list of templates will appear for you to select.

Quite an amazing feature! I did not think about this, but I'm glad you did because I can see how this can come in handy for reusing a lot of the same announcements you may send out a lot! Nice!

I'm sorry for not clarifying better, but I meant the html template that the email uses when displaying the announcement. With every other email we send, we can select both which plaintext and html template file it uses when sending the email. The only one that does not have this, is the announcements; and because of this the emails are the default black background emails. (Granted though for a default email, it's nice)

https://bss.nz/i/07-14-2021-9bNbEj4jhC.png

**Comment by hrfee** [comment]
Sorry, this setting was available but hidden from the UI and undocumented. Added in 4d3acb2, you can find it by enabling advanced settings and checking the "Custom email template" section.

**Comment by Facinorous-420** [comment]
> Sorry, this setting was available but hidden from the UI and undocumented. Added in [4d3acb2](https://github.com/hrfee/jfa-go/commit/4d3acb2c4c17f66da0d0e622ce2ad1a7dc9499f0), you can find it by enabling advanced settings and checking the "Custom email template" section.

Amazing! Thanks so much for this!
I'm going to close this now since this has been added (plus more, with that sexy announcement template). 

You're the best!

**Comment by Facinorous-420** [comment]
I am reopening this issue, as I have found an issue relating to the announcement emails.

I am unsure why, but when you first applied the template announcements, I had tested it and it worked.
Now after updating to the newest version to be able to set the custom html template, when I go to accounts and select one then try to click "Announce" nothing happens.

**Comment by hrfee** [comment]
Could you send your logs when you click Announce and nothing pops up?

**Comment by Facinorous-420** [comment]
https://bss.nz/i/07-15-2021-qN3XPwweae.png

Here are my docker logs for the container.

I can send you a gif as well, but it will have my users emails in it so I'd rather send it over a private medium. If you want that, you can add me on Discord @ Newguy#7481

**Comment by Facinorous-420** [comment]
https://bss.nz/i/07-15-2021-cLehBw9nd8.png

I have found errors in the browsers console as well. Maybe this can help figure out the source of the issue.

I noticed if I leave the tab open with doing nothing for a long period of time, and come back and click the button- the pop up shows it self. Though, when I close it and try to reopen it; the problem happens again where it does not open.

Will continue to play around with it and report anything I notice.

**Comment by Facinorous-420** [comment]
Okay after playing around with it more, I have more information to report:

Above I mention every so often the pop up appears again, until I refresh the page. I have taken a closer look when this happens and I figured out it only shows when I am unauthorized (I assume jfa-go expires the auth cookie every so often if you leave the page open). When you refresh the page, and thus renew the cookie authorizing yourself again, the pop up no longer works again. 

Since you are not authorized when the pop up appears, you can not send the email nor save it as an actual template. 

I hope all this information can get us closer to the origin of the problem <3 let me know if you need anymore info.

**Comment by hrfee** [comment]
Sorry for the late reply, since the browser loads in the announce email html file, it's likely something to do with your custom one. Can you first make sure your template includes `{{ .text }}`? This is replaced with `<div class="preview-content"></div>` when the preview window is loaded, and that HTML tag is then searched for and stored in `this._announcePreview`, and the error in your JS console means the tag couldn't be found.

**Comment by Facinorous-420** [comment]
> Sorry for the late reply, since the browser loads in the announce email html file, it's likely something to do with your custom one. Can you first make sure your template includes `{{ .text }}`? This is replaced with `<div class="preview-content"></div>` when the preview window is loaded, and that HTML tag is then searched for and stored in `this._announcePreview`, and the error in your JS console means the tag couldn't be found.

No worries.

Ahh that would be it! I guess I over looked the message in the settings page that mentioned to add that. Could have sworn I did though :p turns out I only added the message variable and didn't add the subject.

Is there any other variables I can use here other than these two? For example, I tried  {{ .username }} and nothing happened so I assume there's a list of variables that can be used for each email type? Is this documented?

Other than this, thank you so much for helping em figure this out. Bless you <3

I will close this issue since this issue is resolved and feature added. Once sgain, thanks again for everything.

**Comment by hrfee** [comment]
`{{ .username }}` was one i meant to add for announcements but I never got round to it, i'll look into that now. Other than that the only ones available are those used in the email files. You can just do a grep for `{{` to find them.

**Comment by hrfee** [comment]
`{username}` added for the in app editor in b10b558, and `{{ .username }}` added for use in the raw HTML file in 25a8d38.

**Comment by Facinorous-420** [comment]
> `{username}` added for the in app editor in [b10b558](https://github.com/hrfee/jfa-go/commit/b10b5583581e6414d242e1c098c8c79bce7370c9), and `{{ .username }}` added for use in the raw HTML file in [25a8d38](https://github.com/hrfee/jfa-go/commit/25a8d3807e8846638d7166362f195797dfe1bef9).

I added {{ .username }} to my template and it works! Except there are extra []s around the username. See this screenshot for example:

https://bss.nz/i/07-16-2021-q8uud2oJj8.png

**Comment by hrfee** [comment]
The 2nd {username} in your email doesn’t have the []s, are you sure you didn’t just make a typo in your html and add them for the bigger one?

**Comment by Facinorous-420** [comment]
Yup I'm certain. 

Here is a snippet of code from my template for the larger text:

```
<tr>
																						<td class="h1 pb15"
																							style="color:#ffffff; font-family:'Muli', Arial,sans-serif; font-size:32px; font-weight: bold; line-height:36px; text-align:center; padding-bottom:15px;">
																							Hello, {{ .username }}
																						</td>
																					</tr>
```

Here is a snippet of the smaller text:

```
<tr>
															<td class="text pb20"
																style="color:#ffffff; font-family:Arial,sans-serif; font-size:14px; line-height:26px; text-align:left; padding-bottom:20px;">
																{{ .text }} <br /> <br />
																{{ .message }}</td>
														</tr>
```

**Comment by hrfee** [comment]
Ah, the username for `{{ .username }}` was given as an array instead of as a string, should be fixed in the latest.

>
