### ISSUE TITLE
Can click though install without verifying server connection

### ISSUE THREAD

**Issue by awb1015** [hrfee/jfa-go#129]
I think a few of the issues with jfa-go crashing without properly starting may stem from this.

I noticed that during set-up when I enter the local IP for my server and click check (or test, I can't remember the name on the button) I'm able to click next even if jfa-go doesn't return a "Success". This means that it's possible to complete the set-up wizard with an invalid set-up. Even if the next button is grayed out, it still works.

I had several tries at the correct format for my internal IP before I got a "success". When I continued with set-up in absence of a "Success" I had a lot of the odd issues described where running with a daemon with `jfa-go start` would produce crash logs but not a lot of valuable information

I fixed the issue by deleting my `config.ini` and re-running the set-up process until I was able to return a success when testing the server connection.

Not sure if it matters but I'm running Ubuntu and jfa-go on baremetal. Just have it for internal use at the moment, no reverse proxy. jfa-go is on the same machine that runs Jellyfin. Apologies if this isn't a distinct issue on its own but wanted to share the info

**Comment by hrfee** [comment]
I’ve noticed this myself and ignored it, but I think you’re right in that it could cut down on some issues (and bug reports for my benefit 😆). I’ll see if more information can be provided when “Test Connection” fails as well to help with proper issues.

**Comment by hrfee** [comment]
Also, do you know what specifically fixed your issue? As in was it the format of the address or just a typing mistake?

**Comment by awb1015** [comment]
I'm not entirely sure what cured it to be honest. I felt like for internal address I tried a lot of potential options including..

localhost:8056
192.168.0.XX:8056
127.0.0.1:8056
http://localhost:8056
http://192.168.0.XX:8056
http://127.0.0.1:8056

I think I had to remove a trailing slash and the leading `http://` I can't remember what I finally had success with, the field in settings now says `http://192.168.0.XX:8096` but I can't remember if I included the leading `http://` or if jfa-go prepended it to the string.

It did seem like restarting jfa-go was beneficial as (rightly or wrongly) it felt like it wasn't actually trying the new internal addresses I provided. When I finally returned a "Success" I hit next without really thinking.

**Comment by hrfee** [comment]
A new jellyfin client is created every time you press “Test Connection”, so the new addresses should be used. The http client in Go does require the `http://` I think, iirc a recent commit made this be added automatically but I don’t think it’s done on the setup process. I’ll check tomorrow morning.
