### ISSUE TITLE
Can not create  systemd .service file

### ISSUE THREAD

**Issue by lauw0129** [hrfee/jfa-go#130]
I installed jfa-go in Ubuntu server 20.04 LTS. And when I type `jfa-go systemd` It's output is the following.

```
2021/07/27 17:33:53 Logging to "/tmp/jfa-go.log"
2021/07/27 17:33:53 Using internal storage
jfa-go version: 0.3.7 (a0af763)

Socket: /tmp/jfa-go.sock
```

And /tmp/jfa-go.log this file is not exist. Please help

**Comment by hrfee** [comment]
The command seems to be broken in 0.3.7, you could switch to the unstable version where this works, or just create the file (jfa-go.service) yourself, it looks like this:
```
[Unit]
Description=An account management system for Jellyfin.

[Service]
ExecStart=<path jfa-go (you can figure this out by running `which jfa-go`)>

[Install]
WantedBy=default.target
```
You can then put that in `~/.config/systemd/user/`, run `systemctl --user daemon-reload`, and start/stop/restart with `systemctl --user start/stop/restart jfa-go`.

**Comment by lauw0129** [comment]
Thank you so much!

**Comment by TorresSantos** [comment]
Hello friend, even doing this my jfa-go only works if the ssh access via putty is open after closing the putty software the jfa-go does not work anymore. Would you know why?

> O comando parece estar quebrado em 0.3.7, você pode mudar para a versão instável onde isso funciona, ou apenas criar o arquivo (jfa-go.service) você mesmo, fica assim:
> 
> ```
> [Unit]
> Description=An account management system for Jellyfin.
> 
> [Service]
> ExecStart=<path jfa-go (you can figure this out by running `which jfa-go`)>
> 
> [Install]
> WantedBy=default.target
> ```
> 
> Você pode então colocar isso em `~/.config/systemd/user/`, executar `systemctl --user daemon-reload`e iniciar/parar/reiniciar com `systemctl --user start/stop/restart jfa-go`.



> The command seems to be broken in 0.3.7, you could switch to the unstable version where this works, or just create the file (jfa-go.service) yourself, it looks like this:
> 
> ```
> [Unit]
> Description=An account management system for Jellyfin.
> 
> [Service]
> ExecStart=<path jfa-go (you can figure this out by running `which jfa-go`)>
> 
> [Install]
> WantedBy=default.target
> ```
> 
> You can then put that in `~/.config/systemd/user/`, run `systemctl --user daemon-reload`, and start/stop/restart with `systemctl --user start/stop/restart jfa-go`.

Hello friend, even doing this my jfa-go only works if the ssh access via putty is open after closing the putty software the jfa-go does not work anymore. Would you know why?
