### ISSUE TITLE
Confusing location for external URL

### ISSUE THREAD

**Issue by robocrax** [hrfee/jfa-go#131]
You probably have considered this or are probably thinking of working on this but here's my tiny unimportant problem:

**Configuration**

I have emails (and all related email settings) disabled because solely working with Telegram/any chatbot is a breeze and also FREE99.

**What I'm trying to do**

I'm trying to send password reset links instead of just the key because it's less confusing and easy for any end user.

**Setting that is confusing**

The link provided via Telegram contains the generic sample external URL ```accounts.jellyf.in:8056/invite``` which is in another option `Invite emails` which is literally the next option after `Password Resets` but in my case it's actually hidden because that option is disabled. 

Is it possible to hint under `Password Resets` that this setting is available here?

Or ultimately move the option to a better place, like maybe `General` or whichever you think is best.

**Platform/Version**

Using Docker on Windows using Hyper-V and default docker compose config behind reverse proxy.

**Comment by robocrax** [comment]
Actually come to realize that those 2 links are different, or maybe I'm wrong and the placeholder text confused me.

> Hi <user>,
>
> Someone has recently requested a password reset on Jellyfin.
>
> If this was you, click the link below.
>
> The code will expire on 27/07/21, at 10:20 UTC, which is in 30m.
>
> If this wasn't you, please ignore this.
>
> PIN: http://accounts.jellyf.in:8056/invite/reset?pin=2C-B3-B7-12
>
> Need help? Contact me

The `/invite` in the URL shouldn't even be there, it should just be the host and the the `/reset?` part so I'm guessing a new option will have to created for this is this is the case.

**Comment by hrfee** [comment]
You're right, the link under "Invite Emails" if used for password resets too. The `/invite` is trimmed in unstable builds after 0.3.7, but I've been meaning to add a separate setting for password resets anyway.

**Comment by hrfee** [comment]
Added a redundant setting under Password resets in 9693ce3, if you have the one under Invite emails set it won't show up in there but will still be used.

**Comment by hrfee** [comment]
ultra-necrobump but settings were merged into General  > Extenral jfa-go URL in e71d4924.
