### ISSUE TITLE
NEW FEATURES : Verification password

### ISSUE THREAD

**Issue by Killianbe** [hrfee/jfa-go#14]
Hi, 
here is an idea to embellish jfa-go, add a written password verification. Too many users are wrong, so if checking the match no more problem
:) 
have a nice day

**Comment by hrfee** [comment]
not sure why i hadn't done this earlier, i'll get on it now

**Comment by hrfee** [comment]
Could you translate "Passwords are not identical" into french for me? thanks.

**Comment by hrfee** [comment]
Oh and also "Reenter password".

**Comment by hrfee** [comment]
just added it in ba60193 with the translations "Confirmez mot de passe" and "Les mots de passe ne correspondent pas". My french is high school level so are they alright?

**Comment by Killianbe** [comment]
Perfect !
