### ISSUE TITLE
cant create systemd

### ISSUE THREAD

**Issue by Marios1231** [hrfee/jfa-go#149]
I run ubuntu 21.04 server and whenever I try to use the command jfa-go systemd i get 2021/09/15 05:17:50 Using internal storage

**Comment by Marios1231** [comment]
if anyone else has this issue just use this 

[Unit]                                                                                                                                                                                                             Description=An account management system for Jellyfin.                                                                                                                                                                                                                                                                                                                                                                                [Service]                                                                                                                                                                                                          User=root                                                                                                                                                                                                          ExecStart=/usr/local/bin/jfa-go                                                                                                                                                                                    Restart=on-failure                                                                                                                                                                                                 RestartSec=5                                                                                                                                                                                                       [Install]                                                                                                                                                                                                          WantedBy=default.target

**Comment by hrfee** [comment]
Which version are you running that has this issue? I think it should be fixed in more recent versions.

**Comment by Marios1231** [comment]
0.3.8

**Comment by hrfee** [comment]
Sorry yeah, this was fixed after 0.3.8. I meant to re-release it as it had a lot of bugs but as it looks like there's more to do i'll work on other issues and then release 0.3.9. For now it works in unstable builds.

**Comment by Marios1231** [comment]
alright, thank you very much
