### ISSUE TITLE
Unable to send email

### ISSUE THREAD

**Issue by mairajha** [hrfee/jfa-go#15]
Updated to jfa-go, but unfortunately I am still unable to send email below is the error which I got while I pressed send invitation button. Checked it with two different email providers but got same error.
![jfa-go](https://user-images.githubusercontent.com/52917522/99118189-e2bc6480-2618-11eb-874a-c4da14314c64.jpg)

[ERROR] 01:23:36 api.go:517: vDb5eBFUrqH29HtbDzWRyN: Failed to send to syedmairaj@hotmail.com
[GIN] POST(/invites) => 200
[GIN] GET(/invites) => 200
[GIN] GET(/users) => 200
[INFO] 01:24:03 Config requested
[GIN] GET(/config) => 200
[GIN] GET(/invites) => 200
[INFO] 01:24:36 Config modification requested
[GIN] POST(/config) => 200
[INFO] 01:24:42 Config modification requested
[GIN] POST(/config) => 200
[ERROR] 01:24:53 api.go:517: LAqE4ipG9i4NRYBnjeHruc: Failed to send to syedmairaj@hotmail.com
[GIN] POST(/invites) => 200
[GIN] GET(/invites) => 200
[GIN] GET(/invites) => 200
[ERROR] 01:25:23 api.go:517: gSX8d84MF3Beb3vYgSBfRm: Failed to send to syedmairaj@hotmail.com
[GIN] POST(/invites) => 200
[GIN] GET(/invites) => 200
[GIN] GET(/invites) => 200
[GIN] GET(/invites) => 200
[GIN] GET(/invites) => 200

**Comment by hrfee** [comment]
Could you enable debug logging in settings > general and try again? It
should print an actual error message.

**Comment by mairajha** [comment]
after enable that it says invite sent on console, but on GUI it says failed to send to 

![image](https://user-images.githubusercontent.com/52917522/99147038-396c8180-269f-11eb-9154-5e9ff61e05ec.png)


[INFO] 17:27:50 Starting router @ 0.0.0.0:8056
[GIN/DEBUG] 17:27:55: GET(/) => 200 in 4.8836ms;
[DEBUG] 17:27:55 auth.go:185: Token requested (refresh token)
[DEBUG] 17:27:55 auth.go:188: getTokenRefresh denied: Couldn't get token: http: named cookie not present
[GIN/DEBUG] 17:27:55: GET(/token/refresh) => 400 in 1.9534ms;
[GIN/DEBUG] 17:27:55: GET(/favicon-32x32.png) => 200 in 112.2969ms;
[INFO] 17:28:02 Token requested (login attempt)
[DEBUG] 17:28:03 auth.go:165: Token generated for user "mina"
[GIN/DEBUG] 17:28:03: GET(/token/login) => 200 in 623.9817ms;
[DEBUG] 17:28:03 auth.go:89: Auth succeeded
[DEBUG] 17:28:03 api.go:678: Invites requested
[GIN/DEBUG] 17:28:03: GET(/invites) => 200 in 1.9535ms;
[DEBUG] 17:28:16 auth.go:89: Auth succeeded
[DEBUG] 17:28:16 api.go:482: Generating new invite
[DEBUG] 17:28:16 api.go:508: kmREJW795h63WwcfaDpBR6: Sending invite email
[DEBUG] 17:28:50 daemon.go:37: Daemon: Checking invites
[DEBUG] 17:29:03 auth.go:89: Auth succeeded
[DEBUG] 17:29:03 api.go:678: Invites requested
[GIN/DEBUG] 17:29:03: GET(/invites) => 200 in 2.9358ms;
[ERROR] 17:29:17 api.go:517: kmREJW795h63WwcfaDpBR6: Failed to send to syedmairaj@hotmail.com
[DEBUG] 17:29:17 api.go:518: kmREJW795h63WwcfaDpBR6: Error: EOF
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 400 with 200
[GIN/DEBUG] 17:29:17: POST(/invites) => 200 in 1m0.5977414s;
[DEBUG] 17:29:17 auth.go:89: Auth succeeded
[DEBUG] 17:29:17 api.go:678: Invites requested
[GIN/DEBUG] 17:29:17: GET(/invites) => 200 in 1.9914ms;
[DEBUG] 17:29:50 daemon.go:37: Daemon: Checking invites
[DEBUG] 17:30:03 auth.go:89: Auth succeeded
[DEBUG] 17:30:03 api.go:678: Invites requested
[GIN/DEBUG] 17:30:03: GET(/invites) => 200 in 977.7µs;
[DEBUG] 17:30:50 daemon.go:37: Daemon: Checking invites
[DEBUG] 17:31:03 auth.go:89: Auth succeeded
[DEBUG] 17:31:03 api.go:678: Invites requested
[GIN/DEBUG] 17:31:03: GET(/invites) => 200 in 995.8µs;

**Comment by hrfee** [comment]
After some googling, I think the error is still with the port you're using. Could you try switching smtp port 465 to 587 (or the other way round)?

**Comment by mairajha** [comment]
after changing port to 587 gives me below mentioned error


[GIN/DEBUG] 17:48:53: POST(/invites) => 200 in 1.472584s;
[DEBUG] 17:48:53 auth.go:89: Auth succeeded
[DEBUG] 17:48:53 api.go:678: Invites requested
[DEBUG] 17:48:53 api.go:116: Housekeeping: Deleting old invite RdCPmrdjf5jhsbFKJPFQwG
[GIN/DEBUG] 17:48:53: GET(/invites) => 200 in 1.9524ms;
[DEBUG] 17:49:18 auth.go:89: Auth succeeded
[DEBUG] 17:49:18 api.go:482: Generating new invite
[DEBUG] 17:49:18 api.go:508: iZFAyvswahjvQmgZd8yMck: Sending invite email
[ERROR] 17:49:19 api.go:517: iZFAyvswahjvQmgZd8yMck: Failed to send to mairajenator@gmail.com
[DEBUG] 17:49:19 api.go:518: iZFAyvswahjvQmgZd8yMck: Error: x509: cannot validate certificate for 0.0.0.0 because it doesn't contain any IP SANs
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 400 with 200
[GIN/DEBUG] 17:49:19: POST(/invites) => 200 in 1.4735389s;
[DEBUG] 17:49:19 auth.go:89: Auth succeeded
[DEBUG] 17:49:19 api.go:678: Invites requested
[GIN/DEBUG] 17:49:19: GET(/invites) => 200 in 1.0186ms;
[DEBUG] 17:49:32 auth.go:89: Auth succeeded
[DEBUG] 17:49:32 api.go:482: Generating new invite
[DEBUG] 17:49:32 api.go:508: yGE6QBZoxBgLZKMaYN6PTR: Sending invite email
[ERROR] 17:49:33 api.go:517: yGE6QBZoxBgLZKMaYN6PTR: Failed to send to syedmairaj@hotmail.com
[DEBUG] 17:49:33 api.go:518: yGE6QBZoxBgLZKMaYN6PTR: Error: x509: cannot validate certificate for 0.0.0.0 because it doesn't contain any IP SANs
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 400 with 200
[GIN/DEBUG] 17:49:33: POST(/invites) => 200 in 1.4588291s;
[DEBUG] 17:49:33 auth.go:89: Auth succeeded
[DEBUG] 17:49:33 api.go:678: Invites requested
[DEBUG] 17:49:33 api.go:116: Housekeeping: Deleting old invite RfwDjPvVoquVcsrnJRVTXb
[GIN/DEBUG] 17:49:33: GET(/invites) => 200 in 1.9523ms;
[DEBUG] 17:49:39 auth.go:89: Auth succeeded
[DEBUG] 17:49:39 api.go:678: Invites requested
[GIN/DEBUG] 17:49:39: GET(/invites) => 200 in 1.9166ms;

**Comment by hrfee** [comment]
yeah this  was a bug, not sure how it was even working before. A new build is up on [builds.hrfee.pw](https://builds.hrfee.pw) and the `unstable` docker branch. Install it and see if it works now.

**Comment by mairajha** [comment]
**got this with ssl_tls**

[ERROR] 21:47:35 api.go:517: fQshL5MnBKfuMi4fCpEcZH: Failed to send to mairajenator@gmail.com
[DEBUG] 21:47:35 api.go:518: fQshL5MnBKfuMi4fCpEcZH: Error: tls: first record does not look like a TLS handshake
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 400 with 200
[GIN/DEBUG] 21:47:35: POST(/invites) => 200 in 600.5413ms;
[DEBUG] 21:47:35 auth.go:89: Auth succeeded
[DEBUG] 21:47:35 api.go:678: Invites requested
[GIN/DEBUG] 21:47:35: GET(/invites) => 200 in 1.9502ms;
[DEBUG] 21:47:46 daemon.go:37: Daemon: Checking invites

**this with starttls**
[DEBUG] 21:46:46 auth.go:89: Auth succeeded
[DEBUG] 21:46:46 api.go:482: Generating new invite
[DEBUG] 21:46:46 api.go:508: iFtyzQyBBG9fQ2Lz965N5a: Sending invite email
smtp.hushmail.com:587
[DEBUG] 21:46:46 daemon.go:37: Daemon: Checking invites
[ERROR] 21:46:48 api.go:517: iFtyzQyBBG9fQ2Lz965N5a: Failed to send to mairajenator@gmail.com
[DEBUG] 21:46:48 api.go:518: iFtyzQyBBG9fQ2Lz965N5a: Error: 535 5.7.0 [AUTHORIZATIONFAILED] User does not have a subscription for Desktop Access
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 400 with 200
[GIN/DEBUG] 21:46:48: POST(/invites) => 200 in 2.359266s;

**Comment by hrfee** [comment]
That's an error with your email provider you're sending with, they only allow desktop (SMTP) access with a subscription. Try a different service.

**Comment by mairajha** [comment]
changing email service provider works like a charm, well hotmail, gmail, yahoo & hushmail too not work for me, so I opt in Zoho Mail and it worked on first attempt, thanks a lot!

**Comment by mairajha** [comment]
for use it with my domain, what should I do? have to forward the port 8056? same as I forwarded the port 8096 for jellyfin to use outside my LAN over internet - any idea?

**Comment by theg00s3** [comment]
> yeah this was a bug, not sure how it was even working before. A new build is up on builds.hrfee.pw and the unstable docker branch. Install it and see if it works now.
@hrfee do you know when this fix will hit stable?

**Comment by hrfee** [comment]
> for use it with my domain, what should I do? have to forward the port 8056? same as I forwarded the port 8096 for jellyfin to use outside my LAN over internet - any idea?

Yes, 8056 but you should really put it behind a reverse proxy with HTTPS, otherwise your credentials could be potentially stolen. This applies to Jellyfin as well.

**Comment by hrfee** [comment]
> > yeah this was a bug, not sure how it was even working before. A new build is up on builds.hrfee.pw and the unstable docker branch. Install it and see if it works now.
> 
> 
> 
> @hrfee do you know when this fix will hit stable?

I'll publish a new version today or tomorrow.

**Comment by hrfee** [comment]
@theg00s3 just put v0.2.2 up with this included.
