### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by ashipaek0** [hrfee/jfa-go#151]
Crashing upon install, then launch

**To Reproduce**

install, then launch

jellyfin@racknerd-70c0a7:~$ jfa-go
2021/09/20 10:25:21 Using internal storage
jfa-go version: git (b29c24a)

Socket: /tmp/jfa-go.sock
2021/09/20 10:25:22 
A crash report has been saved to "/tmp/jfa-go-crash-2021-09-20T10:25:22.txt".
runtime error: invalid memory address or nil pointer dereference

**Logs**

/tmp/jfa-go-crash-2021-09-20T10:25:22.txt               
2021/09/20 10:25:21 Using internal storage
jfa-go version: git (b29c24a)
Socket: /tmp/jfa-go.sock

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.Exit({0xc336e0, 0x2703230})
        /drone/src/exit.go:57 +0x2e5
main.start.func2()
        /drone/src/main.go:159 +0x2a
panic({0xc336e0, 0x2703230})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/hrfee/jfa-go/logger.NewEmptyLogger(...)
        /drone/src/logger/logger.go:63
main.start(0x0, 0xf8)
        /drone/src/main.go:237 +0x9d5
main.main()
        /drone/src/main.go:749 +0x4c5

**Configuration**
nil

**Platform/Version**

Linux

Ubuntu 20.04

Both Stable and Unstable jfa builds.

**Comment by hrfee** [comment]
Sorry, this is a really dumb bug that should be fixed now in unstable, you should be able to get it in the next 10 minutes. I always test with the `-debug` option, and the function run when this argument isn't given was broken.
