### ISSUE TITLE
Latest unstable docker image crashing 

### ISSUE THREAD

**Issue by mLgz0rn** [hrfee/jfa-go#153]
#### Read the [FAQ](https://github.com/hrfee/jfa-go/wiki/FAQ) first!

**Describe the bug**

Latest Unstable is crashing on docker witch error  `runtime error: invalid memory address or nil pointer dereference` and is unable to start.
Rerolling to previous version works and stable works.

**To Reproduce**

Install latest unstable docker image.

**Logs**
```
2021/09/23 23:00:25 Using external storage
jfa-go version: git (b29c24a)
Socket: /tmp/jfa-go.sock

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.Exit({0xc36d20, 0x25ef4c0})
	/opt/build/exit.go:57 +0x2e5
main.start.func2()
	/opt/build/main.go:159 +0x2a
panic({0xc36d20, 0x25ef4c0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/hrfee/jfa-go/logger.NewEmptyLogger(...)
	/opt/build/logger/logger.go:63
main.start(0x0, 0x30)
	/opt/build/main.go:237 +0x9f5
main.main()
	/opt/build/main.go:749 +0x3f1
```
**Platform/Version**
Docker (Unraid 6.9.2)
Version 0.3.8
Commit 5b319d6

**Comment by hrfee** [comment]
This is the same issue as #151, which should be fixed now. Really sorry for not replying earlier, just started Uni so i'm a bit bogged down with other stuff.

**Comment by mLgz0rn** [comment]
Oh, can't believe I didn't see that issue :D.
And now worries! I just swapped back to the latest stable that was working!
