### ISSUE TITLE
Password reset solution not working with nginx config.

### ISSUE THREAD

**Issue by BobDaGecko** [hrfee/jfa-go#154]
#### Read the [FAQ](https://github.com/hrfee/jfa-go/wiki/FAQ) first!

**Describe the bug**

The password reset solution found [here](https://wiki.jfa-go.com/docs/password-resets/) doesn't seem to work for me. This isn't really a bug, I just need help getting the solution to work for my config.

**To Reproduce**

Enter code found [here](https://wiki.jfa-go.com/docs/password-resets/) into nginx. Restart nginx.

**Logs**

```
Oct 01 04:58:40 server nginx[1635059]: nginx: [emerg] invalid number of arguments in "proxy_set_header" directive in /etc/nginx/sites-enabled/example.com:34
Oct 01 04:58:40 server nginx[1635059]: nginx: configuration file /etc/nginx/nginx.conf test failed
Oct 01 04:58:40 server systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- An ExecStartPre= process belonging to unit nginx.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Oct 01 04:58:40 server systemd[1]: nginx.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit nginx.service has entered the 'failed' state with result 'exit-code'.
Oct 01 04:58:40 server systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: A start job for unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit nginx.service has finished with a failure.
```

**Configuration**

[Here](https://paste.nginx.org/20) is one of the configs I tired.

**Platform/Version**

Ubuntu: 20.04.3
Nginx: 1.18.0
Jfa-Go: 0.3.8
Jellyfin: 10.7.7

**Comment by hrfee** [comment]
You need to change the `<any local ip address>` to a local ip on your network, e.g. 192.168.1.20.

**Comment by BobDaGecko** [comment]
So I fixed up the config to [this](https://paste.nginx.org/00). Nginx works properly but now when I go to Jellyfin and try to click submit after I entered my username, nothing happens. Jellyfin logs don't show anything happening either.
