### ISSUE TITLE
Email verification link works but displays "Page not found"

### ISSUE THREAD

**Issue by Tonomis** [hrfee/jfa-go#157]
**Describe the bug**

Affected by the 0.3.8 token bug, the 0.3.9 fixed it.
Now, the new account is well created but when i follow the link in the confirmation mail, I've got a "Page not found".

(I know you're back at uni, and this issue is not so important, it's just to notice it, take your time ! :) ) 

**To Reproduce**

Docker + Traefik
0.3.9 Version

**Comment by robocrax** [comment]
I had this same issue and turns out my email had a plus character in it. I ran out so used the infinite email trick.

I used another email and found out emails with characters are not handled properly.

Was this the case for you or should I open a new issue?

**Comment by Tonomis** [comment]
I do not use jfa-go anymore and I really do not remember this issue :(
The only thing I can tell you is that email was'nt containing any special characters

**Comment by SteveGBuck** [comment]
> I had this same issue and turns out my email had a plus character in it. I ran out so used the infinite email trick.
> 
> 
> 
> I used another email and found out emails with characters are not handled properly.
> 
> 
> 
> Was this the case for you or should I open a new issue?

I am having this issue too. Using a "+" tag in my email address results in 404 error on email confirmation page.

**Comment by hrfee** [comment]
> > I had this same issue and turns out my email had a plus character in it. I ran out so used the infinite email trick.
> > I used another email and found out emails with characters are not handled properly.
> > Was this the case for you or should I open a new issue?
> 
> I am having this issue too. Using a "+" tag in my email address results in 404 error on email confirmation page.

Sorry for only just seeing this, but I believe this is because Jellyfin doesn't like certain characters in its usernames, meaning "Use email address as username" won't work with such an email address. The user is now notified of this before submitting.
