### ISSUE TITLE
unable to run jfa-go

### ISSUE THREAD

**Issue by mairajha** [hrfee/jfa-go#16]
tried to run the program after few days but got below mentioned error, kindly take a look and revert back with solution

[35mjfa-go version: [0;97m0.0.0[0;35m ([0;37mfa96f21[0;35m)
[0mSocket: C:\Users\MrKhan\AppData\Local\Temp\jfa-go.sock
[INFO] 19:52:23 [35m

WARNING: Don't use debug mode in production, as it exposes pprof on the network.

[0m
[DEBUG] 19:52:23 main.go:359: Loaded config file "C:\Users\MrKhan\AppData\Roaming\jfa-go\config.ini"
[DEBUG] 19:52:23 main.go:369: Loading storage
[DEBUG] 19:52:23 main.go:426: Using css file "bs4-jf.css"
[DEBUG] 19:52:23 main.go:441: Using Jellyfin for authentication
2020/11/21 19:52:23 Failed to authenticate with Jellyfin @ http://localhost:8096: Timed out
[ERROR] 19:52:23 main.go:458: Failed to authenticate with Jellyfin @ http://localhost:8096: Code 0

**Comment by hrfee** [comment]
This means it couldn't connect to jellyfin on `http://localhost:8096`, are you sure its running and can you access it yourself on that address?

**Comment by mairajha** [comment]
yeah, I can access it on http://localhost:8096

**Comment by hrfee** [comment]
maybe try using the system's IP instead of just `localhost`?

**Comment by mairajha** [comment]
Where should I edit ip address in jfa-go?

**Comment by hrfee** [comment]
If you can access the web UI, its in Settings > Jellyfin > Server Address.

If not, edit `config.ini` and change value for `server` in the `[jellyfin]` section.

**Comment by mairajha** [comment]
I can see config-default only

**Comment by hrfee** [comment]
You’re using Windows iirc, so press the Windows key and R on your keyboard
to bring up the run menu, and in the text box type %appdata% . A file
explorer window should come up, and there should be a ‘jfa-go’ folder. The
config file is in there.

>

**Comment by mairajha** [comment]
same error, but this time it will show my ip instead of local host


E:\jf-accounts-go\jf-accounts-go-new\jfa-go_git-fa96f21_Windows_x86_64.tar>jfa-go
[35mjfa-go version: [0;97m0.0.0[0;35m ([0;37mfa96f21[0;35m)
[0mSocket: C:\Users\MrKhan\AppData\Local\Temp\jfa-go.sock
[INFO] 16:43:02 [35m

WARNING: Don't use debug mode in production, as it exposes pprof on the network.

[0m
[DEBUG] 16:43:02 main.go:359: Loaded config file "C:\Users\MrKhan\AppData\Roaming\jfa-go\config.ini"
[DEBUG] 16:43:02 main.go:369: Loading storage
[DEBUG] 16:43:02 main.go:426: Using css file "bs4-jf.css"
[DEBUG] 16:43:02 main.go:441: Using Jellyfin for authentication
2020/11/23 16:43:02 Failed to authenticate with Jellyfin @ http://192.168.18.30:8096: Timed out
[ERROR] 16:43:02 main.go:458: Failed to authenticate with Jellyfin @ http://192.168.18.30:8096: Code 0

**Comment by mairajha** [comment]
should I do a clean reinstallation again? by deleting jfa-go folder inside %appdata%?

**Comment by hrfee** [comment]
I doubt that’ll make a difference, but you can try. The only other thing I
can think of is the firewall, maybe it’s blocking access to jellyfin?

**Comment by mairajha** [comment]
there isn't any firewall that is blocking a way - infact few days back its working flawlessly

**Comment by hrfee** [comment]
Could you run `jfa-go.exe test` and send the output? If it works you'll probably need to censor some of it.

**Comment by mairajha** [comment]
same output for jfa-go test

E:\jf-accounts-go\New folder\jfa-go_git-e35d057_Windows_x86_64.tar>jfa-go test
[35mjfa-go version: [0;97m0.0.0[0;35m ([0;37me35d057[0;35m)
[0mSocket: C:\Users\MrKhan\AppData\Local\Temp\jfa-go.sock
[INFO] 17:10:26 [35m

WARNING: Don't use debug mode in production, as it exposes pprof on the network.

[0m
[DEBUG] 17:10:26 main.go:359: Loaded config file "C:\Users\MrKhan\AppData\Roaming\jfa-go\config.ini"
[DEBUG] 17:10:26 main.go:369: Loading storage
[DEBUG] 17:10:26 main.go:426: Using css file "bs4-jf.css"
[DEBUG] 17:10:26 main.go:441: Using Jellyfin for authentication
2020/11/23 17:10:26 Failed to authenticate with Jellyfin @ http://192.168.18.30:8096: Timed out
[ERROR] 17:10:26 main.go:458: Failed to authenticate with Jellyfin @ http://192.168.18.30:8096: Code 0

**Comment by hrfee** [comment]
what version of Jellyfin are you running? it probably isn't related but may as well check.

**Comment by mairajha** [comment]
I am on 10.6.1 - before its working just fine on same build and on same pc as well

**Comment by hrfee** [comment]
ok, i have no idea at this point. Did it stop working when you upgraded?

**Comment by mairajha** [comment]
I installed & run 10.6.4 after that this error incurred
But when I run 10.6.4 I didn't run jfa-go

**Comment by hrfee** [comment]
It works for me on 10.6.4, could you try it on that?

**Comment by mairajha** [comment]
same error - 

what I found that my localhost url is using myfunflix also (as mention below) can I paste that whole link instead of ip in config.ini?

http://localhost:8096/jellyfin.myfunflix.com/web/index.html#!/login.html?serverid=774b176336384f4db1dcbf572384abe4

**Comment by mairajha** [comment]
tried it with **_http://localhost:8096/jellyfin.myfunflix.com/web/index.html#!/login.html?serverid=774b176336384f4db1dcbf572384abe4_** this also, still same error

**Comment by mairajha** [comment]
I removed file from %appdata% now able to run the setup but stuck on page 3
![image](https://user-images.githubusercontent.com/52917522/99965496-c1950a00-2db6-11eb-84cc-e26c61928f9c.png)
its not accepting localhost neither ip on host column

**Comment by mairajha** [comment]
now stuck there, testing field keep spinning 
![image](https://user-images.githubusercontent.com/52917522/99966781-a1664a80-2db8-11eb-8e0c-d098082e1f48.png)

below are the logs which I am getting now

E:\jf-accounts-go\New folder\jfa-go_git-e35d057_Windows_x86_64.tar>jfa-go
[35mjfa-go version: [0;97m0.0.0[0;35m ([0;37me35d057[0;35m)
[0mSocket: C:\Users\MrKhan\AppData\Local\Temp\jfa-go.sock
[INFO] 18:17:39 Copied default configuration to "C:\Users\MrKhan\AppData\Roaming\jfa-go\config.ini"
[INFO] 18:17:39 Loading routes
[INFO] 18:17:39 Loading setup @ 0.0.0.0:8056
[GIN] GET(/) => 200


[31m2020/11/23 18:18:11 [Recovery] 2020/11/23 - 18:18:11 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212 (0x50ffb5)
/usr/local/go/src/runtime/signal_windows.go:246 (0x50fe4d)
/usr/local/go/src/net/http/client.go:595 (0x7859fd)
/usr/local/go/src/net/http/client.go:586 (0xc29bca)
/drone/src/jfapi/jfapi.go:75 (0xc29bac)
/drone/src/setup.go:18 (0xc91c8c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa50181)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0xa64466)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa50181)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0xa63553)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa50181)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0xa5a664)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0xa59d54)
/usr/local/go/src/net/http/server.go:2843 (0x7d5c29)
/usr/local/go/src/net/http/server.go:1925 (0x7d124c)
/usr/local/go/src/runtime/asm_amd64.s:1374 (0x532080)
[0m
[GIN] POST(/jellyfin/test) => 500
2020/11/23 18:18:22 Failed to authenticate with authJF @ localhost:8096: Timed out
[INFO] 18:18:22 Auth failed with code 0 (%!s(<nil>))
[GIN] POST(/jellyfin/test) => 401
2020/11/23 18:18:22 Failed to authenticate with authJF @ localhost:8096: Timed out
[INFO] 18:18:22 Auth failed with code 0 (%!s(<nil>))
[GIN] POST(/jellyfin/test) => 401
2020/11/23 18:18:22 Failed to authenticate with authJF @ localhost:8096: Timed out
[INFO] 18:18:22 Auth failed with code 0 (%!s(<nil>))
[GIN] POST(/jellyfin/test) => 401
2020/11/23 18:18:24 Failed to authenticate with authJF @ localhost:8096: Timed out
[INFO] 18:18:24 Auth failed with code 0 (%!s(<nil>))
[GIN] POST(/jellyfin/test) => 401
2020/11/23 18:18:42 Failed to authenticate with authJF @ localhost:8096: Timed out
[INFO] 18:18:42 Auth failed with code 0 (%!s(<nil>))
[GIN] POST(/jellyfin/test) => 401
2020/11/23 18:18:50 Failed to authenticate with authJF @ http://localhost:8096: Timed out
[INFO] 18:18:50 Auth failed with code 0 (%!s(<nil>))
[GIN] POST(/jellyfin/test) => 401
2020/11/23 18:19:00 Failed to authenticate with authJF @ http://192.168.18.30:8096: Timed out
[INFO] 18:19:00 Auth failed with code 0 (%!s(<nil>))
[GIN] POST(/jellyfin/test) => 401
2020/11/23 18:19:01 Failed to authenticate with authJF @ http://192.168.18.30:8096: Timed out
[INFO] 18:19:01 Auth failed with code 0 (%!s(<nil>))
[GIN] POST(/jellyfin/test) => 401
2020/11/23 18:19:01 Failed to authenticate with authJF @ http://192.168.18.30:8096: Timed out
[INFO] 18:19:01 Auth failed with code 0 (%!s(<nil>))
[GIN] POST(/jellyfin/test) => 401


[31m2020/11/23 18:19:04 [Recovery] 2020/11/23 - 18:19:04 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212 (0x50ffb5)
/usr/local/go/src/runtime/signal_windows.go:246 (0x50fe4d)
/usr/local/go/src/net/http/client.go:595 (0x7859fd)
/usr/local/go/src/net/http/client.go:586 (0xc29bca)
/drone/src/jfapi/jfapi.go:75 (0xc29bac)
/drone/src/setup.go:18 (0xc91c8c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa50181)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0xa64466)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa50181)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0xa63553)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa50181)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0xa5a664)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0xa59d54)
/usr/local/go/src/net/http/server.go:2843 (0x7d5c29)
/usr/local/go/src/net/http/server.go:1925 (0x7d124c)
/usr/local/go/src/runtime/asm_amd64.s:1374 (0x532080)
[0m
[GIN] POST(/jellyfin/test) => 500

**Comment by mairajha** [comment]
it's working fine now - what I do is to remove jfa-go folder from %appdata% and setup the whole thing from scratch. Thanks for your help!
