### ISSUE TITLE
html code not possible in messages/notifications anymore

### ISSUE THREAD

**Issue by mLgz0rn** [hrfee/jfa-go#164]
**Describe the bug**

So before I was able to use html code in the emails that gets sent out to customize them abit.
But not anymore, it looks like this now:

https://i.imgur.com/801vKfA.png

Turns into 

https://i.imgur.com/2iJsI3t.png

So it seems like the characters "<" and ">" is not being added when a mail is sent.
If I do "<<style>>" one of the < gets added but not the > as shown here https://i.imgur.com/Adqoaky.png

**To Reproduce**

Use html code in the messages/notifications

**Platform/Version**
Docker Commit 0bf8cd6

**Comment by hrfee** [comment]
Apologies, switched to a new SMTP library recently to fix another issue, and I misunderstood how it worked, which caused the plain text version of the email to always appear. It should be fixed now, a build will be available in a bit.

**Comment by mLgz0rn** [comment]
Awesome! Thank you so much
