### ISSUE TITLE
Feature request: Ombi User Profile

### ISSUE THREAD

**Issue by xiNeRoar** [hrfee/jfa-go#165]
Can we have a feature just like the user profile function but also apply to ombi?
That way we can have different class of user but no universally have the same access right

**Comment by hrfee** [comment]
There's already the "new user defaults" for Ombi but obviously this only gives you one set of permissions. I could change this to work more like Jellyfin user profiles if you think you would use it though.

**Comment by xiNeRoar** [comment]
i think the way like jellyfin user profile will give user more control of their user. Thank you very much dev :P

**Comment by hrfee** [comment]
I've integrated user profiles and ombi user defaults in 4da1c8c. Go into Settings > User Profiles, and you can add the settings from an Ombi user to a profile. Your old Ombi User Defaults will no longer apply so you'll need to set this up for new ombi users to be created. The "Apply settings" thing in Accounts will now also apply ombi settings.

**Comment by xiNeRoar** [comment]
Thanks so much!! Do i need to pull the new release to hvaey this update?

**Comment by hrfee** [comment]
Yeah, you need to download the unstable version to use this for now until I do a new release.

**Comment by xiNeRoar** [comment]
> I've integrated user profiles and ombi user defaults in [4da1c8c](https://github.com/hrfee/jfa-go/commit/4da1c8c2b62c041c2797a8c078cdf1ccc7b84502). Go into Settings > User Profiles, and you can add the settings from an Ombi user to a profile. Your old Ombi User Defaults will no longer apply so you'll need to set this up for new ombi users to be created. The "Apply settings" thing in Accounts will now also apply ombi settings.

Is this included in the new release? Sorry but i dont know where to find it even followed your instructions

**Comment by hrfee** [comment]
Yeah it's in 0.4.0, see the below screenshot.

![ombi](https://user-images.githubusercontent.com/11923517/152247139-9bd8287b-3279-49da-86d1-1dece0f361a2.jpg)

**Comment by xiNeRoar** [comment]
Thank you very much. I just overlooked. Thanks for all the good work🤗
