### ISSUE TITLE
Can't set "Notify on" to true

### ISSUE THREAD

**Issue by Luxumbra27** [hrfee/jfa-go#166]
**Describe the bug**

On a clean configuration of jfa-go, using the latest docker image, after having created an invitation, I cannot set any of the "Notify On:" settings to true. The checkbox stays unchecked on click.

**To Reproduce**

Clean install and config, with SMTP and Telegram configured.

**Logs**

Container
```
2021-11-17 11:26:39 [GIN] GET(/invites) => 200

2021-11-17 11:26:39 [GIN] GET(/users) => 200 

2021-11-17 11:26:39 [GIN] GET(/users/announce) => 200
```

Console
`Failed to load resource: the server responded with a status of 500 () /invites/notify:1 `

**Configuration**

Clean install and config, with SMTP, Ombi, Jellyfin, and Telegram configured and working behind a traefik proxy.

**Platform/Version**

On Docker:
Version 0.3.9
Commit 0fe72b4

**Comment by Luxumbra27** [comment]
My bad ! I did not set a email address for the "admin" user, the error whith "-debug" is:
`Couldn't find email address. Make sure it's set`

Which is clear. I set an email address and now the toggle works.
There is still an issue because I don't want email notifications, only telegram, and yet I have to set an admin email address.
How configure telegram only notifications ?

**Comment by hrfee** [comment]
I'm pretty sure only email is supported for admin notifications right now, although i may have started adding support for others and just not finished it. Either way i'll add this today, and add an "Ask for on registration" option for each of the notification methods.

**Comment by hrfee** [comment]
First part added in e7ca335, if Jellyfin Login is enabled, notifications should be sent to all the contact methods you have set up for your admin account.

**Comment by hrfee** [comment]
Last part added in 73c7f22, Disable "Show on user registration" in Settings > Discord/Telegram/Matrix to hide the "Link xxx" button on the user registration form.

**Comment by Luxumbra27** [comment]
Thank you very much for the quick reply and the new feature ! You rock !
