### ISSUE TITLE
Run under path of Jellyfin

### ISSUE THREAD

**Issue by IngwiePhoenix** [hrfee/jfa-go#17]
Short and simple:

- I am using NGINX to rev-proxy to Jellyfin.
- I would love to run jfa-go.

Can I run it in a sub-address? i.e.: `cloud.mydomain.tld/jfa-go/`?
I assume all I'd have to do is something like...

```nginx
location /jfa-go {
  proxy_pass http://localhost:12345
  # ...
}
```

But I'd just like to make sure that this is supported :)

**Comment by hrfee** [comment]
Yeah, that should work fine.

**Comment by IngwiePhoenix** [comment]
```
journalctl -u jellyfin-accounts.service -f
-- Logs begin at Sat 2020-11-21 15:47:47 UTC. --
Nov 22 11:06:17 ingwie-io jfa-go[7430]: [INFO] 11:06:17 Authenticated with http://localhost:8096
Nov 22 11:06:17 ingwie-io jfa-go[7430]: [INFO] 11:06:17 Loading routes
Nov 22 11:06:17 ingwie-io jfa-go[7430]: [INFO] 11:06:17 Starting password reset daemon
Nov 22 11:06:17 ingwie-io jfa-go[7430]: [INFO] 11:06:17 Invite daemon started
Nov 22 11:06:17 ingwie-io jfa-go[7430]: [INFO] 11:06:17 Starting router @ 0.0.0.0:9191
Nov 22 11:06:22 ingwie-io jfa-go[7430]: [GIN] GET(/) => 200
Nov 22 11:06:44 ingwie-io jfa-go[7430]: [GIN] GET(/) => 200
Nov 22 11:10:42 ingwie-io jfa-go[7430]: [GIN] GET(/accounts) => 404
Nov 22 11:11:42 ingwie-io jfa-go[7430]: [GIN] GET(/accounts/) => 404
Nov 22 11:11:42 ingwie-io jfa-go[7430]: [GIN] GET(/accounts/bs4-jf.css) => 404
```

Welp, time to look up how re-writes work I guess. The `/` calls were using `curl` from the localhost directly to the jfa-go server.

**Comment by IngwiePhoenix** [comment]
Got it:
```nginx
    location ~ ^/accounts(.*)$ {
        # Proxy for jfa-go, Jellyfin accounts
        rewrite ^/accounts/(.*) /$1 break;
        proxy_pass http://localhost:9191;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        # Disable buffering when the nginx proxy gets very resource heavy upon streaming
        proxy_buffering off;
    }
```

Copied `location /` from Jellyfin itself and consulted: https://stackoverflow.com/questions/17423414/nginx-proxy-pass-subpaths-not-redirected

Unfortunately, I couldn't get the first answers' non-regex method working. But hey, for a single entry, this should do just fine.

Feel free to use this in the docs or somewhere :) 

Also, you might have noticed I used `journalctl` - well, here is my systemd unit:

```
[Unit]
Description=Jellyfin Accounts (jfa-go)
After=network.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/srv/jellyfin/jfa-go
WorkingDirectory=/srv/jellyfin
User=jellyfin
Group=jellyfin

[Install]
WantedBy=multi-user.target
```

Probably going to implement a cron to periodically check for updates, stop the demon, apply the update and restart. But this is pretty much enough for now.

**Comment by IngwiePhoenix** [comment]
So, while the initial loading works, subsequent loading does not. I suppose the base URL can not be configured and I have to build from source to get that working?

**Comment by hrfee** [comment]
what do you mean when you say initial loading works but subsequent loading doesn't? Also, i've just given your nginx config a go and it looks like it works fine to me.

**Comment by hrfee** [comment]
Nevermind, its broken. I'll try add a URL base option.

**Comment by hrfee** [comment]
Ok it looks like the only things not loading from jfa-go were the favicons, but the reason the page is broken was because Jellyfins CSP header wasn't allowing bootstrap and popper.js to be downloaded. I'll add the URL base and our own CSP to fix this.

**Comment by hrfee** [comment]
Added the URL base option in 9dbf60e, which is building right now. I also made a [wiki page](https://github.com/hrfee/jfa-go/wiki/Reverse-Proxying) for reverse proxying which includes a version of your config modified to remove the CSP header. Just add:
```
proxy_hide_header Content-Security-Policy;
 You can grab a build of this version [here](https://builds.hrfee.pw/view/hrfee/jfa-go).

**Comment by Cookie-Monster-Coder** [comment]
> 
> 
> Added the URL base option in [9dbf60e](https://github.com/hrfee/jfa-go/commit/9dbf60e3dfc9657aa0d84ebb164d384783939381), which is building right now. You'll need to set it to `/accounts`. I also made a [wiki page](https://github.com/hrfee/jfa-go/wiki/Reverse-Proxying) for reverse proxying which includes a version of your config modified to remove the CSP header. Just add this above `proxy_pass ...`:
> 
> ```
> proxy_hide_header Content-Security-Policy;
> add_header Content-Security-Policy "";
> ```
> 
> You can grab a build of this version [here](https://builds.hrfee.pw/view/hrfee/jfa-go).

I'm confused. I keep getting
```
404
Page not found.

Need help? Contact me.
```

**Comment by hrfee** [comment]
@Cookie-Monster-Coder do you use this in conjunction with the URL Base option or is it unnecessary?

**Comment by Cookie-Monster-Coder** [comment]
> 
> 
> @Cookie-Monster-Coder do you use this in conjunction with the URL Base option or is it unnecessary?

You have to use it with the URL Base option in the config file, otherwise the UI looks funky/messed up. At least from my limited time testing/trying to figure out why it's not working.

**Comment by hrfee** [comment]
Ok great. Since at least one person's got it working and @IngwiePhoenix hasn't replied in a bit i'll close this.
