### ISSUE TITLE
[Bug] Creating the discord bot causes the server to crash with index out of range.

### ISSUE THREAD

**Issue by Rojikku** [hrfee/jfa-go#173]
#### Read the [FAQ](https://github.com/hrfee/jfa-go/wiki/FAQ) first! <-- This link doesn't go anywhere, protip.

**Describe the bug**

Setting up the discord bot produces:
```
[INFO] 00:44:42  Loaded @ 0.0.0.0:8056
2021/11/25 00:44:42 error closing resp body
panic: runtime error: index out of range [-1]

goroutine 26 [running]:
main.(*DiscordDaemon).run(0xc001b20270)
	/opt/build/discord.go:92 +0x47b
created by main.start
	/opt/build/main.go:516 +0x36dd
```

**To Reproduce**

I used the docker image (yours), with originally latest, because I'm not a savage. Once I identified the issue I switched to unstable, to no avail. Every time I have to reconfigure the server, because I don't know any other way to fix it than deleting my persistent volume. I enabled admin notifications on account creation, used jellyfin for authentication, and such.

**Logs**
See above.

**Configuration**

If you see it as necessary, include relevant sections of your `config.ini`, for example, include `[email]` and `[smtp]|[mailgun]` if you have an email issue.

**Platform/Version**
Docker, latest and unstable

**Comment by hrfee** [comment]
Sorry for such a late reply, if you're still interested in getting this working I believe this is because your Discord bot is not a member of a server. Discord bots can't send messages out of the blue, they can only message users in a shared server. You can get the invite link to add them to your server in the Discord developer portal (see image [here](https://wiki.jfa-go.com/docs/bots/discord/#6-enable-permissions-get-invite-link)), which you can click to add it. If this was the problem i'll add a more descriptive error for other users.

**Comment by recom273** [comment]
Can you take a look at the wiki instructions, discord seems to have changed the way to get the invite link. I completed the permission check but couldnt get the link.

 I was also confused by the screenshot of the telegram tab? I would really like to get this function working.

**Comment by hrfee** [comment]
I'll have a look at discord now. For telegram, just message the "BotFather" account (theres a link at the top of the page) and send "/newbot", then follow through with the instructions. Once you're done, it'll give you an API key, which you paste into the box in Settings > Telegram in jfa-go.

**Comment by hrfee** [comment]
You're right, it's changed slightly. You need to choose "in app authorization" on the OAuth2 tab, then select your choices. The URL doesn't show up anymore so you need to copy the Client ID and put it in this url: `https://discordapp.com/oauth2/authorize?&client_id=YOUR_CLIENT_ID&scope=bot&permissions=19457` then visit it. The wiki's been updated to include this.

**Comment by recom273** [comment]
Ok - thanks - I will give it a try.

I am still totally lost on why there is a discord tab, why you follow everything in discord - add a discord bot to the your discord server and then add the discord api to the telegram tab in jfa-go. 

Shouldnt step 7 be - post the token into the discord tab api and a screenshot of the discord tab?

**Comment by hrfee** [comment]
You're right in having no idea why it says that, i dont either 🤣. I banged out all of the chat-bots in a short period so must've got them confused. Copy the token into Settings > Discord > API Token.

**Comment by recom273** [comment]
Ok - I tried it but jfa-go keeps on crashing and when I added the bot to discord it was always offline - anyway, now I know I’m on the right path (or tab) then I can keep on tinkering. Thanks! Happy new year!

**Comment by RisedSky** [comment]
Using the stable package (not docker) crash the install section, block at the bot section, loading indefinitely...

I'm blocked at the install :/

**Comment by RisedSky** [comment]
It is fixed for me, works very well !
