### ISSUE TITLE
Plugin with repository

### ISSUE THREAD

**Issue by butts136** [hrfee/jfa-go#176]
Hi,

This (app/plugin) could be really usefull for me but I'm not good enough to make it work on my seedbox server.

I tried real hard but that's not enough.

It would be very appreciated if you could add the possibility to install jfa-go with a one click install from a repository directly on Jellyfin plugins tab.

I don't know if it's even possible to do it.

Thanks

**Comment by hrfee** [comment]
Sorry, this isn't possible without a full rewrite as jfa-go is written in Go while Jellyfin is written in C#.
