### ISSUE TITLE
[Bug] After account created from invite, popup says Jellyfin

### ISSUE THREAD

**Issue by unclebacon-live** [hrfee/jfa-go#177]
I use Emby and after creating an account from an invite the Success popup says `Your account has been created. Click below to continue to Jellyfin.` Would be awesome if it said the same as the `Substitute occurrences of "Jellyfin"` option.

A minor oversight I'm sure, otherwise everything works AMAZING! Thanks!

**Comment by hrfee** [comment]
Sorry for being late on this, this should be fixed in unstable now.
