### ISSUE TITLE
API Unauthorized

### ISSUE THREAD

**Issue by kevingorman1000** [hrfee/jfa-go#178]
Hello, 

I'm currently trying to work with the API to create an invite code once a user has authenticated their license key. 

Looking at swagger, it seems pretty simple however, I am trying to use the API within postman and php. All I keep getting is 
`{
    "response": "",
    "error": "Unauthorized"
}`

I have authorized a new api key. Having added the "Authorization" to header with the API key, it still gives me the same problem. 

The PHP file I'm using looks like this 

````
<?php

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'http://URLToJFA:30120/invites');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"days\": 1,\n  \"hours\": 2,\n  \"label\": \"For Friends\",\n  \"minutes\": 3,\n  \"months\": 0,\n  \"multiple-uses\": true,\n  \"no-limit\": false,\n  \"profile\": \"DefaultProfile\",\n  \"remaining-uses\": 5,\n  \"send-to\": \"jeff@jellyf.in\",\n  \"user-days\": 1,\n  \"user-expiry\": true,\n  \"user-hours\": 2,\n  \"user-minutes\": 3,\n  \"user-months\": 1\n}");

$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: XXXXXXXXXXXXXXXXXXAwOk1hc3NpdmVEb2cyMDE2ISE=';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

echo $result;

?>
````

This was converted from the curl command supplied in swagger. 

I have also tried adding "http://URLToJFA:30120/invites?api_key=XXXXXXXXXXXXXXXXXXAwOk1hc3NpdmVEb2cyMDE2ISE=" with the same outcome. 

The Curl command that is provided is: 

`curl -X 'POST' \
  'http://URLToJfa:30120/invites' \
  -H 'accept: application/json' \
  -H 'Authorization: XXXXXXXXXXXXXXXXXXAwOk1hc3NpdmVEb2cyMDE2ISE=' \
  -H 'Content-Type: application/json' \
  -d '{
  "days": 1,
  "hours": 2,
  "label": "For Friends",
  "minutes": 3,
  "months": 0,
  "multiple-uses": true,
  "no-limit": false,
  "profile": "DefaultProfile",
  "remaining-uses": 5,
  "send-to": "jeff@jellyf.in",
  "user-days": 1,
  "user-expiry": true,
  "user-hours": 2,
  "user-minutes": 3,
  "user-months": 1
}'`

and even when I run this command directly, I still get the unauthorized error. 

Any suggestions would be great. 

Thank you.

**Comment by hrfee** [comment]
currently the API isn't particularly aimed at this use, so right now it works like this:
* User sends request to `/token/login` with username and pass. 
* A "token" and a cookie named "refresh" are returned, the former lasting 20 minutes and the latter lasting 24 hours. 
* The refresh cookie can then be used in a request to `/token/refresh` to get a new "token" without a username and password.

For your implementation you may as well ignore the refresh cookie part and just make sure to hit `/token/login` and store the returned token at least every 20 minutes, or when a 401 is encountered.

For `/token/login`, simple basic auth is used:
```shell
$ curl -u username:password http://jfa-go/token/login
{"token":"a_long_token"}
```
Then for any other request, e.g `/invites` use header `Authorization: Bearer a_long_token`:
```shell
$ curl -H "Authorization: Bearer a_long_token" http://jfa-go/invites
```
