### ISSUE TITLE
URL BASE BREAK DOCKER UNSTABLE

### ISSUE THREAD

**Issue by Killianbe** [hrfee/jfa-go#18]
Hello
the recent modification on the base url broke my jfa, docker unstabe, unable to connect to the admin page. I don't use a template, only a json for the modified lang

**Comment by hrfee** [comment]
Have you set a value for `url_base`? If it's not set nothing should change.

**Comment by hrfee** [comment]
Also is there any errors in the logs?

**Comment by Killianbe** [comment]
I don't use it after your update. 
Nothing in logs

**Comment by hrfee** [comment]
Nothing at all? not even this?
```
[GIN] GET(/) => 200
```

What happens when you try to load the page? Is your browser giving you an error, or is the page just blank?

**Comment by Killianbe** [comment]
jfa-go version: git (9dbf60e)


Socket: /tmp/jfa-go.sock


[INFO] 11:52:02 Authenticated with http://136.243.2.23:8096


[INFO] 11:52:02 Loading routes


[INFO] 11:52:02 Invite daemon started


[INFO] 11:52:02 Starting router @ 0.0.0.0:8056


[GIN] GET(/) => 200


[GIN] GET(/modules/settings.js) => 200


[GIN] GET(/modules/bs4.js) => 200

**Comment by hrfee** [comment]
so it looks like it loads fine. What shows up in your browser then?

**Comment by Killianbe** [comment]
when i go to jfa, i can't login, popup with login form not appear

**Comment by Killianbe** [comment]
ok i've clear cache and it's ok now, my bad sorry !

**Comment by hrfee** [comment]
ah ok great. I'lll close this then.
