### ISSUE TITLE
Failure to send emails via Mailgun

### ISSUE THREAD

**Issue by LubricantJam** [hrfee/jfa-go#183]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**

When attempting to send any emails, an error occurs.

**To Reproduce**

Enable Mailgun and try to send an email.

**Logs**

``Failed to send announcement message: invalid character 'M' looking for beginning of value
``

**Configuration**

```
[email]
; general email settings.
; default email language. submit a pr on github if you'd like to translate.
language    = en-gb
; use email address from invite form as username on jellyfin.
no_username = true
; method of sending email to use.
method      = mailgun
; address to send emails from
address     = REDACTED
; the name of the sender
from        = REDACTED
; send emails as plain text instead of html.
plaintext   = false
```

```
[mailgun]
; mailgun api connection settings
api_url = https://api.eu.mailgun.net/v3/REDACTED
api_key = 2173f**********************************
```

**Platform/Version**

Ubuntu 20.04 (Not in Docker)
Version 0.3.9
Commit 0fe72b4

**Comment by hrfee** [comment]
Closing as we fixed this in Discord, for others this shouldn't be an issue anymore but if it is, add `/messages` to the end of your `api_url`.
