### ISSUE TITLE
[BUG] Email verification 404 not found

### ISSUE THREAD

**Issue by RisedSky** [hrfee/jfa-go#187]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**

![image](https://user-images.githubusercontent.com/23197999/149412334-e2f49758-aed4-4424-8c1f-99956d76c3d0.png)
Clicking it gives 
![image](https://user-images.githubusercontent.com/23197999/149412421-83d4af90-bcde-48c0-ae90-a8a6942fc8cd.png)

Also, note that it gives HTTPS, my server has only HTTP (needed to change from HTTPS to HTTP in my link)

**To Reproduce**

Email verification => click the link => 404 not found

**Logs**

**If you're using a build with a tray icon, right-click on it and press "Open logs" to access your logs.**

> When you notice the problem, check the output of `jfa-go`. If the problem is not obvious (e.g a panic (red text) or 'ERROR' log), re-> run jfa-go with the `-debug` argument and reproduce the problem. You should then take a screenshot of the output, or paste it here, > preferably between \`\`\` tags (e.g \`\`\``Log here`\`\`\`). Remember to censor any personal information.
[Didn't work for me]

If nothing catches your eye in the log, access the admin page via your browser, go into the console (Right click > Inspect Element > Console), refresh, reproduce the problem then paste the output here in the same way as above.

**Configuration**

If you see it as necessary, include relevant sections of your `config.ini`, for example, include `[email]` and `[smtp]|[mailgun]` if you have an email issue.

**Platform/Version**

Latest stable debian 

Include the platform jfa-go is running on (e.g Windows, Linux, Docker), the version (first line of output by `jfa-go` or Settings>About in web UI), and if necessary the browser version and platform.

**Comment by hrfee** [comment]
For the https:// URL, the url is taken from Settings > Invite Emails > URL Base, check that doesn't have https://. For the other part, what is the rough format of the broken URL? For me it's `https://my-address/invite/invite-code?key=confirmation-code`.

**Comment by RisedSky** [comment]
it gives this in my mail : https://mydomain/invite/aLAPyDdsh4WCojoA7MTTRd?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRoZWdlZWttaW5lY3JhZnQyN0BnbWFpbC5jb20iLCJleHAiOjE2NDIxNTI2MzgsImludml0ZSI6ImFMQVB5RGRzaDRXQ29qb0E3TVRUUmQiLCJwYXNzd29yZCI6IlIxczNkc2t5IiwidGVsZWdyYW1QSU4iOiIiLCJ0eXBlIjoiY29uZmlybWF0aW9uIiwidXNlcm5hbWUiOiJ0aGVnZWVrbWluZWNyYWZ0MjciLCJ2YWxpZCI6dHJ1ZX0.B_794t-GzAuld9fQNLYYdxfEUs63D75eoqujfQdDoq4

My domain is http not https, and in the config : 
![image](https://user-images.githubusercontent.com/23197999/149418127-fa269bb6-7638-43c0-a902-915dc11d15f7.png)
![image](https://user-images.githubusercontent.com/23197999/149418158-205e63ef-8ff6-4c2f-a8f1-89e8c366b308.png)

It really need to have a documentation fixed

also, discord language need to be from config as it says "English" when reloading

**Comment by hrfee** [comment]
Yeah there's two URL Bases, sorry for the confusion. You can leave the one in general alone, just change the one in Settings > Invite Emails. The language selection should be fixed in the 25a1ca5, but you might have to re-select your language.

**Comment by hrfee** [comment]
Also renamed the "URL Base" in General to "Reverse proxy subfolder" to avoid confusion in 5acee68.

**Comment by RisedSky** [comment]
I disabled email verification as i'm linking the discord with the account
