### ISSUE TITLE
Unable to Authorize

### ISSUE THREAD

**Issue by pikachuyepyep** [hrfee/jfa-go#188]
Hi I am trying to authorize after getting everything installed via docker. But I keep getting this error

`
[INFO] 20:27:49  Auth failed with code 401 (Unauthorized, check credentials.)
[GIN] POST(/jellyfin/test) => 401
`

Not sure what to do from here. Thanks for any help.

**Comment by hrfee** [comment]
All i can think of this being is either a wrong username or password, or potentially the user has "Allow remote connections to this server" disabled and your Jellyfin isn't recognizing jfa-go as being on the local network. Could you make sure that setting is enabled? If not, re-creating the container with `-e DEBUG=1` in your docker  arguments might give a more detailed error.

**Comment by pikachuyepyep** [comment]
Thanks going to try adding Debug to the container. I have the correct permissions and I am able to access jfa-go on my local network so hopefully it shows something. will post back to let you know the findings.

**Comment by hrfee** [comment]
Really not sure what this could be. Could you try pulling up your jellyfin logs (with `docker logs -f` to follow them) and then pressing "Test" to see if there's anything outputted there?

**Comment by pikachuyepyep** [comment]
I actually continued to get the same error, But i figured out the issue. Super silly but it worked.. I was doing http://jellyfin.xxxxxxx.xyz and also tried jellyfin.xxxxxxxxx.xyz. What i had to do was put https://jellyfin.xxxxxxxxx.xyz
