### ISSUE TITLE
Failed to authenticate with Jellyfin @ http://jellyfin.local:8096: Code 401

### ISSUE THREAD

**Issue by Ishannaik** [hrfee/jfa-go#19]
jfa-go version: 0.2.2 (e35d057)
Socket: /tmp/jfa-go.sock
[ERROR] 16:04:31 main.go:458: Failed to authenticate with Jellyfin @ http://jellyfin.local:8096: Code 401

Linux/Ubuntu 20.04

It won't just start I have zero to none knowledge of Linux so could you help me step by step

**Comment by hrfee** [comment]
401 means "Unauthorized", so its probably an issue with your login details. Can you confirm that `username` and `password` in the `[jellyfin]` section of your `config.ini` file are correct and correspond to an actual user on Jellyfin? Also make sure `Disable this user` is not checked in the user settings on there.

**Comment by Ishannaik** [comment]
Ah sorry for responding late never got the notif and forgot about it, I've tried just deleting all the files and extracting it again but it's still the same also where can I find the config.ini file (I've already tried deleting and downloading it all again)

**Comment by hrfee** [comment]
The config file will be in `~/.config/jfa-go`.

**Comment by Ishannaik** [comment]
Thank you that worked, just wanted to ask how does password reset work by the way
