### ISSUE TITLE
[Feature Request] Send reset email

### ISSUE THREAD

**Issue by john-sp** [hrfee/jfa-go#190]
Add the possibility for reset email to be sent entirely by jfa-go. I was thinking of a button under Modify Settings on the Accounts tab. 

This would allow for us not to rely on either the server admins setting a password when they forget or trying to get users to actually use the reset page(it doesn't happen for my users 😭).

Hopefully this is easy to implement as you already can send the emails to reset passwords, now you are just giving server admins the ability to send this email without the end user using the reset page in Jellyfin.

LMK if any questions and thanks for your time!!

**Comment by hrfee** [comment]
this is already available in unstable builds, and will be included in 0.4.0 which hopefully will be out by the end of the week.

Sent from ProtonMail mobile

-------- Original Message --------
