### ISSUE TITLE
Feature - jfa-go user access

### ISSUE THREAD

**Issue by KeyboardDabbler** [hrfee/jfa-go#195]
I am testing out the new commit 6448a7db9e4e75954cee042d540d5b26ffa08cc3, allow user jfa-access. I am curious as to what direction this feature is heading, currently I do not quite understand the use case as it stands.

From general settings > enable "allow admin users only"
Create a basic test user in JF
then from jfa-go, accounts > tick "access jfa-go" on the test user.
Test user can now log into jfa-go and change all settings, along with deleting users. Basically a admin? I don't see the purpose of this because JF admin accounts have access anyway. 

If you are planning to add jfa-go "roles" which you already can update/ inherit from ombi, I suggest the below use case.

Give users a basic jfa-go role. They can intern login and view a users page (no access to settings or accounts;
- current status/ expiry displayed
- change pw ( which also updates ombi/ JF ect)
- key feature - Referral section, similar to torrent sites invite only. Admin can manually set x amount of allowed invites on a per user basis. User x has been assigned 1 referral from the admin. User x can generate an invitation and can forward this invite to a friend using a newly created invite code linked to user x account.

**Comment by hrfee** [comment]
Enabling "allow admin users only" just means that all Jellyfin admins can access jfa-go. I added this specifically because someone wanted non-admins to be able to have access, which I admit is a niche use case but it wasn't too much work.

I like the roles/referral idea though, i'll get on that soon.
