### ISSUE TITLE
NO_PUBKEY

### ISSUE THREAD

**Issue by Peekaboo1** [hrfee/jfa-go#196]
"https://apt.hrfee.dev trusty InRelease: The following signatures couldn't be verified because the public key is not available"

"The repository 'https://apt.hrfee.dev trusty InRelease' is not signed"

**Comment by hrfee** [comment]
Have you added the GPG key? You'll need to run this:
```shell
sudo apt-get update
sudo apt-get install curl apt-transport-https gnupg
curl https://apt.hrfee.dev/hrfee.pubkey.gpg | sudo apt-key add -
```
Then `apt-get update` and you should be able to install jfa-go.
