### ISSUE TITLE
Bug in Ombi Integration

### ISSUE THREAD

**Issue by alleyu2** [hrfee/jfa-go#197]
After integrating jfa-go with Ombi, my Ombi admin account gets locked out. After going through the Ombi database, I noted that my admin user name (allen) gets renamed to "Api" and becomes un-accessible.

jfa-go version: 0.4.0
Ombi version: 4.10.2

**Comment by hrfee** [comment]
I gave up on this issue and added warnings to the wiki and settings, and some recovery information. Jellyseerr integration has been added since as well, and it functions much better.
