### ISSUE TITLE
account expiry 

### ISSUE THREAD

**Issue by saivineeth28** [hrfee/jfa-go#198]
i am enable set expiry to accounts

**Comment by pfto1986** [comment]
Same here, after a user has expired I am unable to use the "Set expiry" function, and I get the next success message:

Success: Extended expiry for 0 users.

**Comment by dbz195** [comment]
Same keep getting the same message 
![Screenshot_20220627-235437_Samsung Internet](https://user-images.githubusercontent.com/43154188/176089041-87727a90-32fe-4616-baef-326507672256.jpg)

**Comment by dbz195** [comment]
Bump, same issue here

**Comment by aleksasiriski** [comment]
+1 for this issue...

**Comment by headii** [comment]
> 



> 



> Same keep getting the same message ![Screenshot_20220627-235437_Samsung Internet](https://user-images.githubusercontent.com/43154188/176089041-87727a90-32fe-4616-baef-326507672256.jpg)



> Same here, after a user has expired I am unable to use the "Set expiry" function, and I get the next success message:
> 
> Success: Extended expiry for 0 users.

+1

**Comment by gtxr23** [comment]
Same issue, if this feature worked it would actually be perfect

**Comment by aleksasiriski** [comment]
I sent a simple fix [PR](https://github.com/hrfee/jfa-go/pull/251) it should be merged soon!

For the time being you can disable the user and then when reenabling use setExpiry!

**Comment by hrfee** [comment]
the above is merged, hopefully this should work now on new builds, re-open if not.
