### ISSUE TITLE
SWAG Integration

### ISSUE THREAD

**Issue by dhbtfs** [hrfee/jfa-go#209]
Not really a bug but can you please provide SWAG integration config file. Thanks

**Comment by roib20** [comment]
I have submitted a pull request for the SWAG reverse-proxy-confs, hopefully it will get merged soon. In the meantime, anyone can manually copy my proxy confs from that PR.

Alternatively, if using [SWAG auto-proxy mod](https://github.com/linuxserver/docker-mods/tree/swag-auto-proxy) - these labels can be added to a jfa-go `docker-compose.yml` file:
```
    labels:
      - "swag=enable"
      - "swag_port=8056"
      - "swag_proto=http"
      - "swag_url=jfa-go.*"
```

**Comment by hrfee** [comment]
I'm not familiar with SWAG, @roib20 would you mind if I include a link to your PR in the wiki for now?

**Comment by roib20** [comment]
Yes it will be helpful to mention SWAG on [wiki.jfa-go.com/docs/reverse-proxy/](https://wiki.jfa-go.com/docs/reverse-proxy/)

However it will be easier to use jfa-go with SWAG once my PR for SWAG reverse-proxy-confs gets merged. How can I contribute to the wiki directly?

**Comment by hrfee** [comment]
Submit a PR on https://github.com/hrfee/jfa-go-wiki in `contents/docs/reverse-proxy.md`. It might be useful to install hugo to preview your changes, but it is just markdown so you can use anything to view it.
