### ISSUE TITLE
REQUEST FEATURES : compatible with emby 

### ISSUE THREAD

**Issue by Killianbe** [hrfee/jfa-go#21]
Hello,
since jellyfin uses the same base as emby, I think it must be possible to make jfago compatible with emby
Good luck

**Comment by Killianbe** [comment]
I've try to connect JFA-GO in emby docker : AND THAT WORK PERFECTLY

**Comment by Killianbe** [comment]
ok all work Except, saving passwords in emby, users created themselves fine, just they don't have any password

**Comment by Killianbe** [comment]
Last active don't work too
![image](https://user-images.githubusercontent.com/16178815/103483192-d87f4100-4de5-11eb-9d09-cca33bb293b5.png)

**Comment by hrfee** [comment]
Sorry I haven't replied, i've been busy working on a new ui for the app and revising for college. This looks doable since the APIs are still relatively similar, but if i add this i'll need to modularize the media server component of the app which might take a while.

**Comment by Killianbe** [comment]
Hello, yes I saw the improvement of the interface, nice working, I can not wait to test this x)
For emby i can wait no worries if i can do anything to help dont hesitate!

**Comment by hrfee** [comment]
ok, figured out the last active thing, and passwords dont work as emby doesn't allow you to specify a password when you create a user. I can work around this by creating the user and then setting the password once that's done. Any other problems you've found?

**Comment by Killianbe** [comment]
For the moment I haven't noticed any other problems

**Comment by hrfee** [comment]
Most things seem to be working, but i've decided i won't be changing all of the references to Jellyfin throughout the app's ui as it's a lot of work for a feature I don't think many will use. You can change the account creation form manually with a custom language file.

Also, does emby have password resets like jellyfin? It keeps saying 'Contact your administrator to reset your password' when i go into 'Forgot Password'.

**Comment by Killianbe** [comment]
To my knowledge I don't think there is a password reset.
I updated via unstable docker and the password still does not add

**Comment by hrfee** [comment]
I’ve put it in a separate branch so it hasn’t been built for docker. It
should be out by tomorrow.

**Comment by Killianbe** [comment]
ok thx man :)

**Comment by hrfee** [comment]
Merged in #28, releasing now as 0.2.7. You can choose emby in settings > jellyfin, and also there is an option to replace all occurrences of the word "Jellyfin" in the account creation form with something else, like "Emby".
