### ISSUE TITLE
nginx config  from wiki not working correctly

### ISSUE THREAD

**Issue by antoniozh** [hrfee/jfa-go#211]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**

When I try to use the config in the wiki my nginx will complain about the proxy_pass statement.

**To Reproduce**

Use the proxy_pass statement as is 

**Logs**

2022/05/02 15:49:13 [emerg] 45088#45088: "proxy_pass" cannot have URI part in location given by regular expression, or inside named location, or inside "if" statement, or inside "limit_except" block in /etc/nginx/conf.d/default.conf:128

**Comment by MrPotatoBobx** [comment]
it seems to work if you un-coment the rewrite line, comment the first proxypass, and un-comment the second, but then it throws a 404 error

**Comment by hrfee** [comment]
Hi, which config are you using? The Subdomain or Subfolder one?

**Comment by MrPotatoBobx** [comment]
subfolder, but i recently switched to subdomain

**Comment by hrfee** [comment]
Is the subfolder config working for you? If not try disregarding the wiki and just modifying another service's nginx file to work for jfa-go.

As for the subfolder method, the config given in the wiki is invalid for nginx and i'm not sure why no one (including me) hasn't noticed.  simply changing  `location ~ ^/accounts(.*)$` to `location ^~ /accounts` appears to fix it.
