### ISSUE TITLE
request add jellyseerr with or without ombi as well 

### ISSUE THREAD

**Issue by intertan** [hrfee/jfa-go#217]
its in the title, jellyseerr seems to be mostly focused on Jellyfin only

**Comment by BobDaGecko** [comment]
+1 While Jellyseerr has a way of signing in with imported or even new Jellyfin accounts, I'd love to see Jfa-Go support it as Jfa-Go would be able to add things like Discord and Emails to the accounts.

**Comment by hrfee** [comment]
As mentioned in #224, I might not continue working on this project but if I do this is on the list of features to add.

**Comment by aleksasiriski** [comment]
> As mentioned in #224, I might not continue working on this project but if I do this is on the list of features to add.

I'm planning on learning GO and would love to improve jfa-go. Will you accept PRs or should I fork it?

**Comment by aleksasiriski** [comment]
> +1 While Jellyseerr has a way of signing in with imported or even new Jellyfin accounts, I'd love to see Jfa-Go support it as Jfa-Go would be able to add things like Discord and Emails to the accounts.

I'm working on it now!

**Comment by Bgabor997** [comment]
any update on this by any chance?

**Comment by aleksasiriski** [comment]
I've been focused on other projects  mostly. I'll send a message here when I get around to redoing jfa-go

**Comment by KRDucky** [comment]
looking for Jellyseer support for sure. Ombi is rather limited unlike Jellyseer.

**Comment by aleksasiriski** [comment]
Sadly, I won't be working on this.. I ended up setting up LLDAP and Authelia and that works out better for me instead of using jfa-go

**Comment by hrfee** [comment]
#351 Adds jellyseerr support, let me know if it's satisfactory, should be up to a much higher standard than Ombi I hope.
