### ISSUE TITLE
Not delete user

### ISSUE THREAD

**Issue by xarmadigi** [hrfee/jfa-go#221]
Hi, jfa-go doesnt delete users...

log

[ERROR] 18:02:00 api.go:819: Account deletion failed: 500: <nil>
[GIN] GET(/invites) => 200
[GIN] GET(/users/announce) => 200
[GIN] GET(/invites) => 200
[GIN] GET(/users) => 200
[INFO] 18:02:17  Config requested
[GIN] GET(/config) => 200

any solution?

**Comment by smitty-exos** [comment]
I'm seeing the same thing. jfa-go in docker. I get this error message when I try to delete.

2022/08/31 13:43:06 [Recovery] 2022/08/31 - 13:43:06 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:221 (0x44d906)
	panicmem: panic(memoryError)
/usr/local/go/src/runtime/signal_unix.go:735 (0x44d8d6)
	sigpanic: panicmem()
/opt/build/ombi/ombi.go:62 (0xaaf0a0)
/opt/build/ombi/ombi.go:168 (0xab0628)
/opt/build/api.go:225 (0xb53f4f)
/opt/build/api.go:790 (0xb5b6ba)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0xb70c03)
/opt/build/auth.go:88 (0xb70b57)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x8e8841)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x8e882c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x8e7aa6)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/logger.go:241 (0x8e7a89)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x8e6ff0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0x8e6c58)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x8e6791)
/usr/local/go/src/net/http/server.go:2879 (0x6a631a)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1930 (0x6a19c7)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:1581 (0x46ac20)
	goexit: BYTE	$0x90	// NOP
[GIN] DELETE(/users) => 500
