### ISSUE TITLE
Add Overseerr support

### ISSUE THREAD

**Issue by Sim0nW0lf** [hrfee/jfa-go#224]
It looks like Overseerr will be coming to Jellyfin/Emby.
https://github.com/sct/overseerr/issues/288#issuecomment-1243148437

It would be really great to add support for it as alternative to Ombi since it seems to be really good as well and many probably would want to switch!

**Comment by hrfee** [comment]
It doesn't look like this has been finished yet, however there is a fork called Jellyseerr that works with Jellyfin. I'm not sure if i'll be continuing work on this project but if I do this'll be something I add given the Ombi integration is pretty broken.

**Comment by hrfee** [comment]
Jellyseerr support added in #351.
