### ISSUE TITLE
New users have permission to everything

### ISSUE THREAD

**Issue by Rikoblessedthis** [hrfee/jfa-go#225]
When a user creates an account using an invite link, it has access to everything. E.G all libraries and the option for media deletion etc. It's not an admin user, but has access to this.

Is there a way to filter the permissions that newly crated users by links have access to? E.G only certain basic libraries and options?

**Comment by gtxr23** [comment]
Make sure your not using an admin account as your template, as ive just tried an account via invite link and it has all the settings i chose and unable to delete, access certain libraries etc

**Comment by Rikoblessedthis** [comment]
Hi yes managed to figure it out, thank you! :)
