### ISSUE TITLE
POST returns 401 on /newUser while using invite link

### ISSUE THREAD

**Issue by Trey2k** [hrfee/jfa-go#226]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**

When siging up via the invite link after I click create account the button turns red with no text. Looking at the js console there is a POST 401 error on the /newUser endpoint.
I am able to create new users manually via jfa-go.

Describe the problem, and what you would expect if it isn't clear already.

The user is not created, expected user to be created.

**To Reproduce**

Use stable docker build.
Create a new invite link.
Signup with that link and press create account

What to do to reproduce the problem.

**Logs**

```
form.js:1          GET https://jfa.DOMAIN.com/invite/sM5tcYDQHiCNCTebeSqrib/discord/invite 500
c @ form.js:1
(anonymous) @ form.js:1
(anonymous) @ form.js:3
6The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
form.js:1          POST https://jfa.DOMAIN.com/newUser 401
L @ form.js:1
K @ form.js:3
```

**If you're using a build with a tray icon, right-click on it and press "Open logs" to access your logs.**

When you notice the problem, check the output of `jfa-go` or get the logs by pressing the "Logs" button in the Settings tab. If the problem is not obvious (e.g a panic (red text) or 'ERROR' log), re-run jfa-go with the `-debug` argument and reproduce the problem. You should then take a screenshot of the output, or paste it here, preferably between \`\`\` tags (e.g \`\`\``Log here`\`\`\`). Remember to censor any personal information.

If nothing catches your eye in the log, access the admin page via your browser, go into the console (Right click > Inspect Element > Console), refresh, reproduce the problem then paste the output here in the same way as above.

**Configuration**

If you see it as necessary, include relevant sections of your `config.ini`, for example, include `[email]` and `[smtp]|[mailgun]` if you have an email issue.

**Platform/Version**
Docker:Stable

Include the platform jfa-go is running on (e.g Windows, Linux, Docker), the version (first line of output by `jfa-go` or Settings>About in web UI), and if necessary the browser version and platform.

**Comment by hrfee** [comment]
Could you attempt this again while monitoring jfa-go's logs with `docker logs -f <your container name>`? You should see some relevant information on why its failing, send it here if there is.

**Comment by Trey2k** [comment]
My apologies I have already moved to another system to handle sign ups and as such no longer have jfa-go running. If no one is able to reproduce it I can get it set back up when I have some time.
