### ISSUE TITLE
Failed to authenticate with Jellyfin

### ISSUE THREAD

**Issue by Rainerr123** [hrfee/jfa-go#229]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**

Describe the problem, and what you would expect if it isn't clear already.

Im creating the docker image with:

docker create \
--name "jfa-go" \
-p 8056:8056 \
-v jfa-go-config:/data \
-v /var/lib/docker/volumes/media-stack_jellyfin-config/_data:/jf \
-v /etc/localtime:/etc/localtime:ro \
hrfee/jfa-go:latest

I've tried the fix in #16 

**To Reproduce**

Create docker image and configure with local ip

**Logs**

jfa-go version: 0.4.0 (c6fc576)

Socket: /tmp/jfa-go.sock

2022/10/27 11:07:19 Using external storage

[INFO] 11:07:19  Copied default configuration to "/data/config.ini"

[INFO] 11:07:20  Initializing router

[INFO] 11:07:20  Loading routes

[INFO] 11:07:20  Loading setup @ 0.0.0.0:8056

[INFO] 11:07:20  Loaded, visit 0.0.0.0:8056 to start.

[GIN] GET(/) => 200

[GIN] GET(/lang/form) => 200

[GIN] GET(/lang/admin) => 200

[GIN] GET(/lang/email) => 200

[GIN] GET(/lang/pwr) => 200

[GIN] GET(/lang/setup) => 200

[INFO] 11:08:56  Auth failed with code 0 (Post "http://192.168.0.83:8096/Users/authenticatebyname": context deadline exceeded (Client.Timeout exceeded while awaiting headers))

[GIN] POST(/jellyfin/test) => 200

[INFO] 11:09:57  Config modification requested

[INFO] 11:09:57  Restarting...

[ERROR] 11:09:57 main.go:572: Failure serving: http: Server closed

[GIN] POST(/config) => 200

jfa-go version: 0.4.0 (c6fc576)

[INFO] 11:09:57  Using Jellyfin server type

main.go:436: Failed to authenticate with Jellyfin @ "http://192.168.0.83:8096" (0): Post "http://192.168.0.83:8096/Users/authenticatebyname": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Configuration**

If you see it as necessary, include relevant sections of your `config.ini`, for example, include `[email]` and `[smtp]|[mailgun]` if you have an email issue.

**Platform/Version**
Using Docker

**Comment by hrfee** [comment]
This means that Jellyfin is taking too long to respond to the authentication request. Theres probably something about it in the Jellyfin logs, if you're using docker for that as well could you monitor its logs with `docker logs -f <your jellyfin container name>`, and see what's output when you try to run jfa-go?
