### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by Killianbe** [hrfee/jfa-go#23]
![image](https://user-images.githubusercontent.com/16178815/103707772-90137f00-4faf-11eb-9aba-34bc65c196c8.png)

Hello!

Really nice work done on the web! well done!
2 small questions, one what is the purple bar for?
Can the red crosses be updated in green as soon as the password meets the characteristics, a status in real time?

Thanks man :) !

**Comment by rigrig** [comment]
For me the purple bar shows the contact message (Settings -> General: "Contact message")

**Comment by hrfee** [comment]
Yeah, it shows the contact message. I'll have it hide if there isn't one. I'll do the automatic requirement updates too.

**Comment by hrfee** [comment]
Contact box is hidden if empty in 6860933.

**Comment by hrfee** [comment]
live validation added in 4aae655.
