### ISSUE TITLE
Where is the password reset link indented to be?

### ISSUE THREAD

**Issue by redmetablue** [hrfee/jfa-go#240]
I can't tell if I'm blind or have something misconfigured. Where is the password reset link intended to be? I'm not seeing it located on the sign in window where I would assume.

**Comment by aleksasiriski** [comment]
Forgot password on Jellyfin login page, jfa-go reads the file created by jellyfin and then sends the appropriate email.

**Comment by Rezer** [comment]
The built-in Jellyfin "Forgot password" button doesn't work for anybody outside the local network without convincing Jellyfin that every user is on the local network...which causes its own problems.  Plus the built in button doesn't say anything about checking your email, it's a bit janky.

My workaround is to enter the following on the Jellyfin server General settings page:

Login disclaimer:
```
<p style="color: #A0A0A0; margin-top: -15px;">
<a href="https://your-jfa-go.server/my/account">Forgot password?</a><br />
(Only works if you previously set an email address)</p>
```

Custom css code:
```
#loginPage .raised.cancel.block.btnForgotPassword.emby-button {

  display: none;

}
```

The end result is a hidden Jellyfin "Forgot password" button and a link to the jfa-go "Forgot password" page.  Works for everybody regardless of how your Jellyfin networking is configured, as far as I can tell.  Could put in more work to make the link look more like the other buttons, but...I didn't see much need.

**Comment by hrfee** [comment]
Closing but i'll add link to the above comment on the wiki, it looks quite helpful.
