### ISSUE TITLE
Bug/Suggestion: Success Page improvements

### ISSUE THREAD

**Issue by robocrax** [hrfee/jfa-go#242]
v0.4.0 on Docker

Here's a weird one.

https://github.com/hrfee/jfa-go/blob/main/html/create-success.html

For some reason the CSS on the success page is not rendered and the page looks like this

![Current snip](https://user-images.githubusercontent.com/12411330/213558999-1f55a534-ef68-4fd4-a500-07f37dc47fb6.png)

Instead of 

![After CSS versioning added](https://user-images.githubusercontent.com/12411330/213559020-edbb6f37-4056-42b9-b36d-1a9bdef4564e.png)

Which I think is due to the {{ .cssVersion }} variable not being rendered for some reason.

This is what gets sent to the browser currently:

![Missing v3bundle css](https://user-images.githubusercontent.com/12411330/213559306-4b5ef4a2-fd3a-40ba-ac44-4064a8e2acc5.png)

This is a minor bug and doesn't affect functionality but I thought I would add my own suggestion to this.

I would like to use my own success page and was wondering if an automatic redirect could be setup to this page, skipping the part to click on the continue button.

![Alternative advanced setting in admin to re-direct](https://user-images.githubusercontent.com/12411330/213563665-96070801-eeaf-4995-abdf-a02868257942.png)

**Comment by hrfee** [comment]
thanks for letting me know and doing half the work for me, fixed now and an unstable build should be done soon. I like the redirect idea so i'll add that soon too.

**Comment by hrfee** [comment]
The setting is done and is called "Auto redirect on success", it's in the same place you put yours.
