### ISSUE TITLE
Add PHP support

### ISSUE THREAD

**Issue by Gujjugaming2k** [hrfee/jfa-go#250]
Please make PHP support app most of users don't have VPS or dedicated server with root access so Please build for php also

**Comment by hrfee** [comment]
I don't know PHP nor would I rewrite this whole app in another language, also you don't necessarily need root access to run jfa-go, you would to use docker but a normal build should work fine.

**Comment by hrfee** [comment]
I just saw your other issue #246, i can try help you get jfa-go running over there.
