### ISSUE TITLE
Expiry

### ISSUE THREAD

**Issue by pcmodder2001** [hrfee/jfa-go#261]
Hiya, 

I'm trying to set expiry for some users. and when i have 2+ selected it lets me do the steps (set expiry - set the dates and submit) but the system then says expiry set for 0 users and the expiry does not update on the account list. 

does anyone have this issue? 

I'm running on windows currently but i also had the same issue on Docker. (wasn't a problem for me before but it is now as this is a feature i need")

any help much appreciated :)

**Comment by marcofrias** [comment]
Same here, setting expiration to existing users si not working.

**Comment by dj4shots** [comment]
+1

**Comment by xZeroCool277** [comment]
I have it too

**Comment by hrfee** [comment]
don't think this should be an issue anymore, as setting expiries has been reworked.
