### ISSUE TITLE
Gtk-WARNING **: 14:29:25.833: cannot open display: :0

### ISSUE THREAD

**Issue by mdshahinneel9** [hrfee/jfa-go#266]
2023/04/04 14:29:25 Logging to "/tmp/jfa-go.log"
2023/04/04 14:29:25 Using internal storage
jfa-go version: 0.4.0 (c6fc576) TrayIcon

Socket: /tmp/jfa-go.sock

(jfa-go:14169): Gtk-WARNING **: 14:29:25.833: cannot open display: :0

**Comment by hrfee** [comment]
are you running jfa-go in a graphical environment? if not, try the non-trayIcon package.
