### ISSUE TITLE
No redirection with the "continue" button

### ISSUE THREAD

**Issue by Cornichon420** [hrfee/jfa-go#27]
Following a successful new account creation, the continue button has no redirection.
I setup my "public address" setting : https://jellyfin.mydomain (i also tried to my organizr : https://organizr.mydomain)
(initially it was "https://jellyf.in:443")

**Configuration**

My "Public address" setting is correctly reported in my config.ini

**Platform/Version**

Jfa-go 0.2.5
Docker Swarm
Traefik

**Comment by hrfee** [comment]
Someone had this issue yesterday, I've already fixed it but hadn't released a new version. v0.2.6 with the fix is building now, should be out in the next 10 minutes.
