### ISSUE TITLE
Expired key on apt.hrfee.dev

### ISSUE THREAD

**Issue by c9rnelius** [hrfee/jfa-go#271]
"**Describe the bug**

The public key of your apt repository has expired on 24.05.2023.

**To Reproduce**

- Follow the instructions on https://apt.hrfee.dev/ to add the repository
- execute `sudo apt-get update`

**Logs**
```
Get:9 https://apt.hrfee.dev trusty InRelease [3,234 B]
Err:9 https://apt.hrfee.dev trusty InRelease
The following signatures were invalid: EXPKEYSIG E8D453F3D40BDEBF Harvey Tindall (Packaging) <hrfee@hrfee.dev>
W: GPG error: https://apt.hrfee.dev trusty InRelease: The following signatures were invalid: EXPKEYSIG E8D453F3D40BDEBF Harvey Tindall (Packaging) <hrfee@hrfee.dev>
E: The repository 'https://apt.hrfee.dev trusty InRelease' is not signed.
``` 

**Platform/Version**

Debian 11 "bullseye"

**Comment by hrfee** [comment]
Just updated it as well as the instructions to not use the now-deprecated apt-key, give it a go again.
-------- Original Message --------

**Comment by c9rnelius** [comment]
Thanks for the quick fix!
