### ISSUE TITLE
Unable to create accounts using the latest nightly build

### ISSUE THREAD

**Issue by Darth4212** [hrfee/jfa-go#275]
Unable to actually create accounts with the latest nightly build

**To Reproduce**

Change over from the latest stable version to the latest nightly build on buildrone 

**Logs**

[DEBUG] 15:26:08 auth.go:121: Auth succeeded
[DEBUG] 15:26:08 api-invites.go:128: Generating new invite
[GIN/DEBUG] 15:26:08: POST(/jfago/invites) => 200 in 506.9µs; 
[DEBUG] 15:26:08 auth.go:121: Auth succeeded
[DEBUG] 15:26:08 api-invites.go:220: Invites requested
[GIN/DEBUG] 15:26:08: GET(/jfago/invites) => 200 in 508.1µs; 
[GIN/DEBUG] 15:26:08: GET(/jfago/fonts/hanken-grotesk-v8-cyrillic-ext_latin_vietnamese-500italic.woff2) => 200 in 544.8µs; 
[GIN/DEBUG] 15:26:09: GET(/jfago/invite/PCGb8qB2MnJa9YZkj9N9W) => 200 in 522.7µs; 
[GIN/DEBUG] 15:26:09: GET(/jfago/css/v3bundle.css) => 200 in 1.0519ms; 
[GIN/DEBUG] 15:26:09: GET(/jfago/css/remixicon.css) => 200 in 524.8µs; 
[GIN/DEBUG] 15:26:09: GET(/jfago/invite/js/form.js) => 200 in 505.3µs; 
[GIN/DEBUG] 15:26:09: GET(/jfago/invite/css/v3bundle.css) => 200 in 505.3µs; 
[GIN/DEBUG] 15:26:09: GET(/jfago/invite/fonts/hanken-grotesk-v8-cyrillic-ext_latin_vietnamese-700.woff2) => 200 in 0s; 
[GIN/DEBUG] 15:26:09: GET(/jfago/invite/fonts/hanken-grotesk-v8-cyrillic-ext_latin_vietnamese-regular.woff2) => 200 in 0s; 
[GIN/DEBUG] 15:26:09: GET(/jfago/invite/fonts/hanken-grotesk-v8-cyrillic-ext_latin_vietnamese-500.woff2) => 200 in 0s; 
[GIN/DEBUG] 15:26:09: GET(/jfago/invite/css/remixicon.woff2?t=1684338274817) => 200 in 520.9µs; 
[GIN/DEBUG] 15:26:10: GET(/jfago/site.webmanifest) => 200 in 0s; 
[GIN/DEBUG] 15:26:21: GET(/jfago/invite/PCGb8qB2MnJa9YZkj9N9W) => 200 in 1.3728ms; 
[GIN/DEBUG] 15:26:22: GET(/jfago/css/v3bundle.css) => 200 in 1.0443ms; 
[GIN/DEBUG] 15:26:22: GET(/jfago/css/remixicon.css) => 200 in 547.6µs; 
[GIN/DEBUG] 15:26:22: GET(/jfago/invite/js/form.js) => 200 in 0s; 
[GIN/DEBUG] 15:26:22: GET(/jfago/invite/css/v3bundle.css) => 200 in 505.8µs; 
[GIN/DEBUG] 15:26:22: GET(/jfago/invite/fonts/hanken-grotesk-v8-cyrillic-ext_latin_vietnamese-700.woff2) => 200 in 0s; 
[GIN/DEBUG] 15:26:22: GET(/jfago/invite/fonts/hanken-grotesk-v8-cyrillic-ext_latin_vietnamese-500.woff2) => 200 in 0s; 
[GIN/DEBUG] 15:26:22: GET(/jfago/invite/fonts/hanken-grotesk-v8-cyrillic-ext_latin_vietnamese-regular.woff2) => 200 in 0s; 
[GIN/DEBUG] 15:26:22: GET(/jfago/invite/css/remixicon.woff2?t=1684338274817) => 200 in 514.7µs; 
[GIN/DEBUG] 15:26:22: GET(/jfago/site.webmanifest) => 200 in 0s; 
[DEBUG] 15:26:57 daemon.go:79: Housekeeping: Checking for expired invites
[DEBUG] 15:27:57 daemon.go:79: Housekeeping: Checking for expired invites

**BROWSER CONSOLE OUTPUT**

rm.js:1 Uncaught TypeError: Cannot set properties of null (setting 'onchange')
    at q (form.js:1:5668)
    at form.js:3:2224
    at form.js:5:1995
q @ form.js:1
(anonymous) @ form.js:3
(anonymous) @ form.js:5
recaptcha__en.js:104 Uncaught (in promise) Error: reCAPTCHA placeholder element must be an element or id
    at recaptcha__en.js:104:375
    at reCAPTCHACallback (PCGb8qB2MnJa9YZkj9N9W:155:20)
(anonymous) @ recaptcha__en.js:104
reCAPTCHACallback @ PCGb8qB2MnJa9YZkj9N9W:155
Promise.then (async)
(anonymous) @ recaptcha__en.js:423
z.window.<computed>.<computed>.z.window.<computed>.<computed> @ recaptcha__en.js:448
(anonymous) @ recaptcha__en.js:449
(anonymous) @ recaptcha__en.js:286
(anonymous) @ recaptcha__en.js:448
(anonymous) @ recaptcha__en.js:882
(anonymous) @ recaptcha__en.js:888
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
PCGb8qB2MnJa9YZkj9N9W:1 The resource https://my.site/jfago/css/remixicon.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
PCGb8qB2MnJa9YZkj9N9W:1 The resource https://my.site/jfago/css/v3bundle.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Platform/Version**

The latest nightly build as of this bug report 46f1bc2 for Windows 11 Pro Edition

**Comment by hrfee** [comment]
Have you enabled the reCAPTCHA feature in settings? your browser logs indicate so. Also, your console logs don't show any POST requests, so unless theres stuff missing, you weren't able to submit the form. What happens when you try to submit it?

**Comment by hrfee** [comment]
Also, i just released a new build, which changes it so helpful debugging information is included in unstable builds. Would you mind updating to it and seeing if you get new info in your logs, specifically the browser ones?

**Comment by Darth4212** [comment]
> Have you enabled the reCAPTCHA feature in settings? your browser logs indicate so. Also, your console logs don't show any POST requests, so unless theres stuff missing, you weren't able to submit the form. What happens when you try to submit it?

Okay after updating it now shows what the actual issue is for some reason my recaptcha is not working even though it gives the green check and everything. I think it may be how my stuff is setup? I am running jfa-go under a subdirectory of my site ie
```https://my.site.net``` is the JF server
```https://my.site.net/jfago``` is jfa-go's subdirectory

**Comment by Darth4212** [comment]
Although I will recommend making where you cannot add a scheme on the reCAPTCHA settings of jfa-go because that simply isn't supported through Google reCAPTCHA

**Comment by Darth4212** [comment]
It was just odd essentially before you pushed out the build I would get no information regarding what was going on through logs or ui but you adding the debugging seemed to fix them both? Just an idea I was throwing out since it really is a simple mistake
