### ISSUE TITLE
JFA doesn't start up automatically after a reboot

### ISSUE THREAD

**Issue by xarmadigi** [hrfee/jfa-go#285]
I'm trying to get jfa to run automatically when the server restarts. I've created a systemd service and a script that calls it, but it's not working. Has anyone else had success with this?

#!/bin/bash

if [ ! -f /usr/local/bin/jfa-go ]; then
  echo "El binario jfa-go no existe en la ruta /usr/local/bin/jfa-go"
  exit 1
fi

echo "Ejecutando jfa-go start"
/usr/local/bin/jfa-go start

---------------------------------------------
service

[Unit]
Description=An account management system for Jellyfin.

[Service]
ExecStart=/usr/local/bin/jfa-go start

[Install]
WantedBy=default.target

**Comment by hrfee** [comment]
Don't use the `jfa-go start` command, it's a bit of an afterthought, and unnecessary. Just run `jfa-go systemd`, it'll generate a `jfa-go.service` file in the directory you run it in.
