### ISSUE TITLE
Username as an option

### ISSUE THREAD

**Issue by Bgabor997** [hrfee/jfa-go#287]
Possibility to add username on registration / user creation, and import user to Jellyfin / Emby with username if provided, if not then keep e-mail, would be nice to know who is the user in jellyfin, since labels only visible in jfa-go.

If someone is using the Jellyfin db as an authentication for all service (Jellyseerr + Jellyfin + Organizer + jfa-go) it would help a lot with user management.

Thank you for your work <3

**Comment by deejayexe** [comment]
Yes, I have been testing jfa-go and I would also like to have the option to use the user field with a username and not just the email in my case to be able to import users from plex directly with their username and not the email
Maybe this option can be implemented 😉

**Comment by hrfee** [comment]
Sorry, i don't quite understand. jfa-go already asks for a username, asking for an email and using it in place of a username are configurable options already. Are you asking to make username an optional field (i.e. Use email as username only if an alternate username isn't provided)?

**Comment by Bgabor997** [comment]
Sorry, my issue is about when a user registers from an invite link, he can give username, but in Jellyfin / Jellyseerr i can see the user with his/her email address, and sometimes i can't indentify the user from email. In my case i want to transfer the user's username to Jellyfin when its created.

**Comment by hrfee** [comment]
Weird, that's meant to be the default behaviour. Do you have the "Use email address as username" option enabled?

**Comment by Bgabor997** [comment]
Well, i would like to close the issue and apologize. o.o Its my bad, didn't notice this option.
