### ISSUE TITLE
Request to hide the background on login page.

### ISSUE THREAD

**Issue by devanteweary** [hrfee/jfa-go#288]
Hey it's so awesome to have an update after all this time and great job on this project.

It really is a game changer!!

I'm just writing to request to make the login page background blank (or custom color) rather than showing all the jfa-go fields dimmed with the login box over it.

Thank you!

Here is the current and then proposed change.

**Current**
![login-current](https://github.com/hrfee/jfa-go/assets/29805497/4b1802a8-54c3-4f7b-9817-f54588429b41)

**Proposed**
![login-proposed](https://github.com/hrfee/jfa-go/assets/29805497/a25d1ad1-a2b9-469b-8cb1-83a54cbaa72a)

**Comment by J03lYuK** [comment]
I agree with this comment, Please dev when you get time to fix this issue. Thank you.

**Comment by hrfee** [comment]
Added in the above commit. You can find the "Login screen Appearance" setting in "General".

**Comment by devanteweary** [comment]
> Added in the above commit. You can find the "Login screen Appearance" setting in "General".

Heck yeah awesome!!! (sorry I know this is 2 weeks late).
 You're the best!

I'll keep an eye out for the release. Thank you!

**Comment by devanteweary** [comment]
> Added in the above commit. You can find the "Login screen Appearance" setting in "General".

Heck yeah awesome!!! (sorry I know this is 2 weeks late).
 You're the best!

I'll keep an eye out for the release. Thank you!

**Comment by devanteweary** [comment]
> Added in the above commit. You can find the "Login screen Appearance" setting in "General".

Hey. :>

Just wondering.... I'm on version 0.5.0 (commit 084a62e, using an Unraid Docker container) and I can't seem to find this option anywhere.
I don't see anything to do with the login page under General.

Please help sensei!

**Comment by hrfee** [comment]
Switch to the unstable for now, 5.1 will be done pretty soon then you can switch back.

-------- Original Message --------

**Comment by devanteweary** [comment]
Awesome thank you for adding it!!
