### ISSUE TITLE
Navigation to "My Account" page doesn't respect reverse proxy subfolder

### ISSUE THREAD

**Issue by cmbarba** [hrfee/jfa-go#289]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**

Navigating to the "My Account" page while a reverse proxy subfolder is set brings me to a blank page. Manually adding the subfolder to the url takes me the correct login page and, past that, the account page.

**To Reproduce**

Have a reverse proxy redirecting urls and navigate to "My Account" page with reverse proxy subfolder set.

**Logs**

Nothing new appears in the logs when navigating to the blank page.

**Platform/Version**

Docker
jfa-go Version 0.5.0

**Comment by xBelladonna** [comment]
I can confirm this is happening to me as well. Currently working around it witb ngx_http_sub_module. See docs here: https://nginx.org/en/docs/http/ngx_http_sub_module.html

You can put this snippet in your nginx config file and it should do the job:
```
# Substitude any invalid/missing basename for the real one
sub_filter "/my/account" "/accounts/my/account";
```

**Comment by cmbarba** [comment]
> I can confirm this is happening to me as well. Currently working around it witb ngx_http_sub_module. See docs here: https://nginx.org/en/docs/http/ngx_http_sub_module.html
> 
> You can put this snippet in your nginx config file and it should do the job:
> 
> ```
> # Substitude any invalid/missing basename for the real one
> sub_filter "/my/account" "/accounts/my/account";
> ```

Thanks for this. I was unable to use it because I run Traefik, but it gave me enough of a hint to figure out my own configuration for the workaround:

### Static configuration (traefik.yml):
```
experimental:
  plugins:
    subfilter:
      moduleName: "github.com/chahn/subfilter"
      version: "v0.1.4" 
```

### Dynamic configuration (docker compose labels):
```
labels:
  - "traefik.enable=true"
  - "traefik.http.routers.jfa-go.rule=Host(`example.com`) && PathPrefix(`/accounts`)"
  - "traefik.http.middlewares.jfa-go-subfilter.plugin.subfilter.replacements.pattern=/my/account"
  - "traefik.http.middlewares.jfa-go-subfilter.plugin.subfilter.replacements.replacement=/accounts/my/account"
  - "traefik.http.routers.jfa-go.middlewares=jfa-go-subfilter@docker"
```

**Comment by Killianbe** [comment]
Same prob here

**Comment by dinosmm** [comment]
I get a "Page Not Found" when navigating to "My Account" using the button on the top right. Is this the same issue? How can I change my password or even log off?

I tried to add that snipped in my nginx config but it didn't help, it just goes to domain/accounts/my/account and still shows me the 'Page Not Found' page.

**Comment by cmbarba** [comment]
> I get a "Page Not Found" when navigating to "My Account" using the button on the top right. Is this the same issue?
> 
> I tried to add that snipped in my nginx config but it didn't help, it just goes to domain/accounts/my/account and still shows me the 'Page Not Found' page.

Have you set "accounts" as your reverse proxy subfolder under General settings?

**Comment by dinosmm** [comment]
Never mind, all my fault, I didn't read the documentation properly to see that the My Account button only works with Jellyfin authentication. I switched to that and now it works fine. Sorry!!
