### ISSUE TITLE
Unable to run jfa-go

### ISSUE THREAD

**Issue by BobDaGecko** [hrfee/jfa-go#29]
### Describe the bug

Can't run jfa-go with the latest release, get an error

### To Reproduce

On fresh install, run `jfa-go`

### Logs

Error output: `-bash: /usr/bin/jfa-go: cannot execute binary file: Exec format error`

### Configuration

None, cannot get to web interface

### Platform/Version

Linux v0.2.7

**Comment by hrfee** [comment]
This likely means the architecture/os is incorrect. What is the output of the command `uname -m`, and which file did you download from releases?

**Comment by BobDaGecko** [comment]
I totally did. Downloaded ARM not x86. Resolved.
