### ISSUE TITLE
Invite emails

### ISSUE THREAD

**Issue by KeyboardDabbler** [hrfee/jfa-go#3]
I can not get the "Invite emails" feature to work. I have setup smtp to connect with my gmail. At first i tried ssl_tsl but i was receiving a "failed to send error".
Changing the port and method to "starttls" cleared the error but i am not receiving any invitation email. 

`
[INFO] 08:47:36 Token requested (login attempt)
[GIN] GET(/getToken) => 200
[GIN] GET(/getInvites) => 200
[INFO] 08:48:35 ******************: Sent invite email to example@gmail.com
[GIN] POST(/generateInvite) => 200
[GIN] GET(/getInvites) => 200

`

Also no path is undefined when attempting to "reset pw"
![pwreset](https://user-images.githubusercontent.com/53971316/93005103-d6c50f80-f5a1-11ea-8324-e98d7ed4c623.PNG)

**Comment by hrfee** [comment]
your [smtp] section should look like this:
```
encryption = ssl_tls
server = smtp.gmail.com
port = 465
password = <password>
```

If you use 2FA on your google account, you'll need to create an App Password [here](https://myaccount.google.com/apppasswords), and use that as the password. If it still isn't working, run jfa-go with `-debug`, try again and post the log.

**Comment by hrfee** [comment]
Also, the path shows as `undefined` for me as well, but works anyway.

**Comment by KeyboardDabbler** [comment]
I am not using 2FA on this account.

The pw that i have set is correct for the email address that i set in "Sent from (address)"
`
[GIN/DEBUG] 10:20:36: GET(/favicon-32x32.png) => 200 in 3.906194ms;
[INFO] 10:20:42 Token requested (login attempt)
[DEBUG] 10:20:42 auth.go:171: Token generated for user "jfago"
[GIN/DEBUG] 10:20:42: GET(/getToken) => 200 in 32.309878ms;
[DEBUG] 10:20:42 auth.go:102: Auth succeeded
[DEBUG] 10:20:42 api.go:324: Invites requested
[GIN/DEBUG] 10:20:42: GET(/getInvites) => 200 in 139.862µs;
[DEBUG] 10:20:56 auth.go:102: Auth succeeded
[DEBUG] 10:20:56 api.go:284: Generating new invite
[DEBUG] 10:20:56 api.go:304: ***************************: Sending invite email
[ERROR] 10:20:58 api.go:312: ***************************: Failed to send to example@gmail.com
[DEBUG] 10:20:58 api.go:313: ***************************: Error: 535 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials z1sm1513051pfq.102 - gsmtp
[GIN/DEBUG] 10:20:58: POST(/generateInvite) => 200 in 1.709408086s;
[DEBUG] 10:20:58 auth.go:102: Auth succeeded
[DEBUG] 10:20:58 api.go:324: Invites requested
[GIN/DEBUG] 10:20:58: GET(/getInvites) => 200 in 511.588µs;
[DEBUG] 10:21:04 daemon.go:37: Daemon: Checking invites

`

**Comment by KeyboardDabbler** [comment]
I am not getting the error when setting `starttls` but i am also not receiving the invite. 

```
[INFO] 18:43:09 Config modification requested
[DEBUG] 18:43:09 api.go:635: Config saved
[GIN/DEBUG] 18:43:09: POST(/modifyConfig) => 200 in 1.42186ms;
[DEBUG] 18:43:21 auth.go:102: Auth succeeded
[DEBUG] 18:43:21 api.go:284: Generating new invite
[DEBUG] 18:43:21 api.go:304: ********************: Sending invite email
[INFO] 18:43:25 ********************: Sent invite email to example@gmail.com
[GIN/DEBUG] 18:43:25: POST(/generateInvite) => 200 in 3.273142164s;
[DEBUG] 18:43:25 auth.go:102: Auth succeeded
[DEBUG] 18:43:25 api.go:324: Invites requested
[GIN/DEBUG] 18:43:25: GET(/getInvites) => 200 in 437.049µs;
```

**Comment by hrfee** [comment]
When i tried with 2FA turned off, i got a security alert in my email from google which asked me to confirm it was me trying to sign in. After accepting, it worked. Did you receive a similar email? Also, ssl_tls is the correct option as google has disabled starttls.

**Comment by hrfee** [comment]
Do you happen to be running jfa-go in docker with a VPN on Windows? Someone had the same issue and that ended up being the problem.

**Comment by KeyboardDabbler** [comment]
This can now be closed. After you mentioned a VPN i recall setting up i filter on my pfSense box recently which was the issue.

Thankyou for the help, jfa-go is a great addition to my JF environment.

**Comment by hrfee** [comment]
No problem, will put something about VPNs in the FAQ if i haven't already.
