### ISSUE TITLE
Cannot send emails

### ISSUE THREAD

**Issue by BobDaGecko** [hrfee/jfa-go#30]
### Describe the bug

Emails fail to send

### To Reproduce

1. Configure SMTP
2. Send invite

### Logs

```
[DEBUG] 12:45:51 api.go:487: Generating new invite
[DEBUG] 12:45:51 api.go:513: kBQJ9nEqYkmX6XZL7wth8n: Sending invite email
smtp.gmail.com:465
[ERROR] 12:45:52 api.go:522: kBQJ9nEqYkmX6XZL7wth8n: Failed to send to bobdageckobusiness@gmail.com
[DEBUG] 12:45:52 api.go:523: kBQJ9nEqYkmX6XZL7wth8n: Error: 534 5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbv
5.7.14 cpOxZA4Xp5FTmcIhCYBGFcoV98-NZ5cAxBcX_Sa13eoSGf0_2mV_1HSgniJ4Ob0HwdcAf
5.7.14 dHkwVoJVrQPlDTYp6KsLJBh_JO6DVNcsGcObk0t9yxXFbidzQaEGrLUQPlgeN5I0>
5.7.14 Please log in via your web browser and then try again.
5.7.14  Learn more at
5.7.14  https://support.google.com/mail/answer/78754 r23sm185553ejd.56 - gsmtp
```

### Configuration

Email method: SMTP
Sent from (address): example@gmail.com
Sent from (name): Jellyfin
Username: n/a
Encryption Method: ssl_tls
Server address: smtp.gmail.com
Port: 465
Password: ************

### Platform/Version

Linux v0.2.7

**Comment by hrfee** [comment]
Have you tried visiting that link and then trying again?

**Comment by BobDaGecko** [comment]
I did that but it still doesn't work. It's running on a remote server though. Would I have to somehow login there?

**Comment by hrfee** [comment]
I don't think that would make a difference, the fingerprint of the server is likely included in the link. After doing it do you get the same error or something different?

**Comment by BobDaGecko** [comment]
Nope, get the same thing just with a new link.

**Comment by hrfee** [comment]
Try enabling less secure app access in your google settings [here](https://www.google.com/settings/security/lesssecureapps).

**Comment by BobDaGecko** [comment]
It's already on unfortunately.

**Comment by hrfee** [comment]
Do you have 2FA on? try using an app password ([google settings](https://myaccount.google.com/security) > security > app passwords). If not, apparently logging in [here](https://www.google.com/accounts/DisplayUnlockCaptcha) will allow the next login attempt to succeed.

**Comment by BobDaGecko** [comment]
Huh, that seems to have worked. Granted the email went to spam but it must of been that captcha link. Thanks, really appreciate it.

**Comment by BobDaGecko** [comment]
Before I close this, all the invites I have done are still showing up even though I deleted them. It seems after persistently deleting them they go away but it's weird behavior.

**Comment by hrfee** [comment]
Weird. Could you enable debug output with the `-debug` flag and then try to delete an invite? The command line output should look like this:
```
[DEBUG] 20:28:12 auth.go:89: Auth succeeded
[DEBUG] 20:28:12 api.go:825: JWwdY7TurJVhjh5KUWHe2D: Deletion requested
[INFO] 20:28:12 JWwdY7TurJVhjh5KUWHe2D: Invite deleted
[GIN/DEBUG] 20:28:12: DELETE(/invites) => 200 in 496.235µs; 
```

**Comment by BobDaGecko** [comment]
They're gone now, couldn't seem to find the log data for what happened.
