### ISSUE TITLE
0.5.0 jfa crashing upon first failure to find jellyfin

### ISSUE THREAD

**Issue by ohitstom** [hrfee/jfa-go#305]
![image](https://github.com/hrfee/jfa-go/assets/22730962/3608c888-93b2-4f23-840b-fb3c15a01a33)
windows 10, tray autostart

**Comment by hrfee** [comment]
Try the latest unstable, a retry mechanism was added that tries 6 more times, 10 seconds apart. If that isn't enough to wait for Jellyfin to start, you can increase it in advanced settings.

**Comment by ohitstom** [comment]
perfect I'll keep you posted, my jellyfin takes a while to load due to all my plugins so that's probably why

is there no way to receive a signal and for jfa to sit idle when jellyfin isn't active then? I would have thought once jellyfin had successfully booted it would send out some sort of ping

**Comment by ohitstom** [comment]
sorry where do i find unstable? maybe im dumb, if i have to compile it myself i wouldnt really know where to start

**Comment by hrfee** [comment]
Unstables can be found at https://builds.hrfee.pw/view/hrfee/jfa-go.

**Comment by ohitstom** [comment]
> Unstables can be found at https://builds.hrfee.pw/view/hrfee/jfa-go.

awesome that fixed it :tada:
