### ISSUE TITLE
limit reset password identifiers

### ISSUE THREAD

**Issue by ohitstom** [hrfee/jfa-go#312]
please make it possible to set it so you have to enter an email and cant enter usernames etc
im sick of being spammed with password reset requests by bots

**Comment by hrfee** [comment]
Settings to enable/disable each way of initiating a PWR have been added to the userpage settings.

**Comment by ohitstom** [comment]
is this part of an experimental branch?

**Comment by ohitstom** [comment]
an option to disable password resets for the jellyfin website but still have them for the user login page would also be awesome !

**Comment by hrfee** [comment]
You can do this by just setting the password reset directory to something wrong.

**Comment by ohitstom** [comment]
> You can do this by just setting the password reset directory to something wrong.

would this stop emails etc too?

**Comment by hrfee** [comment]
Not quite sure what you mean, all this would do is make the "forgot password" page on Jellyfin from working.

**Comment by ohitstom** [comment]
sounds good tysm
