### ISSUE TITLE
ERROR updater.go:558: Failed to get latest tag (200): Tag was empty

### ISSUE THREAD

**Issue by toekubpom** [hrfee/jfa-go#313]
I keep getting error messages from log files. 
The message says 
"[ERROR] 22:49:00 updater.go:558: Failed to get latest tag (200): Tag was empty." 
How do I fix it?

**Comment by mastervash** [comment]
Facing this exact issue currently. Did you have any luck in resolving the issue?

**Comment by hrfee** [comment]
This isn't really a bug, it just means no updates were found.
