### ISSUE TITLE
How edit "jellyf.in" 

### ISSUE THREAD

**Issue by GaetanPTX** [hrfee/jfa-go#316]
Hello, how can I modify the link of the "Continue" button, it redirects to https://jellyf.in and not to my jellyfin url, although I have put the url of my jellyfin server in the settings.

This is the validation popup when you have just created your account.
  THANKS

![image](https://github.com/hrfee/jfa-go/assets/51859391/4ab86f5e-7fbe-43fa-91fa-aef54a901995)
![image](https://github.com/hrfee/jfa-go/assets/51859391/41b5cbb6-25b3-40d8-be22-1f28647ec1b7)

**Comment by hrfee** [comment]
The setting is General (Advanced) -> Form success redirect URL. It defaults to the same value you set in Jellyfin > Public address, so make sure that isn't set to "jellyf.in" first.
