### ISSUE TITLE
Mail Issue

### ISSUE THREAD

**Issue by Stetsed** [hrfee/jfa-go#317]
**Describe the bug**

I am trying to configure JFA-GO to use MXRoute as a mail relay using SMTP, however no matter what combo I use it doesn't seem to be working.

**To Reproduce**

1. Get an MXRoute account
2. Set SMTP settings to port 465 with TLS/SSL, or 587 with STARTTLS.
3. It will not succesfully send and just error out

This same configuration DOES work for Gitea with port 587 and STARTTLS and it will succesfuly send e-mails.

**Logs**
jfa-go  | [INFO] 14:16:51  Token requested (login attempt)
jfa-go  | [GIN] GET(/token/login) => 200
jfa-go  | [GIN] GET(/config/update) => 200
jfa-go  | [INFO] 14:16:52  Config requested
jfa-go  | [GIN] GET(/config) => 200
jfa-go  | [GIN] GET(/invites) => 200
jfa-go  | [GIN] GET(/users/announce) => 200
jfa-go  | [GIN] GET(/invites) => 200
jfa-go  | [GIN] GET(/users) => 200
jfa-go  | [GIN] GET(/invites) => 200
jfa-go  | [GIN] GET(/users/announce) => 200
jfa-go  | [GIN] GET(/users) => 200
jfa-go  | [GIN] GET(/users/announce) => 200
jfa-go  | [GIN] GET(/invites) => 200
jfa-go  | [GIN] GET(/users) => 200
jfa-go  | [GIN] GET(/) => 200
jfa-go  | [GIN] GET(/banner.svg) => 200
jfa-go  | [GIN] GET(/css/remixicon.css) => 200
jfa-go  | [GIN] GET(/css/v3bundle.css) => 200
jfa-go  | [GIN] GET(/js/admin.js) => 200
jfa-go  | [GIN] GET(/fonts/hanken-grotesk-v8-cyrillic-ext_latin_vietnamese-500.woff2) => 200
jfa-go  | [GIN] GET(/fonts/hanken-grotesk-v8-cyrillic-ext_latin_vietnamese-regular.woff2) => 200
jfa-go  | [GIN] GET(/fonts/hanken-grotesk-v8-cyrillic-ext_latin_vietnamese-700.woff2) => 200
jfa-go  | [GIN] GET(/css/remixicon.woff2?t=1684338274817) => 200
jfa-go  | [GIN] GET(/lang/admin) => 200
jfa-go  | [GIN] GET(/token/refresh) => 400
jfa-go  | [GIN] GET(/favicon-32x32.png) => 200
jfa-go  | [INFO] 14:18:28  Token requested (login attempt)
jfa-go  | [GIN] GET(/token/login) => 200
jfa-go  | [GIN] GET(/config/update) => 200
jfa-go  | [GIN] GET(/invites) => 200
jfa-go  | [GIN] GET(/users/announce) => 200
jfa-go  | [GIN] GET(/invites) => 200
jfa-go  | [GIN] GET(/users) => 200
jfa-go  | [GIN] GET(/users/announce) => 200
jfa-go  | [GIN] GET(/invites) => 200
jfa-go  | [GIN] GET(/users) => 200
jfa-go  | [INFO] 14:19:45  Config requested
jfa-go  | [GIN] GET(/config) => 200
jfa-go  | [GIN] GET(/invites) => 200
jfa-go  | [GIN] GET(/users) => 200
jfa-go  | [GIN] GET(/users/announce) => 200
jfa-go  | [ERROR] 14:22:05 logger.go:81: mVydvKubzWLds2jBc7qU8g: Failed to send to email1@example.com: Mail Error: SMTP Send timed out
jfa-go  | [GIN] POST(/invites) => 200
jfa-go  | [ERROR] 14:22:12 logger.go:81: ToBhXD6BXdq5jiXXVSeYFS: Failed to send to email2@example.com: Mail Error: SMTP Send timed out
jfa-go  | [GIN] POST(/invites) => 200
jfa-go  | [ERROR] 14:23:43 logger.go:81: pdaFqGYPqSrfavAes8Hopg: Failed to send to email3@example.com: Mail Error: SMTP Send timed out
jfa-go  | [GIN] POST(/invites) => 200

**Configuration**

```
[smtp]
; smtp server connection settings.
; username for smtp. leave blank to user send from address as username.
username        = noreply@example.com
; your email provider should provide different ports for each encryption method. generally 465 for ssl_tls, 587 for starttls.
encryption      = starttls
; smtp server address.
server          = tuesday.mxrouting.net
port            = 587
password        = PasswordForMailServer
; hostname sent when sending hello to the smtp server. some servers don't like the default "localhost" value, such as smtp-relay.gmail.com.
hello_hostname  = localhost
; use if your smtp server's ssl certificate is not trusted by the system.
ssl_cert        = 
; warning, disabling this makes you much more vulnerable to man-in-the-middle attacks
cert_validation = true
; smtp authentication method
auth_type       = 4
```

**Platform/Version**

Docker running the latest commit as of 10c8d4a

**Comment by hrfee** [comment]
MXroute looks expensive so I won't be able to test myself, but the fact it works with gitea sounds interesting. Are all the settings the same, or are there any missing from either?

**Comment by Stetsed** [comment]
Hey @hrfee sorry for the not responding, I have moved away from JFA so I will not be able to test. But as far as I know all the settings where the same. Incase I revisit this(I have moved to LDAP for my authentication systems) I will check it out or if I have the time this vacation to take a stab at it.
