### ISSUE TITLE
For admin translation

### ISSUE THREAD

**Issue by Killianbe** [hrfee/jfa-go#32]
{
    "meta": {
        "name": "French (FR)"
    },
    "strings": {
        "invites": "Invite",
        "accounts": "Comptes",
        "settings": "Reglages,
        "theme": "Thème",
        "inviteDays": "Jours",
        "inviteHours": "Heures",
        "inviteMinutes": "Minutes",
        "inviteNumberOfUses": "Nombre d'utilisateur",
        "warning": "Attention",
        "inviteInfiniteUsesWarning": "les invitationsinfinies peuvent être utilisées abusivement",
        "inviteSendToEmail": "Envoyer à",
        "login": "S'identifier",
        "logout": "Se déconecter",
        "create": "Créer",
        "apply": "Appliquer",
        "delete": "Effacer",
        "submit": "Soumettre",
        "name": "Nom",
        "username": "Nom d'utilisateur",
        "password": "Mot de passe",
        "emailAddress": "Addresse Email",
        "lastActiveTime": "Dernière activité",
        "from": "De,
        "user": "Utilisateur",
        "aboutProgram": "A propros",
        "version": "Version",
        "commitNoun": "Commettre",
        "newUser": "Nouvel utilisateur",
        "profile": "Profil",
        "modifySettings": "Modifier les paramètres",
        "modifySettingsDescription": "Appliquez les paramètres à partir d'un profil existant ou obtenez-les directement auprès d'un utilisateur.",
        "applyHomescreenLayout": "Appliquer la disposition de l'écran d'accueil",
        "sendDeleteNotificationEmail": "Envoyer un e-mail de notification ",
        "sendDeleteNotifiationExample": "Votre compte a été supprimé. ",
        "settingsRestartRequired": "Redémarrage nécessaire ",
        "settingsRestartRequiredDescription": "Un redémarrage est nécessaire pour appliquer certains paramètres que vous avez modifiés. Redémarrer maintenant ou plus tard? "
        "settingsApplyRestartLater": "Appliquer, redémarrer plus tard ",
        "settingsApplyRestartNow": "Appliquer et redémarrer ",
        "settingsApplied": "Paramètres appliqués.",
        "settingsRefreshPage": "Actualisez la page dans quelques secondes ",
        "settingsRequiredOrRestartMessage": "Remarque: {*} indique un champ obligatoire, {R} indique que les modifications nécessitent un redémarrage. ",
        "settingsSave": "Sauver",
        "ombiUserDefaults": "Paramètres par défaut de l'utilisateur Ombi",
        "ombiUserDefaultsDescription": "Créez un utilisateur Ombi et configurez-le, puis sélectionnez-le ci-dessous. Ses paramètres / autorisations seront stockés et appliqués aux nouveaux utilisateurs Ombi créés par jfa-go ",
        "userProfiles": "Profils d'utilisateurs",
        "userProfilesDescription": "Les profils sont appliqués aux utilisateurs lorsqu'ils créent un compte. Un profil inclut les droits d'accès à la bibliothèque et la disposition de l'écran d'accueil. ",
        "userProfilesIsDefault": "Défaut",
        "userProfilesLibraries": "Bibliothèques",
        "addProfile": "Ajouter un profil",
        "addProfileDescription": "Créez un utilisateur Jellyfin et configurez-le, puis sélectionnez-le ci-dessous. Lorsque ce profil est appliqué à une invitation, de nouveaux utilisateurs seront créés avec les paramètres. ",
        "addProfileNameOf": "Nom de profil",
        "addProfileStoreHomescreenLayout": "Enregistrer la disposition de l'écran d'accueil"
    },
    "variableStrings": {
        "settingsRequiredOrRestartMessage": "Remarque: {*} indique un champ obligatoire, {R} indique que les modifications nécessitent un redémarrage. "
    },
    "quantityStrings": {
        "modifySettingsFor": {
            "singular": "Modifier les paramètres pour {n} utilisateur",
            "plural": "Modifier les paramètres pour {n} utilisateurs"
        },
        "deleteNUsers": {
            "singular": "Supprimer {n} utilisateur",
            "plural": "Supprimer {n} utilisateurs"
        },
        "addUser": {
            "singular": "Ajouter un utilisateur",
            "plural": "Ajouter des utilisateurs"
        },
        "deleteUser": {
            "singular": "Supprimer l'utilisateur",
            "plural": "Supprimer les utilisateurs"
        }
    }
}

**Comment by hrfee** [comment]
Wow, didn't expect this, thanks so much! I've changed/added a couple things since the last commit so I might need a couple more, I'll comment with the missing ones in a bit.

**Comment by hrfee** [comment]
Ok, these are the only remaining ones:
```json
{
    "strings": {
        "date": "Date",
        "success": "Success",
        "error": "Error",
        "unknown": "Unknown",
        "inviteNoUsersCreated": "None yet!",
        "inviteUsersCreated": "Created users",
        "inviteNoProfile": "No Profile",
        "copy": "Copy",
        "inviteDateCreated": "Created",
        "inviteRemainingUses": "Remaining uses",
        "inviteNoInvites": "None",
        "inviteExpiresInTime": "Expires in {n}",
        "notifyEvent": "Notify on:",
        "notifyInviteExpiry": "On expiry",
        "notifyUserCreation": "On user creation"
    },
    "quantityStrings": {
        "deletedUser": {
            "singular": "Deleted {n} user.",
            "plural": "Deleted {n} users."
        },
        "appliedSettings": {
            "singular": "Applied settings to {n} user.",
            "plural": "Applied settings to {n} users."
        }
    }
}
```

Also, i noticed your `commitNoun` looks like a verb (as in "to commit"). What would the noun be?

**Comment by hrfee** [comment]
Oh, and there's a new section, sorry.
```json
    "notifications": {
        "changedEmailAddress": "Changed email address of {n}.",
        "userCreated": "User {n} created.",
        "createProfile": "Created profile {n}.",
        "saveSettings": "Settings were saved",
        "setOmbiDefaults": "Stored ombi defaults.",
        "errorConnection": "Couldn't connect to jfa-go.",
        "error401Unauthorized": "Unauthorized. Try refreshing the page.",
        "errorSettingsAppliedNoHomescreenLayout": "Settings were applied, but applying homescreen layout may have failed.",
        "errorHomescreenAppliedNoSettings": "Homescreen layout was applied, but applying settings may have failed.",
        "errorSettingsFailed": "Application failed.",
        "errorLoginBlank": "The username and/or password were left blank.",
        "errorUnknown": "Unknown error.",
        "errorBlankFields": "Fields were left blank",
        "errorDeleteProfile": "Failed to delete profile {n}",
        "errorLoadProfiles": "Failed to load profiles.",
        "errorCreateProfile": "Failed to create profile {n}",
        "errorSetDefaultProfile": "Failed to set default profile.",
        "errorLoadUsers": "Failed to load users.",
        "errorSaveSettings": "Couldn't save settings.",
        "errorLoadSettings": "Failed to load settings.",
        "errorSetOmbiDefaults": "Failed to store ombi defaults.",
        "errorLoadOmbiUsers": "Failed to load ombi users.",
        "errorChangedEmailAddress": "Couldn't change email address of {n}.",
        "errorFailureCheckLogs": "Failed (check console/logs)",
        "errorPartialFailureCheckLogs": "Partial failure (check console/logs)"
    }
```

**Comment by Killianbe** [comment]
No worries, it's normal given the superb work you provide, I'll take care of the translations tomorrow!
Sorry I don't understand this sentence: 'Also, I noticed that your commitNoun looks like a verb (like in "to commit"). What would the name be?
and google translate doesn't help me either ^^

**Comment by hrfee** [comment]
"travail" is a noun (it describes a thing), whereas "travailler" is a verb (it describes an action). "commitNoun" is meant to be a noun, hopefully that helps.

**Comment by hrfee** [comment]
I think it would just be "Commit", GitLab uses it in their french translation.

**Comment by Killianbe** [comment]
I'm doing it tonight! promised!

**Comment by Killianbe** [comment]
{
    "strings": {
        "date": "Date",
        "success": "Succès",
        "error": "Erreur",
        "unknown": "Inconnu",
        "inviteNoUsersCreated": "Aucun pour l'instant!",
        "inviteUsersCreated": "Utilisateurs créer",
        "inviteNoProfile": "Aucun profil",
        "copy": "Copier",
        "inviteDateCreated": "Créer",
        "inviteRemainingUses": "Utilisations restantes",
        "inviteNoInvites": "Aucune",
        "inviteExpiresInTime": "Expires dans {n}",
        "notifyEvent": "Notifier sur:",
        "notifyInviteExpiry": "À l'expiration",
        "notifyUserCreation": "à la création de l'utilisateur"
    },
    "quantityStrings": {
        "deletedUser": {
            "singular": "Supprimer {n} utilisateur.",
            "plural": "Supprimer {n} utilisateurs."
        },
        "appliedSettings": {
            "singular": "Appliquer le paramètre {n} utilisteur.",
            "plural": "Appliquer les paramètres {n} utilisteurs."
        }
    }
}

**Comment by Killianbe** [comment]
"notifications": {
        "changedEmailAddress": "Adresse e-mail modifiée de {n}.",
        "userCreated": "L'utilisateur {n} a été créé.",
        "createProfile": "Profil créé {n}.",
        "saveSettings": "Les paramètres ont été enregistrés",
        "setOmbiDefaults": "Valeurs par défaut de Ombi.",
        "errorConnection": "Impossible de se connecter à jfa-go.",
        "error401Unauthorized": "Non autorisé. Essayez d'actualiser la page.",
        "errorSettingsAppliedNoHomescreenLayout": "Les paramètres ont été appliqués, mais l'application de la disposition de l'écran d'accueil a peut-être échoué.",
        "errorHomescreenAppliedNoSettings": "La disposition de l'écran d'accueil a été appliquée, mais l'application des paramètres a peut-être échoué.",
        "errorSettingsFailed": "L'application a échoué.",
        "errorLoginBlank": "Le nom d'utilisateur et / ou le mot de passe sont vides",
        "errorUnknown": "Erreur inconnue.",
        "errorBlankFields": "Les champs sont vides",
        "errorDeleteProfile": "Échec de la suppression du profil {n}",
        "errorLoadProfiles": "Échec du chargement des profils.",
        "errorCreateProfile": "Échec de la création du profil {n}",
        "errorSetDefaultProfile": "Échec de la définition du profil par défaut",
        "errorLoadUsers": "Échec du chargement des utilisateurs.",
        "errorSaveSettings": "Impossible d'enregistrer les paramètres.",
        "errorLoadSettings": "Échec du chargement des paramètres.",
        "errorSetOmbiDefaults": "Impossible de stocker les valeurs par défaut d'Ombi.",
        "errorLoadOmbiUsers": "Échec du chargement des utilisateurs Ombi.",
        "errorChangedEmailAddress": "Impossible de modifier l'adresse e-mail de {n}.",
        "errorFailureCheckLogs": "Échec (vérifier la console / les journaux)",
        "errorPartialFailureCheckLogs": "Panne partielle (vérifier la console / les journaux)"
    }

**Comment by Killianbe** [comment]
when you push him on the unstable docker, tell me I'm checking if the whole thing makes sense

**Comment by hrfee** [comment]
Thanks, added and will merge into main in a minute, which will trigger the docker build.

**Comment by Killianbe** [comment]
All good!
