### ISSUE TITLE
"Not an admin?" showing up even though option to only allow only admins is set.

### ISSUE THREAD

**Issue by devanteweary** [hrfee/jfa-go#326]
Hey!

Just wanted to let you know the "Not an admin?" prompt is showing up even though I have "Allow admin users only" set and "Allow all users to log in" unchecked. (by the way what's the difference?)

![image](https://github.com/hrfee/jfa-go/assets/29805497/e289bae8-708f-4d76-b713-9e148f3ad2d7)

![image](https://github.com/hrfee/jfa-go/assets/29805497/cbd5c74f-32a7-4698-87a0-5285bbbac09e)

Thank you!

**Comment by hrfee** [comment]
The "allow admin users only" and "allow all users to login" only apply to the admin interface, not to the "My Accounts" page. I'll change the wording to make this clearer.
