### ISSUE TITLE
For mail txt translation

### ISSUE THREAD

**Issue by Cornichon420** [hrfee/jfa-go#33]
I was mounting the volume /opt/jfa-go/data to edit and translate mail messages, but it may be usefull to share my translation :)

created.txt 
```
Un utilisateur a été créé avec ce code {{ .code }}.

Nom: {{ .username }}
Adresse: {{ .address }} 
Date: {{ .time }}  // "Heure" if it's only minutes and hours, I didn't check it
```

invite.txt : 
```
Salut {{ .username }},

Quelqu'un vient de demander une réïnitialisation du mot de passe via Jellyfin.
Si c'était bien toi, renseigne le code PIN en dessous.
Ce code expirera le {{ .expiry_date }}, à {{ .expiry_time }} UTC, soit dans {{ .expires_in }}.
Si ce n'était pas toi, tu peux ignorer ce mail.

PIN: {{ .pin }}

{{ .message }}
```

deleted.txt
```
Ton compte Jellyfin a été supprimé.
Motif : {{ .reason }}

{{ .message }}
```
invite-mail.txt : 
```
Salut,
Tu a été invité à rejoindre Jellyfin.
Pour continuer, suis le lien en dessous.
L'invitation expirera le {{ .expiry_date }}, à {{ .expiry_time }}, soit dans {{ .expires_in }}, alors fais vite !

{{ .invite_link }}
```

**Comment by hrfee** [comment]
Thanks, I hadn't thought of translating these. With all the stuff I've been sent we should have an almost complete french translation soon.

**Comment by Cornichon420** [comment]
With pleasure !
Thanks for all your work, it's so usefull in my server :)

**Comment by hrfee** [comment]
Just wondering, do you also want to translate the email titles?
They are:
```
Invite - Jellyfin
Notice: User created
Notice: Invite expired
Your account was deleted - Jellyfin
```

**Comment by hrfee** [comment]
Also, could you do `expired.txt` as well? Its pretty short:
```
Invite expired.                                                              

Code {{ .code }} expired at {{ .expiry }}. 
```

**Comment by Cornichon420** [comment]
With pleasure

```
Invitation - Jellyfin
Notification : Utilisateur créé
Notification : Invitation expirée
Ton compte a été désactivé - Jellyfin
Réïnitialisation de mot de passe demandée - Jellyfin
```

```
Invitation expirée
Le code {{ .code }} a expiré à {{ .expiry }}.
```

**Comment by hrfee** [comment]
Thanks so much, I'll get this released today or tomorrow, just waiting on one more set of translations for the admin page.

**Comment by Cornichon420** [comment]
I just edit my 2 messages

Add an "s" in the invite-mail.txt
And replace "de" by "du" in the Password reset email title

**Comment by Cornichon420** [comment]
In your last commit, there's a mistake

"Invite Email"

It's "so**I**t" not "sout"
` "inviteExpiry": "L'invitation expirera le {n}, à {n}, soit dans {n}, alors fais vite !", `

**Comment by hrfee** [comment]
Ah, oops. Thanks, just changed both of those things.
