### ISSUE TITLE
Providing a referral Link is not including the URLbase of the JFA instance.

### ISSUE THREAD

**Issue by Rephl3x** [hrfee/jfa-go#335]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

When clicking on the "Copy Link" button under a referral enabled account the Invite URL is being copied as 
https://invite/ytGCJ6rSb5mh7Y6BUuT7aJ missing the URL of the server

Describe the problem, and what you would expect if it isn't clear already.

Click Copy Link and view the past.

What to do to reproduce the problem.

**Logs**
No logs Captured for this other than [GIN] GET(/invite/ytGCJ6rSb5mh7Y6BUuT7aJ) => 200

**Platform/Version**
Docker and latest version

**Comment by Rephl3x** [comment]
I have since tested this by navigating to the JFA-Go's Docker container IP and doing it all locally and the copy button is correctly capturing the IP Address then /invite/code1234

the URL I am attempting to use is https://accounts.domainname.tld/invite/code1234

Is this because the Typescript is seeing the "accounts" in the domain and killing itself?

**Comment by hrfee** [comment]
Closing as this was probably fixed by 272c38e.
