### ISSUE TITLE
Invite create Element box not filling the screen in Mobile

### ISSUE THREAD

**Issue by MuhammadBayiz** [hrfee/jfa-go#339]
**Describe the bug**
In Mobile browsers invite create section is only filing the screen half way, it was quite annoying for me that everything looked narrow so after some searching i find out that `card ~neutral @low flex flex-col gap-2 w-1/2 dark:~d_neutral` class has a rule that defined the box to only fill half the screen with this `.w-1\/2 {
    width: 50%;
}` after changing it to **100%** it fixed the bug.
 
**Screenshots**
Before changing `width: 50%;`
![Screenshot_20240515-083659_Pixel Launcher](https://github.com/hrfee/jfa-go/assets/63660736/880a4e4d-856f-490d-a413-33fc749e904d)
After changing it to `width: 100%;`
![Screenshot_20240515-083711_Pixel Launcher](https://github.com/hrfee/jfa-go/assets/63660736/8ddeb24d-3bc3-41f8-8c58-8603975d2431)

**Platform/Version**
Jfa-go:
• Version 0.5.1
• Commit 46566fb9
• Build Time 2023-12-26 19:15:29 +0000 UTC
• Built By "drone.hrfee.dev"
Running server:
• Linux - Gentoo
• Using precompiled binaries 
Client Platform:
• LineageOS - Android 14
• Google chrome version 124.0.6367.171

**Comment by hrfee** [comment]
Fixed, thank you for pointing it out.
