### ISSUE TITLE
Infinite validation loading from facebook redirection link

### ISSUE THREAD

**Issue by Cornichon420** [hrfee/jfa-go#34]
I posted a link in our facebook private group to invite my friends, and a lot of them have a bug, when they clic on this link, a infinite loading when validating their account.
Their only solution is to copy/paste this link.

I personally couldn't reproduce this bug, but i noticed it's when their web browser didn't remove the facebook redirection URL part.

Of course their account is not created when there is this infinite loading.

**Comment by hrfee** [comment]
So when they click the link, does it just not load, or does it go into an infinite loop when they press "create account"?

**Comment by Cornichon420** [comment]
Yep, an infinite loop when they press "create account"
(Of course their form is ok with my password policy and email)

**Comment by hrfee** [comment]
Facebook messing up the link would make sense, when the form page tries to create an account it tries to get the invite code from the URL. This can probably be mitigated quite easily by having the server embed the invite code into the javascript. I'll change it in a bit.

**Comment by Cornichon420** [comment]
It's not really an issue for me, there's other way to provide the link, but i found it fair to report you this :)

**Comment by Cornichon420** [comment]
It's fixed, thank's :)
