### ISSUE TITLE
TLS/HTTP2 ERROR

### ISSUE THREAD

**Issue by feelingfrance** [hrfee/jfa-go#343]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**
enable tls/http2 , path to TLS Certificate and  key is correct. the server is correct running, but i reboot the server or quit the server, the brower FIREFOX open itself and display Crash report for jfa-go,Error: main.start.func4:569 main.go:569: Failure serving with SSL/TLS: http: Server closed  .....

**To Reproduce**

What to do to reproduce the problem.

**Logs**

```

                        2024/05/26 09:10:48 Using internal storage
jfa-go version: 0.5.1 (46566fb9) TrayIcon
Socket: C:\Users\R2700-6\AppData\Local\Temp\jfa-go.sock
[INFO] 09:10:48  Using TLS/HTTP2
[INFO] 09:10:48  Connected to DB "C:\Users\R2700-6\AppData\Roaming\jfa-go\db"
[INFO] 09:10:48  Using Emby server type
WARNING: Emby compatibility is experimental, and support is limited.
Password resets are not available.
[INFO] 09:10:48  Authenticated with "http://127.0.0.1:8096"
[INFO] 09:10:48  Invite daemon started
[INFO] 09:10:48  User daemon started
[INFO] 09:10:48  Initializing router
[INFO] 09:10:48  Loading routes
[INFO] 09:10:48  Loaded @ 0.0.0.0:8057
[GIN] GET(/invites) => 401
[GIN] GET(/users/announce) => 401
[GIN] GET(/users) => 401
[INFO] 09:10:51  Restart/Quit signal received, give me a second!

main.go:569: Failure serving with SSL/TLS: http: Server closed
goroutine 100 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.Exit({0x1aea540, 0xc0004548d0})
	/drone/src/exit.go:73 +0x2e5
github.com/hrfee/jfa-go/logger.(*Logger).Fatalf(0xc00045e870, {0x1c9760e?, 0x20?}, {0xc000535f60?, 0x1?, 0x1?})
	/drone/src/logger/logger.go:133 +0x142
main.start.func4()
	/drone/src/main.go:569 +0x38a
created by main.start
	/drone/src/main.go:555 +0x3791

                    ```

**If you're using a build with a tray icon, right-click on it and press "Open logs" to access your logs.**

When you notice the problem, check the output of `jfa-go` or get the logs by pressing the "Logs" button in the Settings tab. If the problem is not obvious (e.g a panic (red text) or 'ERROR' log), re-run jfa-go with the `-debug` argument and reproduce the problem. You should then take a screenshot of the output, or paste it here, preferably between \`\`\` tags (e.g \`\`\``Log here`\`\`\`). Remember to censor any personal information.

If nothing catches your eye in the log, access the admin page via your browser, go into the console (Right click > Inspect Element > Console), refresh, reproduce the problem then paste the output here in the same way as above.

**Configuration**

If you see it as necessary, include relevant sections of your `config.ini`, for example, include `[email]` and `[smtp]|[mailgun]` if you have an email issue.

**Platform/Version**

windows 10, jfa-go 0.5.1,FIREFOX

**Comment by hrfee** [comment]
Errors were being logged as fatal by the TLS server code, while the normal one logged them normally. Both should behave the same in the above commit.
