### ISSUE TITLE
[Feature Request] Remove assigned Discord role on account disable/delete

### ISSUE THREAD

**Issue by vodkapmp** [hrfee/jfa-go#353]
It would be neat if when the Discord feature "Apply Role on connection" is in use the bot would remove the assigned role from the users Discord account when the account is disabled or deleted.

Would probably also need to implement a way for it to be re-added if a disabled account is re-enabled.

**Comment by hrfee** [comment]
ffd46ff, 448955c and 28ca022 add another setting just below to auto remove/add is on disable/deletion/enable. It's done when you do any of these through jfa-go, but also in the background, so users that get deleted/disabled outside of jfa-go will have the role removed too.
