### ISSUE TITLE
Password Reset function is case sensitive

### ISSUE THREAD

**Issue by BeepBobCloudy** [hrfee/jfa-go#354]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**

I give the user the possibility to reset his password by email. If the user requests a password reset and is registered as "test", however the user enters "Test" in the reset request form no email will be send. As soon as the user enters "Test" it is working.

**To Reproduce**

See above

**Logs**

If the user enters its name with the wrong capitalization (Info line is missing):
```
[GIN] POST(/jfa-go/my/password/reset/Test => 204
```

If the capitalization matches:
```
[INFO] 12:25:33  Sent password reset message to "test"
[GIN] POST(/jfa-go/my/password/reset/test) => 204
```

**Platform/Version**

Version 0.5.1
Debian GNU/Linux 12 (bookworm)

**Comment by hrfee** [comment]
Weird, I thought Jellyfin itself was case sensitive, but apparently not. I've just updated the mediabrowser library to compare usernames in lowercase when searching, which should fix this.

**Comment by BeepBobCloudy** [comment]
Thank you for the fast reaction. Cant say anything about Jellyfin since I am using Emby but atleast in Emby case doesnt matter.

**Comment by hrfee** [comment]
no problem, and the culprit function in mediabrowser is shared between the two anyway.
