### ISSUE TITLE
Separate web link for resetting password

### ISSUE THREAD

**Issue by MuhammadBayiz** [hrfee/jfa-go#363]
Hi, i would like to suggest to separate "Reset Password" and "Login" pages. Right now I'm using this guide 
https://github.com/hrfee/jfa-go/issues/240#issuecomment-1779875680

To redirect my users to password resetting page but "Reset Password" page not having a seperate subpath in the domain creates an extra step for the user to prese on "reset password" again when it's redirected to jfa-go.

**Comment by hrfee** [comment]
The above commit adds `/my/account/password/reset`. It's loaded with javascript and relies on the `/password/reset` being in the URL, so make you don't remove it if you're gonna reverse proxy it to a different path.

**Comment by MuhammadBayiz** [comment]
Fantastic works flawlessly thanks

**Comment by gigante154** [comment]
I tried but redirect to a "Page not found."

**Comment by devanteweary** [comment]
> The above commit adds `/my/account/password/reset`. It's loaded with javascript and relies on the `/password/reset` being in the URL, so make you don't remove it if you're gonna reverse proxy it to a different path.

Hey there I know I'm kinda late but just finding out about this link...

Here's my URL to the password reset: https://invite.domain.sub/my/account/password/reset

Going to this I get the following simple page:

`Page not found.`
`domain.sub`

If I use my internal `IP:port/my/account/password/reset` I get the same thing.  
http or https doesn't matter

Am I missing something?

**Comment by devanteweary** [comment]
> Fantastic works flawlessly thanks

Hey, do you mind giving me the exact URL to bypass the login and go straight to reset password?
I'm trying `https://invite.domain.sub/my/account/password/reset` but it goes to "Page not found."
