### ISSUE TITLE
Uncaught DOMException: String contains an invalid character when username has ő in it

### ISSUE THREAD

**Issue by Blintmester** [hrfee/jfa-go#364]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**

Describe the problem, and what you would expect if it isn't clear already.

I just set up the project, and tried to login with a user, named Gergő, but I got infinite loading screen and in the js console the above error:

```
Uncaught DOMException: String contains an invalid character
login https://accounts.example.com/js/user.js:1
    onsubmit https://accounts.example.com/js/user.js:1
[user.js:1](https://accounts.example.com/js/user.js)
    login https://accounts.example.com/js/user.js:1
    onsubmit https://accounts.example.com/js/user.js:1
```

<img width="897" alt="Screenshot 2024-08-27 at 17 04 44" src="https://github.com/user-attachments/assets/e1233760-0e5c-42e2-b911-ce28c6bdace9">

<img width="1728" alt="Screenshot 2024-08-27 at 17 04 59" src="https://github.com/user-attachments/assets/ee3eba8a-c7c1-4758-a142-83519b4d1392">

**To Reproduce**

What to do to reproduce the problem.

Create a user with some specific characters (e.g.: Gergő), and try to login with this user.
 
**Logs**

```
[GIN] GET(/my/account) => 200
[INFO] 15:12:56  UserToken request (refresh token)
[GIN] GET(/my/token/refresh) => 400
[GIN] GET(/lang/user) => 200
[GIN] GET(/invites) => 200
[GIN] GET(/users) => 200
[GIN] GET(/users/announce) => 200
[GIN] POST(/activity) => 200
```

**If you're using a build with a tray icon, right-click on it and press "Open logs" to access your logs.**

When you notice the problem, check the output of `jfa-go` or get the logs by pressing the "Logs" button in the Settings tab. If the problem is not obvious (e.g a panic (red text) or 'ERROR' log), re-run jfa-go with the `-debug` argument and reproduce the problem. You should then take a screenshot of the output, or paste it here, preferably between \`\`\` tags (e.g \`\`\``Log here`\`\`\`). Remember to censor any personal information.

If nothing catches your eye in the log, access the admin page via your browser, go into the console (Right click > Inspect Element > Console), refresh, reproduce the problem then paste the output here in the same way as above.

**Configuration**

If you see it as necessary, include relevant sections of your `config.ini`, for example, include `[email]` and `[smtp]|[mailgun]` if you have an email issue.

**Platform/Version**

Kubernetes, using docker image. Tried the `latest`, `testing`, and tried to test with `unstable`, but it just not started.

Include the platform jfa-go is running on (e.g Windows, Linux, Docker), the version (first line of output by `jfa-go` or Settings>About in web UI), and if necessary the browser version and platform.

Browser: from mobile built-in browser, from PC Firefox

Thanks, for checking, I think it's an easy-to-fix bug, but I'm super stupid in js/ts...

**Comment by hrfee** [comment]
Sorry, ran into this issue in another project not too long ago, javascript's base 64 encoder doesn't do unicode. Thankfully I already had a function for it written. It should work fine now.

**Comment by Blintmester** [comment]
Thanks for the quick response and fix! It's working fine!
