### ISSUE TITLE
[Bug] Library Order not working on User Profile Clone

### ISSUE THREAD

**Issue by JamsRepos** [hrfee/jfa-go#373]
#### Read the [FAQ](https://wiki.jfa-go.com/docs/faq/) first!

**Describe the bug**

Library Order does not seem to copy when setting up a User Profile.
Also if possible, could Display settings also be included?

**To Reproduce**

Set up a profile and witness the desired settings not copy. 

**Configuration**

I am ensuring the User Profile is updated within JFA-Go on each change to the base user.

**Comment by hrfee** [comment]
@Brramble I think this field is either new, or not shown in the returned configuration unless a non-default value is set. Either way, it's included in the library struct now and is in 7acdd40.

**Comment by hrfee** [comment]
I'm not able to replicate this, library order copies for me in a quick test (Changed to Shows > Movies, created profile from user and applied from admin and through invite). Which version are you using?

**Comment by JamsRepos** [comment]
Seems like it is working now on the latest Jellyfin and Latest JFA-Go. Hmm, odd. I had to manually apply order on 10.10.0.
