### ISSUE TITLE
Some features if you need ideas :)

### ISSUE THREAD

**Issue by Cornichon420** [hrfee/jfa-go#38]
Once again, thank's for your work, it's so usefull to manage my jellyfin :)

Some ideas :
• A mail confirmation with the username used (a lot of users forget it and try to use their email address !)
• Add a private name note to my invitation (just to manage it more easily)

**Comment by hrfee** [comment]
I've just added the first one, if you want you can add the new translations on Weblate. There's an extra string in the Admin section, and a few more in the Email section.

**Comment by hrfee** [comment]
For the label, there's just one extra string in the language section.

**Comment by Cornichon420** [comment]
You're the boss !
I've just finished to translate it in french :)

**Comment by Cornichon420** [comment]
It's working for me :)

**Comment by Cornichon420** [comment]
Good idea to let the choice between username or e-mail address to login !
Maybe could-it be smart to precise it in the welcome email ?

**Comment by Cornichon420** [comment]
Sometimes users miswrite their email address, so they never receive emails, an email confirmation could be brilliant !

**Comment by hrfee** [comment]
Using the email address instead of a username works by literally creating the Jellyfin account with their email as the username, so if you have it enabled, their email address will be included in the email.

**Comment by hrfee** [comment]
I'll get to adding a confirmation email as well, that's a great idea.

**Comment by hrfee** [comment]
added in ee02671. You can enable it in the settings, and translate on weblate if you want.
