### ISSUE TITLE
Some little "bugs" I noticed

### ISSUE THREAD

**Issue by Cornichon420** [hrfee/jfa-go#39]
- There's a useless space in the PIN code (sent in email), it's not user friendly to copy/paste it
![image](https://user-images.githubusercontent.com/63344585/105699813-3f38db80-5f08-11eb-9f88-dbf20c1f3685.png)

- There's no information if you're trying to create a new account with an already used username (just infinite loop an no creation)

- When I delete a user, could it be possible to delete it in Ombi too ?

- For Français/Deutsch/Nederlands, in the admin menu, there's only the 3 first field translated : 

![image](https://user-images.githubusercontent.com/63344585/105701308-68f30200-5f0a-11eb-8924-ba3b9fde0205.png)

**Comment by hrfee** [comment]
The first two have been fixes in 0619452 and 8af1c13. I thought I'd added ombi deletion, but i'll check.

For the settings page, the first three are static, where as the rest are dynamically loaded. I haven't added translation support for the settings yet, but I'll get around to it soon. Right now i'm working on adding a new setup wizard, so it might be a couple of days.

**Comment by hrfee** [comment]
Just checked, and I've already added the Ombi thing. Could you try it out (create and then delete a user in jfa-go) and see what the output is in the logs?

**Comment by Cornichon420** [comment]
My bad, it works
