### ISSUE TITLE
error formlang.string

### ISSUE THREAD

**Issue by Killianbe** [hrfee/jfa-go#40]
Hi 
i've update docker unstable and i've that error ;) 
```
jfa-go version: git (4fc9bdb)
Socket: /tmp/jfa-go.sock
[INFO] 04:29:13 Failed to load language files: json: cannot unmarshal object into Go struct field formLang.strings of type string
```

**Comment by hrfee** [comment]
Are you still using a custom language file for your account creation form? If so, what does the file look like?

**Comment by Killianbe** [comment]
{
    "meta": {
        "name": "Francais PERSO (FR)"
    },
    "strings": {
        "pageTitle": "Inscription NSL",
        "createAccountHeader": "Création du compte",
        "accountDetails": "Détails",
        "emailAddress": "Email",
        "username": "Pseudo",
        "password": "Mot de passe",
		 "reEnterPassword": "Confirmez mot de passe",
        "reEnterPasswordInvalid": "Les mots de passe ne correspondent pas.",
        "createAccountButton": "Créer le compte",
        "passwordRequirementsHeader": "Mot de passe requis",
        "successHeader": "Succes!",
        "successContinueButton": "Continuer",
        "validationStrings": {
            "length": {
                "singular": "Doit avoir au moins {n} caractère",
                "plural": "Doit avoir au moins {n} caractères"
            },
            "uppercase": {
                "singular": "Doit avoir au moins {n} caractère majuscule",
                "plural": "Must have at least {n} caractère majuscules"
            },
            "lowercase": {
                "singular": "Doit avoir au moins {n} caractère minuscule",
                "plural": "Doit avoir au moins {n} caractère minuscules"
            },
            "number": {
                "singular": "Doit avoir au moins {n} nombre",
                "plural": "Doit avoir au moins {n} nombres"
            },
            "special": {
                "singular": "Doit avoir au moins {n} caractère spécial",
                "plural": "Doit avoir au moins {n} caractères spéciaux"
            }
        }
    }
}

**Comment by hrfee** [comment]
Ah. `validationStrings` is now separate from `strings`. It should be this:
```json
{
    "meta": {
        "name": "Francais PERSO (FR)"
    },
    "strings": {
        "pageTitle": "Inscription NSL",
        "createAccountHeader": "Création du compte",
        "accountDetails": "Détails",
        "emailAddress": "Email",
        "username": "Pseudo",
        "password": "Mot de passe",
        "reEnterPassword": "Confirmez mot de passe",
        "reEnterPasswordInvalid": "Les mots de passe ne correspondent pas.",
        "createAccountButton": "Créer le compte",
        "passwordRequirementsHeader": "Mot de passe requis",
        "successHeader": "Succes!",
        "successContinueButton": "Continuer"
    },
    "validationStrings": {
        "length": {
            "singular": "Doit avoir au moins {n} caractère",
            "plural": "Doit avoir au moins {n} caractères"
        },
        "uppercase": {
            "singular": "Doit avoir au moins {n} caractère majuscule",
            "plural": "Must have at least {n} caractère majuscules"
        },
        "lowercase": {
            "singular": "Doit avoir au moins {n} caractère minuscule",
            "plural": "Doit avoir au moins {n} caractère minuscules"
        },
        "number": {
            "singular": "Doit avoir au moins {n} nombre",
            "plural": "Doit avoir au moins {n} nombres"
        },
        "special": {
            "singular": "Doit avoir au moins {n} caractère spécial",
            "plural": "Doit avoir au moins {n} caractères spéciaux"
        }
    }
}
```

**Comment by Killianbe** [comment]
thx all work :) !
