### ISSUE TITLE
setup.js blocked because of a disallowed MIME type (“text/plain”)

### ISSUE THREAD

**Issue by mezzovide** [hrfee/jfa-go#44]
UI unresponsive, fresh install jfa-go

Firefox log :
Loading module from “http://localhost:8056/js/setup.js” was blocked because of a disallowed MIME type (“text/plain”).

Windows 10

**Comment by hrfee** [comment]
Hi, when you downloaded jfa-go it should have came with a `data` folder. Can you check that `data/web/js/setup.js` exists? If it does (or if you're using docker) are you accessing jfa-go using a reverse proxy on a subdomain (e.g `jellyf.in/accounts`)?

**Comment by mezzovide** [comment]
Yeah, its existed i guess

`[INFO] 18:34:01 Loading routes                                                                                          [INFO] 18:34:01 Loading setup @ 0.0.0.0:8056                                                                            [GIN] GET(/) => 200                                                                                                     [GIN] GET(/js/setup.js) => 200                                                                                          [GIN] GET(/banner.svg) => 200                                                                                           [GIN] GET(/favicon-32x32.png) => 200                                                                                    [GIN] GET(/css/bundle.css) => 200                                                                                       [GIN] GET(/js/setup.js) => 200                                                                                          [GIN] GET(/favicon.ico) => 200                                                                                          [GIN] GET(/) => 200                                                                                                     [GIN] GET(/css/bundle.css) => 200                                                                                       [GIN] GET(/js/setup.js) => 200                                                                                          [GIN] GET(/css/remixicon.css) => 200                                                                                    [GIN] GET(/) => 200                                                                                                     [GIN] GET(/js/setup.js) => 200                                                                                          [GIN] GET(/banner.svg) => 304                                                                                           [GIN] GET(/favicon-32x32.png) => 304          `

**Comment by hrfee** [comment]
Are you using docker? I just realized the stable tag hasn't been updated in a while so it might be broken.

**Comment by hrfee** [comment]
Also, which version are you using? When you run jfa-go, it will print the version at the top like this: 
```
jfa-go version: git (2c8be42)
```

**Comment by mezzovide** [comment]
no, i was using this build before :
https://github.com/hrfee/jfa-go/releases/download/v0.3.0/jfa-go_0.3.0_Windows_x86_64.tar.gz

and then i try with ur nightly build too:
jfa-go version: 0.0.0 (8eed4b0)
https://builds.hrfee.pw/repo/hrfee/jfa-go/build/8eed4b012783f4cf78fcba7635265fc0d95efd48/jfa-go_git-8eed4b0_Windows_x86_64.tar.gz

same issue

**Comment by mezzovide** [comment]
Chrome log :
`setup.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

**Comment by hrfee** [comment]
This is weird, even when I run the same version on windows the MIME type is `text/javascript`. Could you go to the network tab in dev tools, select the setup.js request, and look at the response? It should start like this:
![screenshot](https://user-images.githubusercontent.com/11923517/107153074-8640bb00-6963-11eb-9803-f7a120e30386.png)

**Comment by mezzovide** [comment]
There is no response, i think because it was blocked. all i can get is response header 

`HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 12659
Content-Type: text/plain; charset=utf-8
Last-Modified: Fri, 05 Feb 2021 18:28:33 GMT
Date: Mon, 08 Feb 2021 01:53:41 GMT`

i was searching and stumbled upon this https://github.com/gin-gonic/gin/issues/1584
could be something related to my error?

**Comment by hrfee** [comment]
I doubt it, this is just loading a static file so BindJSON isn't called. Could you try [this](https://builds.hrfee.pw/repo/hrfee/jfa-go/build/b3d7bc7704d7c6d20ba3ef20f5287cec625c9bd4/jfa-go_git-b3d7bc7_Windows_x86_64.tar.gz) build? The internal files are embedded inside the executable, so there is no `data` directory.

**Comment by mezzovide** [comment]
`2021/02/08 09:53:18 Using internal storage                                                                              [INFO] 09:53:18 Failed to load language files: open lang/common\en-us.json: file does not exist `

**Comment by hrfee** [comment]
Ah, the embed library used for the files uses `/`, but since you're on windows the `filepath.Join` function uses `\`. I'll fix that now.

**Comment by hrfee** [comment]
Ok, ive added a fix to [this](https://builds.hrfee.pw/repo/hrfee/jfa-go/build/1f9dce1870efa968b7b23aa5f0ca6a9c56b51ecb/jfa-go_git-1f9dce1_Windows_x86_64.tar.gz) version.

**Comment by mezzovide** [comment]
still the same problem
Loading module from “http://localhost:8056/js/setup.js” was blocked because of a disallowed MIME type (“text/plain”).

**Comment by hrfee** [comment]
Could you open Powershell and run: `Invoke-WebRequest http://localhost:8056/js/setup.js`? It should look like this:
```
StatusCode        : 200                                                                                                                                                   StatusDescription : OK                                                                                                                                                    Content           : (()=>{const v=(e,t,i)=>{let n=new                                                                                                                     
                    XMLHttpRequest;window.URLBase&&(e=window.URLBase+e),n.open("GET",e,!0),n.responseType="json",n.setRequestHeader("Authorization","Bearer 
                    "+window.token),n.setRequestHe…
RawContent        : HTTP/1.1 200 OK
                    Accept-Ranges: bytes
                    Date: Mon, 08 Feb 2021 13:48:54 GMT
                    Content-Length: 12659
                    Content-Type: application/javascript
                    
                    (()=>{const v=(e,t,i)=>{let n=new XMLHttpRequest;window.URLBase&&(e…
Headers           : {[Accept-Ranges, System.String[]], [Date, System.String[]], [Content-Length, System.String[]], [Content-Type, System.String[]]}
Images            : {}
InputFields       : {}
Links             : {@{outerHTML=<a href="?lang=${o}" class="button input ~neutral field mb-half">${t.response[o]}</a>; tagName=A; href=?lang=${o}; class=button input 
                    ~neutral field mb-half}, @{outerHTML=<a href="https://weblate.hrfee.pw">Weblate</a>; tagName=A; href=https://weblate.hrfee.pw}, @{outerHTML=<a 
                    href="https://mailgun.com">Mailgun</a>; tagName=A; href=https://mailgun.com}, @{outerHTML=<a href="https://strftime.ninja/">strftime.ninja</a>; 
                    tagName=A; href=https://strftime.ninja/}}
RawContentLength  : 12659
RelationLink      : {}
```

**Comment by mezzovide** [comment]
```
StatusCode        : 200
StatusDescription : OK
Content           : (()=>{const v=(e,t,i)=>{let n=new XMLHttpRequest;window.URLBase&&(e=window.URLBase+e),n.open("GET",
                    e,!0),n.responseType="json",n.setRequestHeader("Authorization","Bearer
                    "+window.token),n.setRequestHe...
RawContent        : HTTP/1.1 200 OK
                    Accept-Ranges: bytes
                    Content-Length: 12659
                    Content-Type: text/plain; charset=utf-8
                    Date: Mon, 08 Feb 2021 15:10:09 GMT

                    (()=>{const v=(e,t,i)=>{let n=new XMLHttpRequest;window.UR...
Forms             : {}
Headers           : {[Accept-Ranges, bytes], [Content-Length, 12659], [Content-Type, text/plain; charset=utf-8],
                    [Date, Mon, 08 Feb 2021 15:10:09 GMT]}
Images            : {}
InputFields       : {}
Links             : {@{innerHTML=${t.response[o]}; innerText=${t.response[o]}; outerHTML=<A class="button input
                    ~neutral field mb-half" href="?lang=${o}">${t.response[o]}</A>; outerText=${t.response[o]};
                    tagName=A; class=button input ~neutral field mb-half; href=?lang=${o}}, @{innerHTML=Weblate;
                    innerText=Weblate; outerHTML=<A href="https://weblate.hrfee.pw">Weblate</A>; outerText=Weblate;
                    tagName=A; href=https://weblate.hrfee.pw}, @{innerHTML=Mailgun; innerText=Mailgun; outerHTML=<A
                    href="https://mailgun.com">Mailgun</A>; outerText=Mailgun; tagName=A; href=https://mailgun.com},
                    @{innerHTML=strftime.ninja; innerText=strftime.ninja; outerHTML=<A
                    href="https://strftime.ninja/">strftime.ninja</A>; outerText=strftime.ninja; tagName=A;
                    href=https://strftime.ninja/}}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 12659
```

**Comment by hrfee** [comment]
Ok, so the content is right at least. I'll try to force set the content-type header maybe.

**Comment by hrfee** [comment]
Ah, according to [this](https://stackoverflow.com/a/65150421/13261977) stackoverflow post, Go assigns the content-type based on a mapping stored in the System Registry on Windows, so its a pretty common issue since installing/uninstalling software can change the mapping. I guess I'll try to add a built in one so the system doesn't affect this.

**Comment by mezzovide** [comment]
Changing .js from text/plain to application/javascript in the registry, and now it works! damn windows. Solved. Thanks.

**Comment by hrfee** [comment]
I also added a manual override to the latest unstable, so hopefully this issue doesn't plague others.
