### ISSUE TITLE
user profile not working

### ISSUE THREAD

**Issue by mezzovide** [hrfee/jfa-go#46]
new invite with user profile. account created, but user profile not applied.

jellyfin 10.7.0-RC3
jfa-go 0.3.0

**Comment by hrfee** [comment]
Is there any output in the program's log? If not, can you enable debug logging in Settings > General, restart and try again?

**Comment by mezzovide** [comment]
Ok, im not making myself clear here, sorry. user profile (profile,access,parental control) does works, the one that not working is setting user personal preferences from admin control panel (display,home,playback,subtitles,client settings)

**Comment by hrfee** [comment]
What is the output in the log when you try this? And are you applying settings from profile, or an existing user?

**Comment by mezzovide** [comment]
I think its also bugged from jf itself, setting those other user preferences manually from jf admin page isnt working for me (10.7.0-RC3)
