### ISSUE TITLE
Add armhf builds to the Docker container

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [hrfee/jfa-go#47]
Hi,

I'm a Raspberry Pi user, and I use Dockstarter to manage my apps. My Jellyfin and Ombi are installed in docker from Dockstarter because they have their armhf versions in the container.

I would like to use them with jfa-go to have unified authentication and account creation form for my friends. But the Docker version only contains the arm64 version of jfa-go.

Could it be possible to add the armhf edition into it ?
Thanks in advance for your help.
Have a great day

**Comment by hrfee** [comment]
Dockerhub currently does the normal x86_64 builds, but they don't support autobuilding for arm. I've got an rpi 3B (armhf) and a Rockpro64 (arm64) running for other purposes, so I'll look into automating builds on those.

**Comment by LeVraiRoiDHyrule** [comment]
Great ! Thanks for your answer ! Your app is really an excellent initiative.

**Comment by hrfee** [comment]
I've added arm64 and armhf now, currently there is no stable build (`latest`), but `unstable` should be available now.

**Comment by jassycliq** [comment]
I may be wrong but I think the new builds have replaced the previous x86_64 or at least the only builds I can find on dockerhub are arm (stable) and arm64 (unstable).

**Comment by hrfee** [comment]
@jassycliq You're right, I thought that docker would automatically download the latest version for the  right architecture, but it seems not to be.

**Comment by hrfee** [comment]
I've setup docker manifest, so all architectures should now be released properly.
