### ISSUE TITLE
Debug sent email

### ISSUE THREAD

**Issue by mezzovide** [hrfee/jfa-go#48]
Need to debug sent email to the user. Since my smtp provider rewrite the url for invite/confirmation button i cant see if the url sent to the smtp provider if its correct or not. Any way to do this?

**Comment by hrfee** [comment]
It's not really a proper test email, but in the 'invites' tab, you can check the box next to 'send to address' and type an email address there, and then create an invite. It will send an email to that.

**Comment by mezzovide** [comment]
No, what i want to do is see what invite link sent to the email address e.g https://test.com/invite/jdjsiejejej3939xx. Because i cant see it in the email i sent since my smtp server provider rewrite the invite link url to their redirect url, and return 404 page not found as a result. That way i cannot be sure whether their redirect is broken or jfa-go sent a broken invite link

**Comment by mezzovide** [comment]
can you enchance debug console to include the invite link when sending an email?

**Comment by hrfee** [comment]
Also, if you're using a reverse proxy on the `/accounts` subpath, the URL would be `https://test.com/accounts/invite/jdjsiejejej3939xx`. Make sure you have Settings > Invite Emails > URL Base set to `https://test.com/invite` as well.

**Comment by mezzovide** [comment]
ah now its working after i add the host in url base:
```
url_base   = https://test.com/invite
```
```
apache.conf
    ProxyPass "/invite" "http://localhost:8056/invite"
    ProxyPassReverse "/invite" "http://localhost:8056/invite"
```
i got confused because the `url_base` for `/accounts` have different requirement with `url_base` for `/invite`.

**Comment by hrfee** [comment]
Yeha, `[invite_email]/url_base` was added before `[ui]/url_base` was an option. Eventually i'll get rid of it since it's redundant.
