### ISSUE TITLE
email confirmation process returned error

### ISSUE THREAD

**Issue by mezzovide** [hrfee/jfa-go#50]
email confirmation process returned error, and not redirected to the jf login page, but user is created and welcome email also sent.
<pre>
[log]
[DEBUG] 19:47:19 api.go:586: Generating new invite
[GIN/DEBUG] 19:47:19: POST(/invites) => 200 in 10.9988ms;
[DEBUG] 19:47:19 auth.go:89: Auth succeeded
[DEBUG] 19:47:19 api.go:788: Invites requested
[GIN/DEBUG] 19:47:19: GET(/invites) => 200 in 1.9984ms;
[DEBUG] 19:47:27 api.go:478: HXjQWeiFv4iJYfhmvDjiXk: New user attempt
[DEBUG] 19:47:27 api.go:360: HXjQWeiFv4iJYfhmvDjiXk: Email confirmation required
[INFO] 19:47:29 HXjQWeiFv4iJYfhmvDjiXk: Sent user confirmation email to test@test.com
<b>[GIN/DEBUG] 19:47:29: POST(/newUser) => 401 in 2.1991211s;</b>
[DEBUG] 19:47:59 daemon.go:37: Daemon: Checking invites
[DEBUG] 19:48:59 daemon.go:37: Daemon: Checking invites
[DEBUG] 19:49:44 api.go:411: Applying settings from profile "default"
[DEBUG] 19:49:44 api.go:417: Applying policy from profile "default"
[DEBUG] 19:49:44 api.go:425: Applying homescreen from profile "default"
[DEBUG] 19:49:44 api.go:454: test@test.com: Sending welcome email to test@test.com
[INFO] 19:49:46 test@test.com: Sent welcome email to test@test.com
[GIN/DEBUG] 19:49:46: GET(/invite/HXjQWeiFv4iJYfhmvDjiXk?key=xxx => 200 in 2.6689999s;
[INFO] 19:49:48 HXjQWeiFv4iJYfhmvDjiXk: New user failed: User test@test.com already exists
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 401 with 404
</pre>
```
[Request Header]
POST /accounts/newUser HTTP/2
Host: test.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
Accept: */*
Accept-Language: en,id;q=0.7,en-US;q=0.3
Accept-Encoding: gzip, deflate, br
Authorization: Bearer undefined
Content-Type: application/json; charset=UTF-8
Content-Length: 124
Origin: https://test.com
Connection: keep-alive
Referer: https://test.com/accounts/invite/L5oc37skvhq8WszXio7VW5
Cookie: __cfduid=xxx; refresh=xxx
TE: Trailers
```
```
[Response Header]
HTTP/2 401 Unauthorized
date: Wed, 10 Feb 2021 12:41:09 GMT
server: Apache/2.4.46 (Win64) LibreSSL/3.2.3
content-type: application/json; charset=utf-8
content-length: 38
X-Firefox-Spdy: h2
```

**Comment by hrfee** [comment]
Could you try again with the latest git build on the main branch?

**Comment by mezzovide** [comment]
i've tested against build `f72def0` still have some issues
![Untitled](https://user-images.githubusercontent.com/2650084/107736088-cb823580-6d33-11eb-8600-4349504d7037.png)
this page doesnt have theme applied.
and after that if i click `continue`
![Untitled](https://user-images.githubusercontent.com/2650084/107736168-008e8800-6d34-11eb-9211-42a6acf43c0e.png)
[log]
```
[DEBUG] 12:55:02 api.go:478: moTUqeNa5sCLtMrs58M8kH: New user attempt
[DEBUG] 12:55:02 api.go:360: moTUqeNa5sCLtMrs58M8kH: Email confirmation required
[DEBUG] 12:55:03 daemon.go:37: Daemon: Checking invites
[INFO] 12:55:04 moTUqeNa5sCLtMrs58M8kH: Sent user confirmation email to user@user.com
[GIN/DEBUG] 12:55:04: POST(/newUser) => 401 in 2.1790233s;
[DEBUG] 12:55:05 auth.go:89: Auth succeeded
[DEBUG] 12:55:05 api.go:788: Invites requested
[GIN/DEBUG] 12:55:05: GET(/invites) => 200 in 1.0021ms;
[DEBUG] 12:55:05 auth.go:89: Auth succeeded
[DEBUG] 12:55:05 api.go:979: Users requested
[GIN/DEBUG] 12:55:05: GET(/users) => 200 in 2.0018ms;
[DEBUG] 12:55:19 api.go:411: Applying settings from profile "default"
[DEBUG] 12:55:19 api.go:417: Applying policy from profile "default"
[DEBUG] 12:55:19 api.go:425: Applying homescreen from profile "default"
[DEBUG] 12:55:19 api.go:454: user@user.com: Sending welcome email to user@user.com
[INFO] 12:55:21 user@user.com: Sent welcome email to user@user.com
[GIN/DEBUG] 12:55:21: GET(/invite/moTUqeNa5sCLtMrs58M8kH?key=xxx => 200 in 2.3123965s;
[GIN/DEBUG] 12:55:21: GET(/css/bundle.css) => 200 in 0s;
[GIN/DEBUG] 12:55:21: GET(/css/remixicon.css) => 200 in 0s;
[GIN/DEBUG] 12:55:33: GET(/invite/moTUqeNa5sCLtMrs58M8kH?key=xxx => 404 in 5.9996ms;
```

**Comment by hrfee** [comment]
When you click the continue button, where does it redirect you?

**Comment by mezzovide** [comment]
To the "page not found"

**Comment by mezzovide** [comment]
this is log from latest build
```
[GIN/DEBUG] 20:09:48: POST(/accounts/newUser) => 401 in 2.2211029s;
[DEBUG] 20:09:58 api.go:411: Applying settings from profile "default"
[DEBUG] 20:09:58 api.go:417: Applying policy from profile "default"
[DEBUG] 20:09:58 api.go:425: Applying homescreen from profile "default"
[DEBUG] 20:09:58 api.go:454: user@test.com: Sending welcome email to user@test.com
[INFO] 20:10:01 user@test.com: Sent welcome email to user@test.com
[GIN/DEBUG] 20:10:01: GET(/accounts/invite/qbQrYZ9FgLFehWNRW9u4JJ?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZXouYWRyaWFuQGdtYWlsLmNvbSIsImV4cCI6IjE2MTMxNzg1ODYiLCJpbnZpdGUiOiJxYlFyWVo5RmdMRmVoV05SVzl1NEpKIiwicGFzc3dvcmQiOiJoNG56NC1SZXphIiwidHlwZSI6ImNvbmZpcm1hdGlvbiIsInVzZXJuYW1lIjoiYXJlei5hZHJpYW5AZ21haWwuY29tIiwidmFsaWQiOnRydWV9.nf0HrrpDFhWtuX_mtvB0MdhkRYGWWk0IjhqbGr3JChs) => 200 in 2.3736863s;
[GIN/DEBUG] 20:10:02: GET(/accounts/invite/qbQrYZ9FgLFehWNRW9u4JJ?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZXouYWRyaWFuQGdtYWlsLmNvbSIsImV4cCI6IjE2MTMxNzg1ODYiLCJpbnZpdGUiOiJxYlFyWVo5RmdMRmVoV05SVzl1NEpKIiwicGFzc3dvcmQiOiJoNG56NC1SZXphIiwidHlwZSI6ImNvbmZpcm1hdGlvbiIsInVzZXJuYW1lIjoiYXJlei5hZHJpYW5AZ21haWwuY29tIiwidmFsaWQiOnRydWV9.nf0HrrpDFhWtuX_mtvB0MdhkRYGWWk0IjhqbGr3JChs) => 404 in 4.9995ms;
```

**Comment by hrfee** [comment]
Ah, thought i fixed this a while ago. Once it's up, try 1af8d1f.

**Comment by mezzovide** [comment]
fix confirmed. cheers!
