### ISSUE TITLE
Setting a baseurl for reverse proxy breaks login on both inside and outside network (404 error)

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [hrfee/jfa-go#51]
#### Read the [FAQ](https://github.com/hrfee/jfa-go/wiki/FAQ) first!

**Describe the bug**

As soon as a baseurl is set in the settings ( /accounts ), trying to login will lead to this error:

[GIN] GET(/accounts/token/login) => 404

Both connections from the local network or the outside are broken. No way to connect if baseurl is set up. So I can't use jfa-go with my nginx reverse proxy.

**To Reproduce**

Install jfa-go 0.3.0
Set a baseurl
It can no longer login

**Logs**

Logs from jfa-go in debug mode:

`[INFO] 18:56:06 Starting router @ 0.0.0.0:8056
[GIN/DEBUG] 18:56:41: GET(/) => 200 in 24.12524ms;
[GIN/DEBUG] 18:56:41: GET(/css/bundle.css) => 200 in 20.37937ms;
[GIN/DEBUG] 18:56:41: GET(/css/bundle.css) => 200 in 6.337037ms;
[GIN/DEBUG] 18:56:41: GET(/js/admin.js) => 200 in 6.832649ms;
[GIN/DEBUG] 18:56:41: GET(/css/remixicon.css) => 200 in 73.097222ms;
[GIN/DEBUG] 18:56:41: GET(/css/remixicon.css) => 200 in 23.07237ms;
[GIN/DEBUG] 18:56:42: GET(/banner.svg) => 200 in 544.13µs;
[GIN/DEBUG] 18:56:42: GET(/accounts/lang/admin) => 404 in 10.935278ms;
[GIN/DEBUG] 18:56:42: GET(/accounts/token/refresh) => 404 in 9.227796ms;
[GIN/DEBUG] 18:56:42: GET(/css/remixicon.woff2?t=1590207869815) => 200 in 21.925778ms;
[GIN/DEBUG] 18:56:42: GET(/accounts/apple-touch-icon.png) => 404 in 7.966611ms;
[GIN/DEBUG] 18:56:42: GET(/accounts/favicon-32x32.png) => 404 in 8.384926ms;

[GIN/DEBUG] 18:56:48: GET(/accounts/token/login) => 404 in 9.329556ms;
`
The 404 error reproduces at each login tries. It happen on both 
[localip]:8056 ; 
[localip]:8056/accounts ; 
[servername]/accounts

Screenshot:
![image](https://user-images.githubusercontent.com/64923542/107557985-91e9e700-6bda-11eb-9ae3-2fb788331a5a.png)

**Configuration**

Nothing special configured. Did initial setup, connection to Jellyfin successful according the test in initial setup (my Jellyfin is hosted on the same server), and restarted the pi.

**Platform/Version**

Jfa-go 0.3.0 on Raspberry Pi (armv6) , no Docker.

**Comment by hrfee** [comment]
Could you post your nginx configuration?

**Comment by LeVraiRoiDHyrule** [comment]
Hi,

Thanks for your answer.

Here is my full Nginx configuration : https://pastebin.com/56TGAuXE
Jfa-go setup is at 182 line
(dns masked for privacy of course)

But I don't think it has something to see with my Reverse proxy as the problem is here as soon as I turn on the subpath. I had the same issue without even configuring the reverse proxy. Tried with it and it's the same problem.

Thanks in advance for your help, have a great day

**Comment by hrfee** [comment]
Ah, I meant just the jfa-go part, but thanks anyway. It looks fine to me, so could you open the developer console > network tab in your browser then try to log in? You should see something like this:
![image](https://user-images.githubusercontent.com/11923517/107696692-30914900-6caa-11eb-9464-71e6c3eb4662.png)
What is the full URL path? (on the screenshot in the top right mine is `http://localhost:8056/token/login`)

**Comment by LeVraiRoiDHyrule** [comment]
On local network with [localip]:8056
![image](https://user-images.githubusercontent.com/64923542/107706733-1020b900-6cc1-11eb-9e78-2454dd62880c.png)

On local network with [localip]:8056/accounts
![image](https://user-images.githubusercontent.com/64923542/107706789-262e7980-6cc1-11eb-941e-c521f2eda90d.png)

From the outside with [ddns]/accounts

**Comment by hrfee** [comment]
When you're using a URL Base, jfa-go will only work through the reverse proxy. Also could you specifically click on the `login` request and send the URL that's in the top right of the box that opens?

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> When you're using a URL Base, jfa-go will only work through the reverse proxy. Also could you specifically click on the `login` request and send the URL that's in the top right of the box that opens?

That's surprising because Jellyfin and Ombi still works locally when a baseurl is set.

I have no request called "login" when connecting from the outside with my domain.

**Comment by hrfee** [comment]
Ah ok, does the login screen not pop up when the page loads then?
Also i know it's kinda weird, I'll fix it soon.

**Comment by LeVraiRoiDHyrule** [comment]
With the page when connecting from the outside, if I enter my credential and tries to click to login, it fully reloads the page. The requests in the network tab are exactly the same.

**Comment by hrfee** [comment]
Could you check the JavaScript console when you load the page and look for any errors? The only reason I can think of this happening is the JS crashing and not handling the login event.

**Comment by LeVraiRoiDHyrule** [comment]
![image](https://user-images.githubusercontent.com/64923542/107708366-a9e96580-6cc3-11eb-9359-21e859fcdfa8.png)

Do you mean the "JS" tab ? It's empty

**Comment by hrfee** [comment]
Ok, i guess the JS file isn't loaded at all. Could you update to the latest unstable build and try again? I fixed the weird reverse proxy behaviour so `localhost:8056/`, `localhost:8056/accounts` and `domain/accounts` should work now, and the `rewrite` line for nginx shouldn't be necessary.

**Comment by LeVraiRoiDHyrule** [comment]
Where can I download the lastest unstable build ?

**Comment by hrfee** [comment]
[builds.hrfee.pw](https://builds.hrfee.pw/view/hrfee/jfa-go), also docker armhf is up now on the `unstable` tag if you want to switch to it at some point.

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> [builds.hrfee.pw](https://builds.hrfee.pw/view/hrfee/jfa-go), also docker armhf is up now on the `unstable` tag if you want to switch to it at some point.

It works ! It works perfectly both locally and from the outside with my reverse proxy !!!!
Thank you so much for your help !!
That's one more step towards my fully automated jellyfin server.

Thanks again, you're doing an incredible job !
Have a great day or night (or both) !

**Comment by hrfee** [comment]
No worries, i'm honestly surprised someone hadn't asked for it earlier.

**Comment by LeVraiRoiDHyrule** [comment]
I don't think there is that much people using reverse proxy + subpath. The people who use it are probably already using the dev builds

**Comment by MrPotatoBobx** [comment]
its broken again on 0.4.0
and the rewrite line is for it to show up again(#211)
