### ISSUE TITLE
Request access for Greek Translation

### ISSUE THREAD

**Issue by Marketos-Damigos** [hrfee/jfa-go#52]
Hello,

I would like to help with the translation of the project into Greek.

How can I request the addition of the language in weblate?

Thanks in advance.

**Comment by hrfee** [comment]
If you login to weblate with Github, you can add the language yourself in each section (see bottom of picture):
![weblate](https://user-images.githubusercontent.com/11923517/107643218-c3f85900-6c6d-11eb-8937-121720ac48a5.png)

**Comment by Marketos-Damigos** [comment]
Great, i thought you needed to give the rights. 

Closed
