### ISSUE TITLE
Cannot create new user from invite

### ISSUE THREAD

**Issue by gadgetusaf** [hrfee/jfa-go#55]
I am running the unstable version in docker and cannot get it to create a new user in jellyfish. I can create the invite but when we try to test it fails to create the user and stays on the account creation page.

`
form.js:1 GET https://my.domain.tld/invite/0xbd64e0/lang/form 404
`
`
(anonymous) @ form.js:1
`
`
site.webmanifest:1 GET https://my.domain.tld/invite/0xbd64e0/site.webmanifest 404
`
`
site.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.
`
`
rFXZQhzRQQSC7pLBSKHZY5:1 The resource https://my.domain.tld/css/remixicon.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
`
`
rFXZQhzRQQSC7pLBSKHZY5:1 The resource https://my.domain.tld/css/bundle.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
`
`
form.js:1 POST https://my.domain.tld/invite/0xbd64e0/newUser 404
`

**Comment by hrfee** [comment]
Could you run `docker logs <jfa-go container name> | head` and put the output here? This will tell you the version. Based on `https://my.domain.tld/invite/0xbd64e0/newUser` from your log (specifically `0xbd64e0`), it looks like you're running an old version with a bug i fixed recently.

**Comment by gadgetusaf** [comment]
`
jfa-go version: git (f72def0)
`
`
Socket: /tmp/jfa-go.sock
`
`
/opt/jfa-go/data/confirmation.html
`
`
[INFO] 12:53:33 Using Jellyfin server type
`
`
[INFO] 12:53:33 Authenticated with http://10.0.1.104:3636
`
`
[INFO] 12:53:33 Invite daemon started
`
`
[INFO] 12:53:33 Loading routes
`
`
[INFO] 12:53:33 Starting router @ 0.0.0.0:8056
`
`
[GIN] GET(/invite/rFXZQhzRQQSC7pLBSKHZY5) => 200
`
`
[GIN] GET(/invite/0xbd64e0/lang/form) => 404
`

**Comment by hrfee** [comment]
Yeah, this is older than the fix. Could you update your container? The issue should be fixed.

**Comment by gadgetusaf** [comment]
I just pulled the following container and got the same result.
hrfee/jfa-go:unstable

When I tried hrfee/jfa-go:latest it failed to start

**Comment by hrfee** [comment]
Oh, for some reason the new image hasn't been pushed. I'll try get it up now.

**Comment by hrfee** [comment]
For now you can use the `manifest-unstable-amd64` tag if you're using x86_64, i've been trying to set up multi-arch builds which has kinda messed with `unstable`.

**Comment by gadgetusaf** [comment]
That worked! Thanks

**Comment by hrfee** [comment]
@gadgetusaf, `unstable` is fixed now, and since i switched to a different build method, `manifest-unstable-amd64` wont be updated anymore.
