### ISSUE TITLE
Add custom listen path

### ISSUE THREAD

**Issue by Luxumbra27** [hrfee/jfa-go#56]
Hi @hrfee !
Thanks for your work it's exactly what I needed :smile:

Just like in Ombi, Sonarr etc, I would like to have __jfa-go__ listen on a custom path, like `http://0.0.0.0:8056/jfa-go`

I think it would a very useful feature, as jfa-go is supposed to be used in multiple-services environments.

**Comment by hrfee** [comment]
I modified the behaviour of the `URL Base` setting in `General` to do this in f72def0399d73250c7de0bac8d2bbb237401a7f5. For your use case, set it to `/jfa-go`. You can get a nightly build with it [here](https://builds.hrfee.pw/view/hrfee/jfa-go) or on the `unstable` tag on docker. It'll also be in 0.3.1 which I suspect to be out by the end of the month.

**Comment by Luxumbra27** [comment]
That is perfect ! Thanks, running the unstable like a charm now.
