### ISSUE TITLE
standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by joaovitoriasilva** [hrfee/jfa-go#57]
Hello,

I have this docker compose:
version: "2.1"
services:
  jfa-go:
    image: hrfee/jfa-go
    container_name: jfa-go
    #environment:
    #  - PUID=1000
    #  - PGID=1000
    #  - TZ=Europe/Lisbon
    volumes:
      - /mnt/appdata/jfago:/data
      - /mnt/appdata/jellyfin:/jf
      - /etc/localtime:/etc/localtime
    ports:
      - 8056:8056
     # - 8057:8057
    restart: unless-stopped

And I am having this issue:
standard_init_linux.go:219: exec user process caused: exec format error

Can someone help me?

Thanks

**Comment by hrfee** [comment]
This is because your CPU architecture is different from what the executable in the container was compiled for. If you're running on an rpi or some other arm board, I recently set up builds for arm64/armv7, although currently they're only available on the `unstable` docker tag.

**Comment by joaovitoriasilva** [comment]
Running on a Ryzen 5 2600. Not an ARM arch

**Comment by hrfee** [comment]
Ah oops, I guess when I was experimenting with multiarch docker builds I broke the latest tag. Lemme push an amd64 build now.
