### ISSUE TITLE
emails don't work

### ISSUE THREAD

**Issue by bvd13** [hrfee/jfa-go#58]
#### Read the [FAQ](https://github.com/hrfee/jfa-go/wiki/FAQ) first!

**Describe the bug**

When using the password reset functionality in Jellyfin, jfa-go should send an email with the password reset code, but doesnt send the email. The same applies to all other emails jfa-go should send (it doesn't send any emails at the moment).

**To Reproduce**

I use jfa-go docker image unstable tag and the linuxserver jellyfin image stable (10.6.4). When clicking on password reset an email should be sent, but isn't. When deleting an account you can press the option to send an email, but that also doesn't work. I tried restarting and recreating the jfa-go docker image, but I can't find the problem.

**Logs**

\`\`\``[INFO] 22:16:46 New password reset for user "test"
[ERROR] 22:16:46 pwreset.go:87: Failed to construct password reset email for test
[GIN] DELETE(/users) => 200
[ERROR] 22:23:51 api.go:553: 96760feee76e443fa6958e7c01660ce2: Failed to construct account deletion email
`\`\`\`

**Configuration**

I'm using SMTP with TLS

**Platform/Version**

I'm running jfa-go docker unstable image

**Comment by hrfee** [comment]
Could you turn on debug logging in Settings > General, restart and then try again? The program should output an informative error message below the `Failed to construct...` that way.

**Comment by bvd13** [comment]
Here are more detailed logs:
`[DEBUG] 22:34:55 api.go:979: Users requested
[GIN/DEBUG] 22:34:55: GET(/users) => 200 in 130.607286ms;
[INFO] 22:35:04 New password reset for user "test"
[ERROR] 22:35:04 pwreset.go:87: Failed to construct password reset email for test
[DEBUG] 22:35:04 pwreset.go:88: test: Error: template: pattern matches no files: `/opt/jfa-go/data/email.html`
[DEBUG] 22:36:34 api.go:979: Users requested
[GIN/DEBUG] 22:36:34: GET(/users) => 200 in 407.986µs;
[DEBUG] 22:37:02 auth.go:89: Auth succeeded
2021/02/17 22:37:02 Failed to authenticate with Ombi @ ombi:3579: Timed out
[GIN/DEBUG] 22:37:02: DELETE(/users) => 200 in 55.59907ms;
[ERROR] 22:37:02 api.go:553: 665bf07fbf05452a9dcb348749160361: Failed to construct account deletion email
[DEBUG] 22:37:02 api.go:554: 665bf07fbf05452a9dcb348749160361: Error: template: pattern matches no files: `/opt/jfa-go/data/deleted.html``

**Comment by hrfee** [comment]
Does the value in Settings > Password Resets > Custom email (HTML) begin with `jfa-go:`?

**Comment by bvd13** [comment]
![Schermopname (104)](https://user-images.githubusercontent.com/33101779/108271591-536fa180-7171-11eb-81b1-934cd11599e4.png)
These are the settings under Password Resets

**Comment by hrfee** [comment]
Ah, it looks like the behaviour of a function has changed in the latest Go update. I'm working on it now.

**Comment by hrfee** [comment]
Ah lmao, just have to strip the `/` in the path. A new container is being built now.

**Comment by hrfee** [comment]
Up now on the `unstable` tag.
