### ISSUE TITLE
FEATURES REQUEST : Send massive mail

### ISSUE THREAD

**Issue by Killianbe** [hrfee/jfa-go#59]
Hi!
New request! Send massive mail to all my people via jfa 
Thankss

**Comment by hrfee** [comment]
Will add, probably with markdown too.

**Comment by Killianbe** [comment]
Enjoy <3

**Comment by hrfee** [comment]
Added in fa433c8, building now. You can select users in the accounts tab and then press 'Announce', type an email subject and message (with markdown support), and its send to each individually (no cc/bcc for privacy).

**Comment by hrfee** [comment]
Also, there's a couple more strings in `admin` on weblate if you want to translate those.

**Comment by Killianbe** [comment]
It's translated :) !
