### ISSUE TITLE
mail pb 

### ISSUE THREAD

**Issue by Killianbe** [hrfee/jfa-go#60]
![image](https://user-images.githubusercontent.com/16178815/108380679-5d43e400-7207-11eb-9764-108c9fb0b9fd.png)

Hi
Small color problem with each email received via jfa.
And how can I change the big 'JellyFin' at the top?
Thank you !

**Comment by hrfee** [comment]
Which email client are you using? Also I'll make the "Substitute Jellyfin with..." setting apply to the email headers too.

**Comment by Killianbe** [comment]
I use windows mail client 
![image](https://user-images.githubusercontent.com/16178815/108381506-2a4e2000-7208-11eb-8e25-2b5b8000c277.png)

**Comment by Killianbe** [comment]
![image](https://user-images.githubusercontent.com/16178815/108381858-83b64f00-7208-11eb-9fa0-bd1443c6fc6a.png)

**Comment by hrfee** [comment]
Jellyfin will be substituted now, and i've added an override for dark mode that works for me in Apple mail, and hopefully on your end too in fb727e7.

**Comment by Killianbe** [comment]
sorry man, jellyfin don't appear but not substituted
and dark mode don't work.. can we just send text mail?

**Comment by Killianbe** [comment]
![image](https://user-images.githubusercontent.com/16178815/108389285-d0e9ef00-720f-11eb-8031-cced926c5f32.png)

**Comment by hrfee** [comment]
Weird, the substitution works in my dev build but not on docker. Also, apparently Outlook uses a different thing for dark mode, which i added in the 27ef931, maybe that works?

**Comment by hrfee** [comment]
I seem to have magically fixed the substitution in that build too, give it a try.

**Comment by Killianbe** [comment]
Nice plain text work nice, but he's not translate ! :)

**Comment by hrfee** [comment]
So the plaintext emails are in English? Translation is working for me.

**Comment by Killianbe** [comment]
![image](https://user-images.githubusercontent.com/16178815/108527303-6bab0200-72d2-11eb-8ffc-bf57af263109.png)
all settings are in french

**Comment by Killianbe** [comment]
wait that's my bad, i didn't see language settings in email menu :) 
Good job man, love u <3

**Comment by hrfee** [comment]
The user's password is never stored in jfa since that's a pretty bad practice security wise, and I don't plan to change that, but you can modify the email text though pretty easily by:
* Creating a `lang` folder and an `email` folder inside it
* Copying the [fr-fr.json](https://github.com/hrfee/jfa-go/blob/main/lang/email/fr-fr.json) file into the `email` folder
* Modifying the applicable section (`emailConfirmation`)

I might add an email editor in the future though to make this simpler.

**Comment by Killianbe** [comment]
ok man i totaly understand! 
i'll wait mail editor
thanks ! : )

**Comment by hrfee** [comment]
I've finished the email editor in d1b1b90. You can access it in Settings (there is a little edit icon next to "Emails"). Give it a try and let me know if there are any issues, I suspect there'll be some bugs.

**Comment by hrfee** [comment]
Ah, just realized it currently doesn't work with plaintext emails, let me fix that.

**Comment by hrfee** [comment]
40fc5e9 should work with them.
