### ISSUE TITLE
Request - binary builds

### ISSUE THREAD

**Issue by eh8** [hrfee/jfa-go#64]
You can build `jfa-go` on armhf but I think there are some node dependencies that have historically made this impossible for previous versions. If there were precomplied binaries available then I think that would help with stability through future versions.

**Comment by hrfee** [comment]
There are builds in the releases section for stable, and nightlies on [builds.hrfee.pw](https://builds.hrfee.pw/view/hrfee/jfa-go). They're compiled to arm/v6, which I'm pretty sure runs on armhf.

**Comment by hrfee** [comment]
Also I'll look into doing a`jfa-go-bin` on the AUR per your comment pre-edit.

**Comment by hrfee** [comment]
[jfa-go-bin](https://aur.archlinux.org/packages/jfa-go-bin/) now added to the aur.
