### ISSUE TITLE
Path to config for emby

### ISSUE THREAD

**Issue by hackmonker** [hrfee/jfa-go#65]
#### Read the [FAQ](https://github.com/hrfee/jfa-go/wiki/FAQ) first!

**Describe the bug**

What should I put in case of emby for this
-v /opt/jellyfin:/jf

if emby is at /opt/emby?

**To Reproduce**

What to do to reproduce the problem.

**Logs**

When you notice the problem, check the output of `jfa-go`. If the problem is not obvious (e.g a panic (red text) or 'ERROR' log), re-run jfa-go with the `-debug` argument and reproduce the problem. You should then take a screenshot of the output, or paste it here, preferably between \`\`\` tags (e.g \`\`\``Log here`\`\`\`). Remember to censor any personal information.

If nothing catches your eye in the log, access the admin page via your browser, go into the console (Right click > Inspect Element > Console), refresh, reproduce the problem then paste the output here in the same way as above.

**Configuration**

If you see it as necessary, include relevant sections of your `config.ini`, for example, include `[email]` and `[smtp]|[mailgun]` if you have an email issue.

**Platform/Version**

Include the platform jfa-go is running on (e.g Windows, Linux, Docker), the version (first line of output by `jfa-go` or Settings>About in web UI), and if necessary the browser version and platform.

**Comment by hrfee** [comment]
The path to config is only used for Password Resets, which don't work on emby so you can just ignore it and mount nothing to `/jf`.
