### ISSUE TITLE
Registration page broken since 0.3.2

### ISSUE THREAD

**Issue by lyz-code** [hrfee/jfa-go#70]
**Describe the bug**

After upgrading from version 0.2.2 to the `latest` or `unstable` docker versions with application versions `0.3.2` or `git (9875458)` I encounter two issues:

* The user registration page got broken: 

![signal-2021-03-25-215036](https://user-images.githubusercontent.com/24810987/112542733-d3121100-8dac-11eb-8a10-450bc08b4c4c.jpeg)

* The email sent to the users no longer contains a link to the registration page, maybe the variable name has changed?

**To Reproduce**

* Either have existent invitations created with 0.2.2 and upgrade to 0.3.2, or create a new invitation. 
* Check the email to see no registration link.
* Go to one of the links created and see the page broken

**Logs**

The only weird thing I saw in the log was:

```
[ERROR] 22:01:24 Failed to get latest tag (200): Tag was empty
```

In the browser console log I saw the next error:

```
Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

In the line 98:

```
 window.validationStrings = JSON.parse("");
```

**Configuration**

I'm using a personal template for the email, and the variable not expanded is `{{ .invite_link }}`.

**Platform/Version**

Platform: Docker
Versions: 0.3.2 and git (9875458)

**Comment by hrfee** [comment]
What language do you have set in Settings > Email > Language?

**Comment by lyz-code** [comment]
Wow, quick answer xD, `English US`

**Comment by hrfee** [comment]
Are you running on docker or with a binary? Also, could you try running with debug logging on (Enable in settings > general or with the `-debug` flag) and looking for any more errors?

**Comment by hrfee** [comment]
> I'm using a personal template for the email, and the variable not expanded is {{ .invite_link }}.

I assume you meant you customized the email html file yourself, as I recently added a proper email editor and with it changed that variable to `inviteURL`. Have you made any other customizations? An outdated or messed up translation file is the only thing I can think of right now.

**Comment by lyz-code** [comment]
No more errors were shown when debug was active.

Once I changed the email template with the new functionality (awesome btw!) the email got fixed.

The broken page remains. If I manually change the language of the page to any language, the `?lang=fr-fr` attribute is appended to the url and it works fine, but if I remove the variable it gets broken again

**Comment by hrfee** [comment]
Could you change the default form language to something other than english, save, then set it back again? If that doesn't work, could you check the value of `[ui]/language-form` in `<wherever you mounted /data>/config.ini`?

**Comment by lyz-code** [comment]
Changing the form language twice worked :)

Thanks for the debugging
