### ISSUE TITLE
Help Me please

### ISSUE THREAD

**Issue by engancha2** [hrfee/jfa-go#71]
Sorry if this is not the place to ask for this

I can't find the jellyfin configuration path

Could you make some instructions on how to use it please

**Comment by hrfee** [comment]
What operating system are you running Jellyfin on, and are you using Docker?

**Comment by engancha2** [comment]
i use ubuntu 18 and i am not using docker

**Comment by hrfee** [comment]
Check `/etc/jellyfin`, does it contains files like `system.xml` and `migrations.xml`?

**Comment by engancha2** [comment]
> Check `/etc/jellyfin`, does it contains files like `system.xml` and `migrations.xml`?

yess

**Comment by hrfee** [comment]
ok that's the right one then. You should use `-v /etc/jellyfin:/jf` for your docker container then.

**Comment by engancha2** [comment]
I'm a bit lost with docker, I would be so kind to publish the docker code, please.

**Comment by hrfee** [comment]
```shell
docker create --name "jfa-go" -v <where you want to store config & data>:/data -p 8056:8056 -v /etc/jellyfin:/jf -v /etc/localtime:/etc/localtime:ro hrfee/jfa-go
```

**Comment by engancha2** [comment]
Thank you very much, you helped me a lot
I already have it working
Thanks a lot !!!

**Comment by hrfee** [comment]
np.

**Comment by engancha2** [comment]
Hello friend, if you allow me, I make a suggestion

Instead of using Mailgun I recommend that you implement this sendinblue.com service in your app.
sendinblue.com is 100% free up to 300 emails a day

**Comment by hrfee** [comment]
You can use that service through SMTP already, I won't be adding support for any more custom email apis.
