### ISSUE TITLE
Initial setup, email page

### ISSUE THREAD

**Issue by KeyboardDabbler** [hrfee/jfa-go#74]
**Describe the bug**
Nothing major but I believe it may bring confusion to some. I think during the setup wizard, the highlighted text in the below image should be hidden until you select a dropdown option, at which point the "tickbox" and text makes sense. 

**To Reproduce**
Follow initial setup wizard.

![emailSetup](https://user-images.githubusercontent.com/53971316/113250619-52f42a00-931d-11eb-8c6d-60d4ccb5af99.PNG)

![Capture](https://user-images.githubusercontent.com/53971316/113250626-54bded80-931d-11eb-9523-ee19d46d57eb.PNG)

**Comment by hrfee** [comment]
thanks, for some reason the message wasn't in the same element as the checkbox so it wasn't getting hidden.
