### ISSUE TITLE
All user profile settings are not being applied for invited users

### ISSUE THREAD

**Issue by xd003** [hrfee/jfa-go#76]
**Describe the bug**

Describe the problem, and what you would expect if it isn't clear already.

I have created a user profile with all the settings as needed. While inviting a user , i am using that profile but all of the settings from user profile template is not getting applied for invited users

To be very specific , i noticed these 2 settings not being applied at all
1) Max Simulatanous video streams ( i have kept this at 5 , still for invited user its unlimited )
2) Hide this user from login screens on devices they have never signed into ( i have checked this but for invited user its unchecked )

My server type is Emby 

**Platform/Version**
jfa docker v0.3.2

**Comment by hrfee** [comment]
Ah sorry, I don't do much testing on Emby so bugs are likely. I'll look into this now.

**Comment by hrfee** [comment]
Ah, these settings (and a couple others) were missing from the Policy struct in the mediabrowser library. Just updated it to include them, new jfa-go is building now, should be done in <10min. You'll need to switch to the `hrfee/jfa-go:unstable` docker build for the time being.

**Comment by xd003** [comment]
Sure , thanks for quick resolution of issue . I will definitely test it out . There's one other issue which i have noticed ( unrelated to this one ) so will open a new issue for that .Cheers

**Comment by xd003** [comment]
@hrfee i just now tested this with hrfee/jfa-go:unstable . Out of the 2 options that i mentioned , the first one ( Max Simulatanous video streams  ) is now getting applied for invited users but ( Hide this user from login screens on devices they have never signed into) this option is still not getting applied. I think this might be happening since this particular option is not present in Jellyfin

**Comment by hrfee** [comment]
It seems to work for me, have you tried deleting and recreating the profile?

**Comment by hrfee** [comment]
Nevermind, just realised I don't even have that last setting on my testing emby, I thought you were talking about `Hide this user from login screens when connected remotely`. I'll update now and add it.

**Comment by hrfee** [comment]
Which version of emby are you using? I still don't see the setting.

**Comment by hrfee** [comment]
Added, give it a try once its built.

**Comment by xd003** [comment]
Sure , will report here as soon as the docker becomes available

**Comment by xd003** [comment]
Thank you the issue has now been fixed for both of the options i had mentioned
