### ISSUE TITLE
Error after run jfa-go

### ISSUE THREAD

**Issue by williamgh2019** [hrfee/jfa-go#78]
Hi,

After install into /opt directory then I run jfa-go in Ubuntu server it show me error as below:

 Failed to authenticate with Jellyfin @ http://jellyfin.local:8096: Code 0

What could I fix it?

**Comment by hrfee** [comment]
It looks like you didn't finish the initial setup. Could you `rm -r ~/.config/jfa-go` then restart jfa-go? You'll then be able to access the setup wizard at `<your ip>:8056`.

**Comment by williamgh2019** [comment]
After remove then new run is stack as below:

![image](https://user-images.githubusercontent.com/17005582/113813915-fbc9db80-979a-11eb-8f9f-a4103094354b.png)

**Comment by williamgh2019** [comment]
One more thing, could you please help to document how to install on Ubuntu server?

I try to read your MD file here on installation it is really hard as I am not developer. (Server Admin)

Well document is import and really thank you.

**Comment by hrfee** [comment]
Just go to `http://your-server-address:8056` in your browser and follow the instructions.

**Comment by williamgh2019** [comment]
it work thank you.
