### ISSUE TITLE
Feature Request: SMTP Username

### ISSUE THREAD

**Issue by HiNsKeY** [hrfee/jfa-go#8]
Is it possible to add an SMTP username in addition to the other SMTP settings? I use the SendGrid SMTP relay and it requires a username to authenticate.

P.S I love the app though!

**Comment by hrfee** [comment]
added in 8672d7d, sorry this took so long. You can grab a build of the commit [here](builds.hrfee.pw) or the unstable branch if you use docker.

**Comment by HiNsKeY** [comment]
No need to apologise. Thank you!
