### ISSUE TITLE
Add Months Option for User Expiry ( Feature Request )

### ISSUE THREAD

**Issue by xd003** [hrfee/jfa-go#82]
Till now , if i wanted to invite a user for more than 1 month , i would usually invite them for 1 month originally ( as it is the max possible limit ) and then extend the expiry as much as needed , yeah it was a tad bit inconvenient but i still didn't bothered much about it . 

But now since we have user expiry mentioned in welcome email ( which is a pretty good step imo ) so ideally we could have this option of months in user expiry so that we could have the correct expiry mentioned in invited user's email . I know someone could make same arguement for years lol but i am not so sure if it would be bit too much . This year thing could be debatable but we could surely have the option for month as it would almost certainly fit in many people's use case

PS/  i primarily need it for expiry option only but i think you could use replicate and use the very same code for invitation too if needed , it would also help to maintain consistency among both options

**Comment by hrfee** [comment]
Added in d701c5f for both invites & user expiry.

**Comment by xd003** [comment]
Working perfectly , thanks

**Comment by xd003** [comment]
Upon in-depth testing , i have came across a pretty weird bug. Although this could be reproduced very easily . If you aren't able to , lemme know i will send the logs

Issue is that the Month Option in expiry doesn't seem to work when its used alone. If a user is invited for (1-30) Month with 0 day ,0 hour and 0 min the expiry duration is absent in invite link . Jfa-go treats it as if Expiry is disabled . There's not even a need to invite any test user , this issue could be reproduced by just creating the invite links itself , just expand the invite link and see the user Expiry

Apart from Month , if any of days , months or hours is not set at 0 , the expiry seems to be work perfectly  .So  to summarise , you need everything else ( days , hours , minutes ) to be to at 0 and you can create invite link for just N months and check the expiry link

**Comment by hrfee** [comment]
Yeah i can reproduce this, ill see whats going on now.

**Comment by hrfee** [comment]
just pushed the fix 3dc0df0, It was deciding whether user expiry was enabled or not based on the days hours and minutes being zero, just needed to add months.

**Comment by xd003** [comment]
I just updated to the latest jfa-go:unstable and i can still reproduce the issue i have mentioned in this post . If you cannot , lemme know i will send all the logs

**Comment by hrfee** [comment]
Are you 100% sure? Could you open the devtools in your browser (Right click > Inspect Element), go to Network, then create an invite with 1mo expiry? A post request should appear called "invites", click on it and in then click Headers, and scroll down until you find "Request payload". Could you send a screenshot of that? See the below screenshot for an example:
![20210409_14h09m50s_grim](https://user-images.githubusercontent.com/11923517/114185158-50a55780-993d-11eb-9ef1-e4e4cc9fff09.png)

This is for Chrome and similar browsers. On firefox, instead of clicking "Headers" click "Request".

**Comment by xd003** [comment]
I tested it on my laptop and it was working there , so i suspected maybe something wrong on my android device browser. So i cleared the cache and it started working fine now. Cheers
