### ISSUE TITLE
Unknown Error when clicking create account

### ISSUE THREAD

**Issue by CyferShepard** [hrfee/jfa-go#83]
**Describe the bug**

Everything works fine but when i click on the invite link to create an account it processes for a bit and then says "Unknown Error." in red on the button

**To Reproduce**

Create and invite Link
Click the link
Enter valid details
Click create user

**Logs**
![image](https://user-images.githubusercontent.com/24864904/114252688-d7424f00-99a6-11eb-9df0-c0a7c10dc708.png)
Nothing in logs but this stands out to me in console

**Platform/Version**
Running on Linux Version 0.3.3 Not Docker

**Comment by hrfee** [comment]
Could you reproduce the problem and then send the output of jfa-go? It should provide more info.

**Comment by CyferShepard** [comment]
`root@Nexus:/home/cyfer/jfago# ./jfa-go -debug
jfa-go version: 0.3.3 (d51a6ab)

Socket: /tmp/jfa-go.sock
2021/04/10 03:01:15 Using internal storage
[DEBUG] 03:01:15 main.go:351: Loaded config file "/root/.config/jfa-go/config.ini"
[DEBUG] 03:01:15 main.go:353: Loading storage

[INFO] 03:01:15  Using Jellyfin server type

[INFO] 03:01:15  Authenticated with http://10.0.0.99:8096
[DEBUG] 03:01:15 main.go:547: Using Jellyfin for authentication

[INFO] 03:01:15  Invite daemon started

[INFO] 03:01:15  User daemon started

[INFO] 03:01:15  Initializing router

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[DEBUG] 03:01:15 router.go:30: Using default "404.html"
[DEBUG] 03:01:15 router.go:30: Using default "admin.html"
[DEBUG] 03:01:15 router.go:30: Using default "create-success.html"
[DEBUG] 03:01:15 router.go:30: Using default "form-base.html"
[DEBUG] 03:01:15 router.go:30: Using default "form-loader.html"
[DEBUG] 03:01:15 router.go:30: Using default "form.html"
[DEBUG] 03:01:15 router.go:30: Using default "header.html"
[DEBUG] 03:01:15 router.go:30: Using default "invalidCode.html"
[DEBUG] 03:01:15 router.go:30: Using default "password-reset.html"
[DEBUG] 03:01:15 router.go:30: Using default "setup.html"
[INFO] 03:01:15  Loading routes

[GIN-debug] GET    /lang/:page               --> main.(*appContext).GetLanguages-fm (4 handlers)
[GIN-debug] GET    /                         --> main.(*appContext).AdminPage-fm (5 handlers)
[GIN-debug] GET    /accounts                 --> main.(*appContext).AdminPage-fm (5 handlers)
[GIN-debug] GET    /settings                 --> main.(*appContext).AdminPage-fm (5 handlers)
[GIN-debug] GET    /lang/:page/:file         --> main.(*appContext).ServeLang-fm (5 handlers)
[GIN-debug] GET    /token/login              --> main.(*appContext).getTokenLogin-fm (5 handlers)
[GIN-debug] GET    /token/refresh            --> main.(*appContext).getTokenRefresh-fm (5 handlers)
[GIN-debug] POST   /newUser                  --> main.(*appContext).NewUser-fm (5 handlers)
[GIN-debug] GET    /invite/:invCode          --> main.(*appContext).InviteProxy-fm (6 handlers)
[GIN-debug] POST   /logout                   --> main.(*appContext).Logout-fm (6 handlers)
[GIN-debug] DELETE /users                    --> main.(*appContext).DeleteUsers-fm (7 handlers)
[GIN-debug] GET    /users                    --> main.(*appContext).GetUsers-fm (7 handlers)
[GIN-debug] POST   /users                    --> main.(*appContext).NewUserAdmin-fm (7 handlers)
[GIN-debug] POST   /users/extend             --> main.(*appContext).ExtendExpiry-fm (7 handlers)
[GIN-debug] POST   /invites                  --> main.(*appContext).GenerateInvite-fm (7 handlers)
[GIN-debug] GET    /invites                  --> main.(*appContext).GetInvites-fm (7 handlers)
[GIN-debug] DELETE /invites                  --> main.(*appContext).DeleteInvite-fm (7 handlers)
[GIN-debug] POST   /invites/profile          --> main.(*appContext).SetProfile-fm (7 handlers)
[GIN-debug] GET    /profiles                 --> main.(*appContext).GetProfiles-fm (7 handlers)
[GIN-debug] POST   /profiles/default         --> main.(*appContext).SetDefaultProfile-fm (7 handlers)
[GIN-debug] POST   /profiles                 --> main.(*appContext).CreateProfile-fm (7 handlers)
[GIN-debug] DELETE /profiles                 --> main.(*appContext).DeleteProfile-fm (7 handlers)
[GIN-debug] POST   /invites/notify           --> main.(*appContext).SetNotify-fm (7 handlers)
[GIN-debug] POST   /users/emails             --> main.(*appContext).ModifyEmails-fm (7 handlers)
[GIN-debug] POST   /users/settings           --> main.(*appContext).ApplySettings-fm (7 handlers)
[GIN-debug] POST   /users/announce           --> main.(*appContext).Announce-fm (7 handlers)
[GIN-debug] GET    /config/update            --> main.(*appContext).CheckUpdate-fm (7 handlers)
[GIN-debug] POST   /config/update            --> main.(*appContext).ApplyUpdate-fm (7 handlers)
[GIN-debug] GET    /config/emails            --> main.(*appContext).GetEmails-fm (7 handlers)
[GIN-debug] GET    /config/emails/:id        --> main.(*appContext).GetEmail-fm (7 handlers)
[GIN-debug] POST   /config/emails/:id        --> main.(*appContext).SetEmail-fm (7 handlers)
[GIN-debug] POST   /config/emails/:id/state/:state --> main.(*appContext).SetEmailState-fm (7 handlers)
[GIN-debug] GET    /config                   --> main.(*appContext).GetConfig-fm (7 handlers)
[GIN-debug] POST   /config                   --> main.(*appContext).ModifyConfig-fm (7 handlers)
[GIN-debug] POST   /restart                  --> main.(*appContext).restart-fm (7 handlers)
[GIN-debug] GET    /ombi/users               --> main.(*appContext).OmbiUsers-fm (7 handlers)
[GIN-debug] POST   /ombi/defaults            --> main.(*appContext).SetOmbiDefaults-fm (7 handlers)
[ERROR] 03:01:16  Failed to get latest tag (200): Tag was empty
[DEBUG] 03:01:20 api.go:504: mRwphx6FGjTFixdRf6VaWK: New user attempt
[ERROR] 03:01:20  mRwphx6FGjTFixdRf6VaWK New user failed (403): Forbidden, the user may not have the correct permissions.
[GIN/DEBUG] 03:01:20: POST(/newUser) => 401 in 8.317059ms; 
[DEBUG] 03:01:26 api.go:504: mRwphx6FGjTFixdRf6VaWK: New user attempt
[ERROR] 03:01:26  mRwphx6FGjTFixdRf6VaWK New user failed (403): Forbidden, the user may not have the correct permissions.
[GIN/DEBUG] 03:01:26: POST(/newUser) => 401 in 10.123276ms; 
[DEBUG] 03:01:27 api.go:504: mRwphx6FGjTFixdRf6VaWK: New user attempt
[ERROR] 03:01:27  mRwphx6FGjTFixdRf6VaWK New user failed (403): Forbidden, the user may not have the correct permissions.
[GIN/DEBUG] 03:01:27: POST(/newUser) => 401 in 8.404105ms; 
[DEBUG] 03:01:28 api.go:504: mRwphx6FGjTFixdRf6VaWK: New user attempt
[ERROR] 03:01:28  mRwphx6FGjTFixdRf6VaWK New user failed (403): Forbidden, the user may not have the correct permissions.
[GIN/DEBUG] 03:01:28: POST(/newUser) => 401 in 7.187076ms; `

This is the output i get when i ran in debug mode

**Comment by hrfee** [comment]
Perfect, thanks. Does the Jellyfin user for jfa-go definitely have admin privileges?

**Comment by CyferShepard** [comment]
Yes, I made sure that "Allow this user to manage the server" was selected when i created the user

**Comment by CyferShepard** [comment]
Did some testing on a VM server I keep, it seemed to work fine, I now tried deleting the user and making a new admin account but it results in the same issue, so I deleted the jellyfin docker completely and reinstalled it, this seems to have solved the issue, may have been an issue on Jellyfins side creating admin accounts? Il log that error instead with jellyfin

**Comment by hrfee** [comment]
Ah ok, was about to say this seemed more like a bug with Jellyfin, there should have been more log output if it had a reason to fail.
