### ISSUE TITLE
Stuck at Loading Routes

### ISSUE THREAD

**Issue by hackmonker** [hrfee/jfa-go#87]
#### Read the [FAQ](https://github.com/hrfee/jfa-go/wiki/FAQ) first!

I was using the app in my previous server. but when I installed it in the new server, the logs stuck at loading routes

Describe the problem, and what you would expect if it isn't clear already.

1. docker start jfa-go
2. docker logs -f jfa-go
3. stuck at loading routes.
4. cant access the webui

What to do to reproduce the problem.

**Logs**

```
jfa-go version: git (d772e43)

Socket: /tmp/jfa-go.sock
2021/04/21 18:31:14 Using external storage
[INFO] 18:31:14  Using Jellyfin server type
[INFO] 18:31:14  Authenticated with http://jellyfin:8096
[INFO] 18:31:14  User daemon started
[INFO] 18:31:14  Invite daemon started
[INFO] 18:31:14  Starting password reset daemon
[INFO] 18:31:14  Initializing router
[INFO] 18:31:14  Loading routes
```

**Platform/Version**

Ubuntu 18.04 LTS

**Comment by hrfee** [comment]
The log output is normal, weird that you can't access it. What's the output of `docker ps -a  | grep jfa-go`?

**Comment by hackmonker** [comment]
Actually I found out the problem, the config for some reason was outdated. so its a mistake on my end. sorry about that
