### ISSUE TITLE
Unable to open editor

### ISSUE THREAD

**Issue by hackmonker** [hrfee/jfa-go#88]
#### Read the [FAQ](https://github.com/hrfee/jfa-go/wiki/FAQ) first!

**Describe the bug**

When I open the editor, I can edit welcome emails but the other mails does not even open the editor

**To Reproduce**

Open editor, click on edit invite email, go back to main screen

**Logs**

```
Uncaught TypeError: this._templ.conditionals is null
    loadEditor https://domain.com/js/admin.js:146
    onreadystatechange https://domain.com/js/admin.js:4

```
in the console

**Platform/Version**

Ubuntu 18.04 LTS

**Comment by hackmonker** [comment]
ok so I checked and this is broken in the latest unstable. the stable works fine

**Comment by hrfee** [comment]
Sorry, big oversight from me. You can switch to a version before I added the if statement for the welcome email for now, I'll fix this when I get back home.

**Comment by hackmonker** [comment]
yeah sure. thanks

**Comment by hrfee** [comment]
Forgot to mention, it should be fixed now if you update to the latest unstable.

**Comment by hackmonker** [comment]
> 
> 
> Forgot to mention, it should be fixed now if you update to the latest unstable.
not sure if it is a bug or not, but the conditionals is not shown in editor

**Comment by hackmonker** [comment]
![firefox_e9fql6ExVz](https://user-images.githubusercontent.com/46002790/116358276-167ff500-a81b-11eb-8587-e348a1a38adb.png)

**Comment by hrfee** [comment]
Could you open `Inspect Element` in your browser and go the network tab, open the email editor again then click the response named `WelcomeEmail` and send a screenshot os the response tab? It should look something like this, i'm looking specifically for the `conditionals` field:

![s](https://user-images.githubusercontent.com/11923517/116409296-9e6dfb00-a82b-11eb-82ce-cda8f84a4cc1.png)

**Comment by hackmonker** [comment]
yeah np buddy. just a sec.

**Comment by hackmonker** [comment]
somehow its back. no idea how. was trying for 3 days and now its back. 
![firefox_bipyItphc9](https://user-images.githubusercontent.com/46002790/116411621-81e5b900-a853-11eb-998e-7a2f6c58b917.png)

**Comment by hrfee** [comment]
Very weird indeed, the value is hardcoded so no idea why it wasn't showing up.

**Comment by hackmonker** [comment]
hmm. thanks though. really appreciate, how helpful you are :smile:
