### ISSUE TITLE
add a path to the registration HTML file in options

### ISSUE THREAD

**Issue by Killianbe** [hrfee/jfa-go#9]
Hiiiii
add a path to the registration HTML file in options
like customs mails
Pls
Thanks !! & great job!

**Comment by hrfee** [comment]
Are you trying to make you own registration page, or just trying to change how it looks a bit?

**Comment by Killianbe** [comment]
Only change your registration page, majoritary for translate to my language

**Comment by hrfee** [comment]
Ah, ok. I'll get this done then.

**Comment by Killianbe** [comment]
Thx man, i use your docker for information ;)

**Comment by hrfee** [comment]
I've added this in 82d07e423c5638ab41599666661d6a4db1d5c6e1. You can get the docker build on the `hrfee/jfa-go:unstable` branch.

Get the HTML files you want to modify [here](https://github.com/hrfee/jfa-go/tree/main/data/templates).

Once you've modified them, mount the directory containing your edited HTML files to your docker container (e.g `-v /path/to/custom-html:/templates`), then set the new setting "Files/Custom HTML Template Directory" to the path you mounted it to within docker (in my example, it would be `/templates`). Any html in the directory matching the filenames of the original files will be loaded instead.

**Comment by hrfee** [comment]
Also updated the [Appearance](https://github.com/hrfee/jfa-go/wiki/Appearance) wiki page with some information that might be helpful.

**Comment by Killianbe** [comment]
Yeah i've test, all work, great job but Or can we change the language for the password requirements (example: 1 uppercase)?

**Comment by hrfee** [comment]
Sorry i didn't respond earlier, i've added this in 9abb17742700dfc3aebbadfdb513390b72888550, which you can again get on `hrfee/jfa-go:unstable`. Basically, the `validationStrings` variable can be overridden in your `form.html`. You'll need to replace the big block of `<script>` tags below the `<script src="serialize.js"></script>` in your version with this:
```javascript
<script>
var usernameEnabled = {{ .username }}
var validationStrings = {
    "length": {
        "singular": "Must have at least {n} character",
        "plural": "Must have a least {n} characters"
    },
    "uppercase": {
        "singular": "Must have at least {n} uppercase character",
        "plural": "Must have at least {n} uppercase characters"
    },
    "lowercase": {
        "singular": "Must have at least {n} lowercase character",
        "plural": "Must have at least {n} lowercase characters"
    },
    "number": {
        "singular": "Must have at least {n} number",
        "plural": "Must have at least {n} numbers"
    },
    "special": {
        "singular": "Must have at least {n} special character",
        "plural": "Must have at least {n} special characters"
    }
}
</script>
<script src="form.js"></script>
```
I've added some explanation to the Apperance wiki page.

**Comment by hrfee** [comment]
I just pushed another commit which changes the name of `seralize.js` to `common.js`, so when you update, change `<script src="serialize.js"></script>` to `<script src="common.js"></script>`.

**Comment by hrfee** [comment]
another change for 301f502052a1763d9995c624bbab96cd0dae9de2 and onwards, sorry, but this should be the last one. 

Remove `var usernameEnabled = {{ .username }}`,
Change `var validationStrings = {` to `window.validationStrings = {`,
and replace `<script src="form.js"></script>` with `{{ template "form-base" .settings }}`.

The removed bits are now in a separate file, which shouldn't affect your custom HTML in future.

**Comment by Killianbe** [comment]
> 
> 
> Sorry i didn't respond earlier, i've added this in [9abb177](https://github.com/hrfee/jfa-go/commit/9abb17742700dfc3aebbadfdb513390b72888550), which you can again get on `hrfee/jfa-go:unstable`. Basically, the `validationStrings` variable can be overridden in your `form.html`. You'll need to replace the big block of `<script>` tags below the `<script src="serialize.js"></script>` in your version with this:
> 
> ```js
> <script>
> var usernameEnabled = {{ .username }}
> var validationStrings = {
>     "length": {
>         "singular": "Must have at least {n} character",
>         "plural": "Must have a least {n} characters"
>     },
>     "uppercase": {
>         "singular": "Must have at least {n} uppercase character",
>         "plural": "Must have at least {n} uppercase characters"
>     },
>     "lowercase": {
>         "singular": "Must have at least {n} lowercase character",
>         "plural": "Must have at least {n} lowercase characters"
>     },
>     "number": {
>         "singular": "Must have at least {n} number",
>         "plural": "Must have at least {n} numbers"
>     },
>     "special": {
>         "singular": "Must have at least {n} special character",
>         "plural": "Must have at least {n} special characters"
>     }
> }
> </script>
> <script src="form.js"></script>
> ```
> 
> I've added some explanation to the Apperance wiki page.

and change it in admin page. 

Thx man

**Comment by hrfee** [comment]
yeah, if you've customized the admin page as well, then look at the new version in this repo to make sure it's right as well.
