### ISSUE TITLE
email confirm title as invite title 

### ISSUE THREAD

**Issue by recom273** [hrfee/jfa-go#93]
Running the latest docker image 

I just installed jfa-go and totally blown away playing with all the features.

Whatever I put in the "invite" text box - will be placed in the email title of the confirmation email, even if I put different text in the confirmation box - I tried editing the config file with no luck.

Not the end of the world, but it threw me for a short trying to work out what is going on.

**Comment by hrfee** [comment]
Ah, the invite email has the title of the confirmation email, right? Should be fixed in 59a014f, if you wait ~10min you can switch to `hrfee/jfa-go:unstable` on docker to get it.

**Comment by recom273** [comment]
Yes, you got it .. there is also another small thing - the html link on the welcome email doesn't work, its blue, but not functional - you can tell i'm pretty blown away with it all and digging in and testing out every option.

I really like the option to announce to all the accounts - really nice feature.

Thanks!

**Comment by hrfee** [comment]
fixed in 488c2f5, hadn't noticed as i was using a custom email template.

**Comment by recom273** [comment]
Perfect! 

I even impressed myself, the template I made for unraid updates itself too
